(defpackage #:koya-spec/server/web/admin-api/contents
  (:use #:cl #:rove)
  (:import-from #:koya-server/usecases/schema #:replace-schema)
  (:import-from #:koya-spec/server/web/api-support
                #:*webhooks* #:admin #:delivery #:webhook-events #:setup-api #:reset-api
                #:test-schema #:*management-key*)
  (:import-from #:koya-core/schema #:make-field #:make-model #:make-schema #:schema-webhooks #:schema-models)
  (:import-from #:koya-server/infra/db/connection #:disconnect-db #:exec)
  (:import-from #:koya-core/json #:jobject #:jget #:json-null #:jkeys #:parse-json #:json-parse-error)
  (:import-from #:alexandria #:alist-hash-table)
  (:import-from #:flexi-streams #:make-in-memory-input-stream)
  (:import-from #:koya-server/web/app #:app))
(in-package #:koya-spec/server/web/admin-api/contents)

(setup (setup-api))

(teardown (disconnect-db))

(defhook :before (reset-api))

(deftest content-flow
  (let ((tag-id nil) (post-id nil))
    (testing "create a published tag"
      (multiple-value-bind (status json) (admin :post "/admin/api/website/lists/tag" :body (jobject "data" (jobject "name" "lisp") "publish" t))
        (ok (= status 201))
        (ok (string= (jget json "status") "published"))
        (setf tag-id (jget json "id"))))
    (testing "validation errors are 422 with details"
      (multiple-value-bind (status json) (admin :post "/admin/api/website/lists/blog" :body (jobject "data" (jobject "body" "x")))
        (ok (= status 422))
        (ok (string= (jget json "error" "code") "validation_failed"))
        (ok (string= (jget (aref (jget json "error" "details") 0) "field") "title"))))
    (testing "create a draft post, then publish it"
      (multiple-value-bind (status json)
          (admin :post "/admin/api/website/lists/blog"
                 :body (jobject "data" (jobject "title" "Hello" "body" "# Hi" "tags" (vector tag-id))))
        (ok (= status 201))
        (ok (string= (jget json "status") "draft"))
        (ok (eq (jget json "published") json-null))
        (setf post-id (jget json "id")))
      (multiple-value-bind (status json) (delivery "/api/v1/website/lists/blog")
        (ok (= status 200))
        (ok (= (jget json "totalCount") 0) "drafts are not delivered"))
      (multiple-value-bind (status json) (admin :post (format nil "/admin/api/website/lists/blog/~a/publish" post-id))
        (ok (= status 200))
        (ok (string= (jget json "status") "published"))
        (ok (string= (jget json "published" "body") "# Hi")))
      (ok (equal (webhook-events) '("publish" "draft" "publish")) "tag publish, the post's draft save, the post's publish: every event reaches the hook")
      (ok (string= (jget (second (first *webhooks*)) "model") "blog"))
      (ok (string= (jget (second (first *webhooks*)) "contents" "new" "title") "Hello"))
      (ok (string= (first (first *webhooks*)) "https://example.com/hook"))
      (ok (= (length (cdr (assoc "X-KOYA-WEBHOOK-KEY" (third (first *webhooks*)) :test #'string=))) 48)
          "webhook carries the space secret"))
    (testing "uniqueness"
      (multiple-value-bind (status json) (admin :post "/admin/api/website/lists/blog" :body (jobject "data" (jobject "title" "Hello")))
        (ok (= status 422))
        (ok (string= (jget (aref (jget json "error" "details") 0) "code") "unique"))))
    (testing "delivery list and item, with reference expansion and fields"
      (multiple-value-bind (status json) (delivery "/api/v1/website/lists/blog")
        (ok (= status 200))
        (ok (= (jget json "totalCount") 1))
        (ok (= (jget json "limit") 10))
        (let ((item (aref (jget json "contents") 0)))
          (ok (string= (jget item "id") post-id))
          (ok (string= (jget item "title") "Hello"))
          (ok (string= (aref (jget item "tags") 0) tag-id) "references are ids by default")
          (ok (stringp (jget item "publishedAt")))))
      (multiple-value-bind (status json) (delivery "/api/v1/website/lists/blog" :query "include=tags")
        (ok (= status 200))
        (ok (string= (jget (aref (jget (aref (jget json "contents") 0) "tags") 0) "name") "lisp") "include embeds references"))
      (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/lists/blog/~a" post-id) :query "fields=title")
        (ok (= status 200))
        (ok (equal (sort (jkeys json) #'string<) '("createdAt" "id" "publishedAt" "revisedAt" "title" "updatedAt"))
            "fields narrows the data; the system fields are always there, as the type says"))
      (multiple-value-bind (status json) (delivery "/api/v1/website/lists/blog" :query "fields=title")
        (ok (= status 200))
        (ok (equal (sort (jkeys (aref (jget json "contents") 0)) #'string<)
                   '("createdAt" "id" "publishedAt" "revisedAt" "title" "updatedAt"))
            "in a list too"))
      (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/lists/blog/~a" post-id) :query "include=tags")
        (ok (= status 200))
        (ok (string= (jget (aref (jget json "tags") 0) "id") tag-id) "embedded object carries its id"))
      (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/lists/blog/~a" post-id) :query "include=title")
        (ok (= status 400))
        (ok (string= (jget json "error" "code") "bad_query") "include of a non-reference field is rejected"))
      (multiple-value-bind (status) (delivery "/api/v1/website/lists/blog" :query "filters=title[equals]Hello")
        (ok (= status 200)))
      (multiple-value-bind (status json) (delivery "/api/v1/website/lists/blog" :query "q=hell")
        (ok (= status 200))
        (ok (= (jget json "totalCount") 1) "q searches over HTTP"))
      (multiple-value-bind (status json) (delivery "/api/v1/website/lists/blog" :query "q=nothing-like-this")
        (ok (= status 200))
        (ok (= (jget json "totalCount") 0)))
      (multiple-value-bind (status json) (admin :get "/admin/api/website/lists/blog" :query "q=nothing-like-this")
        (ok (= status 200))
        (ok (= (jget json "totalCount") 0) "and over the admin API"))
      (multiple-value-bind (status json) (delivery "/api/v1/website/lists/blog" :query "filters=nope[equals]1")
        (ok (= status 400))
        (ok (string= (jget json "error" "code") "bad_query")))
      (multiple-value-bind (status json) (delivery "/api/v1/website/lists/blog" :query "offset=99999999999999999999999")
        (ok (= status 400))
        (ok (string= (jget json "error" "code") "bad_query") "an offset too large to bind is a bad query")))
    (testing "draft edits and preview with draftKey"
      (multiple-value-bind (status json) (admin :patch (format nil "/admin/api/website/lists/blog/~a" post-id) :body (jobject "data" (jobject "title" "Hello v2")))
        (ok (= status 200))
        (ok (string= (jget json "status") "published+draft"))
        (ok (string= (jget json "draft" "title") "Hello v2"))
        (ok (string= (jget json "draft" "body") "# Hi") "patch merges onto existing data"))
      (multiple-value-bind (status json) (admin :post (format nil "/admin/api/website/lists/blog/~a/draft-key" post-id))
        (ok (= status 200))
        (let ((key (jget json "draftKey")))
          (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/lists/blog/~a" post-id))
            (ok (= status 200))
            (ok (string= (jget json "title") "Hello") "without key: published"))
          (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/lists/blog/~a" post-id) :query (format nil "draftKey=~a" key))
            (ok (= status 200))
            (ok (string= (jget json "title") "Hello v2") "with key: draft"))
          (multiple-value-bind (status) (delivery (format nil "/api/v1/website/lists/blog/~a" post-id) :query "draftKey=wrong")
            (ok (= status 200) "wrong key falls back to published")))))
    (testing "discard a draft on a published content"
      (multiple-value-bind (status json) (admin :patch (format nil "/admin/api/website/lists/blog/~a" post-id) :body (jobject "data" (jobject "title" "Draft edit")))
        (ok (= status 200))
        (ok (string= (jget json "status") "published+draft")))
      (multiple-value-bind (status json) (admin :post (format nil "/admin/api/website/lists/blog/~a/discard-draft" post-id))
        (ok (= status 200))
        (ok (string= (jget json "status") "published"))
        (ok (eq (jget json "draft") json-null))
        (ok (string= (jget json "published" "title") "Hello") "published data untouched"))
      (multiple-value-bind (status json) (admin :post "/admin/api/website/lists/blog" :body (jobject "data" (jobject "title" "Never published")))
        (ok (= status 201))
        (multiple-value-bind (status json) (admin :post (format nil "/admin/api/website/lists/blog/~a/discard-draft" (jget json "id")))
          (ok (= status 409) "a draft-only content has nothing to fall back to")
          (ok (string= (jget json "error" "code") "not_published")))
        (admin :delete (format nil "/admin/api/website/lists/blog/~a" (jget json "id")))))
    (testing "unpublish and delete"
      (multiple-value-bind (status json) (admin :post (format nil "/admin/api/website/lists/blog/~a/unpublish" post-id))
        (ok (= status 200))
        (ok (string= (jget json "status") "draft")))
      (multiple-value-bind (status) (delivery (format nil "/api/v1/website/lists/blog/~a" post-id))
        (ok (= status 404)))
      (multiple-value-bind (status json) (admin :delete (format nil "/admin/api/website/lists/blog/~a" post-id))
        (ok (= status 200))
        (ok (eq (jget json "deleted") t)))
      (multiple-value-bind (status) (admin :get (format nil "/admin/api/website/lists/blog/~a" post-id))
        (ok (= status 404)))
      (ok (equal (webhook-events) '("publish" "draft" "publish" "draft" "draft" "discard" "draft" "discard" "unpublish" "discard"))
          "every entry the history records is sent with its kind; a delete as delete while published, as discard when only a draft"))))

(deftest import-style-create
  (testing "explicit id and publishedAt"
    (multiple-value-bind (status json)
        (admin :post "/admin/api/website/lists/tag"
               :body (jobject "data" (jobject "name" "old") "publish" t "id" "hg2papkhis4" "publishedAt" "2025-04-30T15:00:00.000Z"))
      (ok (= status 201))
      (ok (string= (jget json "id") "hg2papkhis4"))
      (ok (string= (jget json "publishedAt") "2025-04-30T15:00:00.000Z")))
    (multiple-value-bind (status json) (delivery "/api/v1/website/lists/tag/hg2papkhis4")
      (ok (= status 200))
      (ok (string= (jget json "publishedAt") "2025-04-30T15:00:00.000Z")))
    (multiple-value-bind (status json) (admin :post "/admin/api/website/lists/tag" :body (jobject "data" (jobject "name" "dup") "id" "hg2papkhis4"))
      (ok (= status 409))
      (ok (string= (jget json "error" "code") "conflict")))
    (multiple-value-bind (status) (admin :post "/admin/api/website/lists/tag" :body (jobject "data" (jobject "name" "x") "id" "bad id!"))
      (ok (= status 400)))
    (multiple-value-bind (status json) (admin :post "/admin/api/website/lists/tag" :body (jobject "data" (jobject "name" "x") "id" "new"))
      (ok (= status 400) "new is the admin UI's new-content form, so no content takes it as its id")
      (ok (string= (jget json "error" "code") "bad_request")))
    (multiple-value-bind (status) (admin :post "/admin/api/website/lists/tag" :body (jobject "data" (jobject "name" "x") "publish" t "publishedAt" "yesterday"))
      (ok (= status 400))))
  (testing "publish with publishedAt override"
    (multiple-value-bind (status json) (admin :post "/admin/api/website/lists/tag" :body (jobject "data" (jobject "name" "later")))
      (ok (= status 201))
      (multiple-value-bind (status json) (admin :post (format nil "/admin/api/website/lists/tag/~a/publish" (jget json "id"))
                                                :body (jobject "publishedAt" "2024-01-01T00:00:00.000Z"))
        (ok (= status 200))
        (ok (string= (jget json "publishedAt") "2024-01-01T00:00:00.000Z"))))))

(deftest object-model
  (multiple-value-bind (status) (delivery "/api/v1/website/objects/about")
    (ok (= status 404) "nothing yet"))
  (multiple-value-bind (status json) (admin :get "/admin/api/website/objects/about")
    (ok (= status 404) "nor anything to read before its first write")
    (ok (string= (jget json "error" "code") "not_found")))
  (testing "an object is not created as a list content"
    (multiple-value-bind (status json) (admin :post "/admin/api/website/lists/about" :body (jobject "data" (jobject "body" "about me") "publish" t))
      (ok (= status 404))
      (ok (string= (jget json "error" "code") "not_found")))
    (ok (<= 400 (admin :post "/admin/api/website/objects/about" :body (jobject "data" (jobject "body" "about me") "publish" t)) 499)
        "nor posted to its model")
    (ok (= 404 (admin :get "/admin/api/website/objects/about")) "so nothing is made")
    (ok (null *webhooks*) "and nothing is sent"))
  (testing "it is delivered at its model, and not as a list"
    (admin :post "/admin/api/website/objects/about/publish" :body (jobject "data" (jobject "body" "about me")))
    (let ((id (jget (nth-value 1 (admin :get "/admin/api/website/objects/about")) "id")))
      (multiple-value-bind (status json) (delivery "/api/v1/website/objects/about")
        (ok (= status 200))
        (ok (string= (jget json "body") "about me")))
      (ok (= 404 (delivery "/api/v1/website/lists/about")))
      (ok (= 404 (delivery (format nil "/api/v1/website/lists/about/~a" id))) "its id does not reach it either")))
  (testing "a list is not delivered as an object"
    (admin :post "/admin/api/website/lists/tag" :body (jobject "data" (jobject "name" "lisp") "publish" t))
    (ok (= 404 (delivery "/api/v1/website/objects/tag")))))

(deftest an-object-is-reached-through-its-model
  (let ((id nil))
    (testing "the first draft saved at the model makes its content"
      (multiple-value-bind (status json) (admin :patch "/admin/api/website/objects/about" :body (jobject "data" (jobject "body" "draft")))
        (ok (= status 200))
        (ok (string= (jget json "status") "draft"))
        (setf id (jget json "id"))))
    (testing "the model answers with that content, not a list"
      (multiple-value-bind (status json) (admin :get "/admin/api/website/objects/about")
        (ok (= status 200))
        (ok (string= (jget json "id") id))
        (ok (string= (jget json "draft" "body") "draft"))))
    (testing "and changes it"
      (multiple-value-bind (status json) (admin :post "/admin/api/website/objects/about/publish")
        (ok (= status 200))
        (ok (string= (jget json "published" "body") "draft")))
      (multiple-value-bind (status json) (admin :patch "/admin/api/website/objects/about" :body (jobject "data" (jobject "body" "edit")))
        (ok (= status 200))
        (ok (string= (jget json "status") "published+draft"))
        (ok (string= (jget json "id") id) "the same content"))
      (multiple-value-bind (status json) (admin :post "/admin/api/website/objects/about/draft-key")
        (ok (= status 200))
        (multiple-value-bind (status preview) (delivery "/api/v1/website/objects/about" :query (format nil "draftKey=~a" (jget json "draftKey")))
          (ok (= status 200))
          (ok (string= (jget preview "body") "edit"))))
      (multiple-value-bind (status json) (admin :post "/admin/api/website/objects/about/discard-draft")
        (ok (= status 200))
        (ok (string= (jget json "status") "published")))
      (multiple-value-bind (status json) (admin :post "/admin/api/website/objects/about/publish" :body (jobject "data" (jobject "body" "given")))
        (ok (= status 200))
        (ok (string= (jget json "published" "body") "given")))
      (multiple-value-bind (status json) (admin :post "/admin/api/website/objects/about/unpublish")
        (ok (= status 200))
        (ok (string= (jget json "status") "draft"))))
    (testing "its id does not reach it"
      (setf *webhooks* '())
      (dolist (call `((:get ,id) (:patch ,id ,(jobject "data" (jobject "body" "by id"))) (:delete ,id)
                      (:post ,(format nil "~a/publish" id)) (:post ,(format nil "~a/unpublish" id))
                      (:post ,(format nil "~a/discard-draft" id)) (:post ,(format nil "~a/draft-key" id))))
        (destructuring-bind (method path &optional body) call
          (multiple-value-bind (status json) (admin method (format nil "/admin/api/website/lists/about/~a" path) :body body)
            (ok (= status 404) (format nil "~a ~a" method path))
            (ok (string= (jget json "error" "code") "not_found")))))
      (ok (null *webhooks*) "and nothing is changed or sent")
      (ok (string= (jget (nth-value 1 (admin :get "/admin/api/website/objects/about")) "draft" "body") "given")))
    (testing "nor is it deleted"
      (multiple-value-bind (status) (admin :delete "/admin/api/website/objects/about")
        (ok (<= 400 status 499)))
      (ok (= 200 (admin :get "/admin/api/website/objects/about")))))
  (testing "the first write at the model can publish"
    (reset-api)
    (multiple-value-bind (status json) (admin :post "/admin/api/website/objects/about/publish")
      (ok (= status 404) "though not with no data")
      (ok (string= (jget json "error" "code") "not_found")))
    (multiple-value-bind (status json) (admin :post "/admin/api/website/objects/about/publish" :body (jobject "data" (jobject "body" "live")))
      (ok (= status 200))
      (ok (string= (jget json "status") "published"))))
  (testing "a list model has no content of its own"
    (dolist (call '((:get "") (:patch "") (:post "/publish") (:post "/unpublish") (:post "/discard-draft") (:post "/draft-key")))
      (destructuring-bind (method suffix) call
        (multiple-value-bind (status json) (admin method (format nil "/admin/api/website/objects/blog~a" suffix)
                                                  :body (jobject "data" (jobject "title" "Mine")))
          (ok (= status 404) (format nil "~a blog~a" method suffix))
          (ok (string= (jget json "error" "code") "not_found")))))
    (ok (zerop (jget (nth-value 1 (admin :get "/admin/api/website/lists/blog")) "totalCount")) "and nothing is made")))

(deftest a-referenced-content-stays
  (flet ((make (model data)
           (jget (nth-value 1 (admin :post (format nil "/admin/api/website/lists/~a" model)
                                     :body (jobject "data" data "publish" t)))
                 "id")))
    (let* ((tag (make "tag" (jobject "name" "lisp")))
           (post (make "blog" (jobject "title" "Uses it" "tags" (vector tag)))))
      (testing "deleting or unpublishing it is refused while a content refers to it"
        (multiple-value-bind (status json) (admin :delete (format nil "/admin/api/website/lists/tag/~a" tag))
          (ok (= status 409))
          (ok (string= (jget json "error" "code") "in_use"))
          (ok (search "referenced by 1 other content" (jget json "error" "message"))))
        (multiple-value-bind (status json) (admin :post (format nil "/admin/api/website/lists/tag/~a/unpublish" tag))
          (ok (= status 409))
          (ok (string= (jget json "error" "code") "in_use")))
        (ok (string= (jget (nth-value 1 (delivery (format nil "/api/v1/website/lists/tag/~a" tag))) "name") "lisp")
            "and it is still delivered"))
      (testing "a draft that still refers to it counts too"
        (admin :patch (format nil "/admin/api/website/lists/blog/~a" post) :body (jobject "data" (jobject "tags" #())))
        (ok (= 409 (admin :delete (format nil "/admin/api/website/lists/tag/~a" tag))) "the published data still does")
        (admin :post (format nil "/admin/api/website/lists/blog/~a/publish" post)))
      (testing "a draft that is referred to is not published, so it is refused as that, not as in use"
        (let ((draft (jget (nth-value 1 (admin :post "/admin/api/website/lists/tag" :body (jobject "data" (jobject "name" "draft"))))
                           "id")))
          (admin :patch (format nil "/admin/api/website/lists/blog/~a" post) :body (jobject "data" (jobject "tags" (vector tag draft))))
          (multiple-value-bind (status json) (admin :post (format nil "/admin/api/website/lists/tag/~a/unpublish" draft))
            (ok (= status 409))
            (ok (string= (jget json "error" "code") "not_published")))
          (ok (= 409 (admin :delete (format nil "/admin/api/website/lists/tag/~a" draft))) "but not deleted")
          (admin :patch (format nil "/admin/api/website/lists/blog/~a" post) :body (jobject "data" (jobject "tags" #())))))
      (testing "once the reference is taken out, it goes"
        (ok (= 200 (admin :post (format nil "/admin/api/website/lists/tag/~a/unpublish" tag))))
        (ok (= 200 (admin :delete (format nil "/admin/api/website/lists/tag/~a" tag)))))))
  (testing "a reference field removed by a deploy no longer holds anything"
    (let ((tag (jget (nth-value 1 (admin :post "/admin/api/website/lists/tag"
                                         :body (jobject "data" (jobject "name" "cl") "publish" t)))
                     "id")))
      (admin :post "/admin/api/website/lists/blog" :body (jobject "data" (jobject "title" "Keeps an id" "tags" (vector tag))))
      (ok (= 409 (admin :delete (format nil "/admin/api/website/lists/tag/~a" tag))))
      (replace-schema "website" (make-schema :models (list (make-model "blog" :list (list (make-field :title :text :required t)))
                                                        (make-model "tag" :list (list (make-field :name :text :required t)))
                                                        (make-model "about" :object (list (make-field :body :richtext))))))
      (unwind-protect
           (ok (= 200 (admin :delete (format nil "/admin/api/website/lists/tag/~a" tag))))
        (replace-schema "website" (test-schema))))))

(deftest a-patch-that-changes-nothing-writes-nothing
  (let ((id (jget (nth-value 1 (admin :post "/admin/api/website/lists/tag"
                                      :body (jobject "data" (jobject "name" "same") "publish" t)))
                  "id")))
    (setf *webhooks* '())
    (multiple-value-bind (status json) (admin :patch (format nil "/admin/api/website/lists/tag/~a" id)
                                              :body (jobject "data" (jobject "name" "same")))
      (ok (= status 200))
      (ok (string= (jget json "status") "published") "no draft is made"))
    (ok (null *webhooks*) "and nothing is sent")))

(deftest what-a-status-cannot-do-is-refused
  (flet ((make (publish)
           (nth-value 1 (admin :post "/admin/api/website/lists/tag"
                               :body (jobject "data" (jobject "name" "kept") "publish" publish))))
         (same-afterwards (made)
           (multiple-value-bind (status json) (admin :get (format nil "/admin/api/website/lists/tag/~a" (jget made "id")))
             (and (= status 200)
                  (string= (jget json "updatedAt") (jget made "updatedAt"))
                  (equal (jget json "draftKey") (jget made "draftKey"))))))
    (testing "discarding when a published content has no draft"
      (let ((made (make t)))
        (setf *webhooks* '())
        (sleep 0.01)
        (multiple-value-bind (status json) (admin :post (format nil "/admin/api/website/lists/tag/~a/discard-draft" (jget made "id")))
          (ok (= status 409))
          (ok (string= (jget json "error" "code") "no_draft")))
        (ok (same-afterwards made) "the content is not touched")
        (ok (null *webhooks*) "and nothing is sent")))
    (testing "unpublishing a content that is not published"
      (let ((made (make nil)))
        (setf *webhooks* '())
        (sleep 0.01)
        (multiple-value-bind (status json) (admin :post (format nil "/admin/api/website/lists/tag/~a/unpublish" (jget made "id")))
          (ok (= status 409))
          (ok (string= (jget json "error" "code") "not_published")))
        (ok (same-afterwards made) "the content is not touched, and its draft key still works")
        (ok (null *webhooks*) "and nothing is sent")))))

(defun admin-octets (method path octets)
  (let ((env (list :request-method method :script-name "" :path-info path :query-string ""
                   :server-name "localhost" :server-port 3000 :server-protocol :http/1.1
                   :request-uri path :url-scheme "http" :remote-addr "127.0.0.1"
                   :headers (alist-hash-table `(("authorization" . ,(format nil "Bearer ~a" *management-key*)))
                                              :test 'equal)
                   :content-type "application/json" :content-length (length octets)
                   :raw-body (make-in-memory-input-stream octets))))
    (destructuring-bind (status headers body) (funcall (app) env)
      (declare (ignore headers))
      (values status (handler-case (parse-json (apply #'concatenate 'string (if (listp body) body (list body)))) (json-parse-error () nil))))))

(deftest wrongly-typed-input-is-refused
  (multiple-value-bind (status json)
      (admin :post "/admin/api/website/lists/blog" :body (jobject "data" (jobject "title" "Yes?") "publish" "yes"))
    (ok (= status 400) "publish is true or false, not a word")
    (ok (string= (jget json "error" "code") "bad_request")))
  (ok (zerop (jget (nth-value 1 (admin :get "/admin/api/website/lists/blog")) "totalCount"))
      "and nothing is made")
  (let ((id (jget (nth-value 1 (admin :post "/admin/api/website/lists/blog" :body (jobject "data" (jobject "title" "Draft"))))
                  "id")))
    (multiple-value-bind (status json)
        (admin :post (format nil "/admin/api/website/lists/blog/~a/publish" id) :body (jobject "data" 5))
      (ok (= status 400) "a data that is not an object publishes nothing")
      (ok (string= (jget json "error" "code") "bad_request")))
    (ok (string= (jget (nth-value 1 (admin :get (format nil "/admin/api/website/lists/blog/~a" id))) "status") "draft"))
    (ok (= 200 (admin :post (format nil "/admin/api/website/lists/blog/~a/publish" id) :body (jobject "data" json-null)))
        "while a null one is none, and publishes the draft"))
  (multiple-value-bind (status json)
      (admin-octets :post "/admin/api/website/lists/blog" (coerce #(123 34 100 34 58 34 255 34 125) '(vector (unsigned-byte 8))))
    (ok (= status 400) "a body that is not UTF-8 is no JSON")
    (ok (string= (jget json "error" "code") "bad_json"))))

(deftest a-list-query-value-that-is-not-text-is-none
  (multiple-value-bind (status json) (admin :get "/admin/api/website/lists/blog" :body (jobject "orders" 1 "q" 1))
    (ok (= status 200) "a value that is not text, here from a JSON body, is no part of the query")
    (ok (jget json "contents"))))

(defun with-pages (thunk)
  (replace-schema "website"
                  (make-schema :webhooks (schema-webhooks (test-schema))
                               :models (append (schema-models (test-schema))
                                               (list (make-model "page" :list (list (make-field :title :text)
                                                                                    (make-field :slug :slug)))))))
  (unwind-protect (funcall thunk)
    (exec "DELETE FROM contents")
    (replace-schema "website" (test-schema))))

(deftest a-list-content-is-reached-by-its-slug
  (with-pages
    (lambda ()
      (let ((id (jget (nth-value 1 (admin :post "/admin/api/website/lists/page"
                                          :body (jobject "data" (jobject "title" "Live" "slug" "live") "publish" t)))
                      "id")))
        (testing "the admin API reads, saves and deletes it at its slug"
          (multiple-value-bind (status json) (admin :get "/admin/api/website/lists/page/slugs/live")
            (ok (= status 200))
            (ok (string= (jget json "id") id)))
          (multiple-value-bind (status json) (admin :patch "/admin/api/website/lists/page/slugs/live"
                                                    :body (jobject "data" (jobject "slug" "live-next")))
            (ok (= status 200))
            (ok (string= (jget json "draft" "slug") "live-next")))
          (ok (string= (jget (nth-value 1 (admin :get "/admin/api/website/lists/page/slugs/live-next")) "id") id)
              "by its draft's slug too")
          (ok (= (admin :get "/admin/api/website/lists/page/slugs/nope") 404)))
        (testing "the delivery API reads it at its published slug"
          (multiple-value-bind (status json) (delivery "/api/v1/website/lists/page/slugs/live")
            (ok (= status 200))
            (ok (string= (jget json "id") id))
            (ok (string= (jget json "slug") "live")))
          (ok (= (delivery "/api/v1/website/lists/page/slugs/live-next") 404) "not at its draft's")
          (let ((key (jget (nth-value 1 (admin :post (format nil "/admin/api/website/lists/page/~a/draft-key" id))) "draftKey")))
            (multiple-value-bind (status json) (delivery "/api/v1/website/lists/page/slugs/live-next"
                                                         :query (format nil "draftKey=~a" key))
              (ok (= status 200) "unless the draft key opens it")
              (ok (string= (jget json "slug") "live-next")))))
        (testing "a slug that reads like a content's action is a slug still"
          (ok (= (nth-value 0 (admin :post "/admin/api/website/lists/page"
                                     :body (jobject "data" (jobject "title" "P" "slug" "publish") "publish" t)))
                 201))
          (ok (= (admin :get "/admin/api/website/lists/page/slugs/publish") 200))
          (ok (= (delivery "/api/v1/website/lists/page/slugs/publish") 200)))
        (testing "a model without a slug field has none to find"
          (ok (= (admin :get "/admin/api/website/lists/blog/slugs/live") 404))
          (ok (= (delivery "/api/v1/website/lists/blog/slugs/live") 404)))
        (testing "nor does an object model have the address"
          (ok (= (admin :get "/admin/api/website/lists/about/slugs/live") 404)))
        (multiple-value-bind (status json) (admin :delete "/admin/api/website/lists/page/slugs/live-next")
          (ok (= status 200))
          (ok (eq (jget json "deleted") t)))
        (ok (= (admin :get (format nil "/admin/api/website/lists/page/~a" id)) 404) "it is gone")))))
