(defpackage #:koya-spec/server/web/admin-api/media
  (:use #:cl #:rove)
  (:import-from #:koya-spec/server/web/api-support #:request #:admin #:admin-upload #:delivery #:setup-api #:reset-api)
  (:import-from #:koya-server/infra/db/connection #:disconnect-db)
  (:import-from #:koya-core/json #:jobject #:jget)
  (:import-from #:babel #:string-to-octets)
  (:import-from #:koya-spec/server/usecases/media #:png-bytes)
  (:import-from #:koya-spec/server/web/api-support #:test-schema)
  (:import-from #:koya-server/usecases/schema #:replace-schema)
  (:import-from #:koya-core/schema #:make-field #:make-model #:make-schema #:make-custom-field))
(in-package #:koya-spec/server/web/admin-api/media)

(setup (setup-api))

(teardown (disconnect-db))

(defhook :before (reset-api))

(deftest media-api
  (let ((id nil))
    (testing "upload"
      (multiple-value-bind (status json)
          (admin-upload "/admin/api/website/media" (list (list "alt" "Cover art")
                                                         (list "file" "cover.png" "image/png" (png-bytes 3 2))))
        (ok (= status 201))
        (let ((media (aref (jget json "media") 0)))
          (setf id (jget media "id"))
          (ok (string= (jget media "filename") "cover.png"))
          (ok (string= (jget media "mime") "image/png"))
          (ok (= (jget media "width") 3))
          (ok (string= (jget media "alt") "Cover art"))
          (ok (search (format nil "/media/website/~a.png" id) (jget media "url"))))))
    (testing "the file is served"
      (multiple-value-bind (status headers path) (request :get (format nil "/media/website/~a.png" id))
        (ok (= status 200))
        (ok (string= (getf headers :content-type) "image/png"))
        (ok (search "immutable" (getf headers :cache-control)))
        (ok (pathnamep path))
        (ok (= (with-open-file (in path :element-type '(unsigned-byte 8)) (file-length in))
               (length (png-bytes 3 2)))))
      (multiple-value-bind (status) (request :get "/media/website/../../etc/passwd")
        (ok (= status 404) "only space/id.ext shapes are served")))
    (testing "list, search, detail, alt"
      (multiple-value-bind (status json) (admin :get "/admin/api/website/media")
        (ok (= status 200))
        (ok (= (jget json "totalCount") 1)))
      (multiple-value-bind (status json) (admin :get "/admin/api/website/media" :query "q=nomatch")
        (ok (= status 200))
        (ok (= (jget json "totalCount") 0)))
      (multiple-value-bind (status json) (admin :get (format nil "/admin/api/website/media/~a" id))
        (ok (= status 200))
        (ok (= (jget json "references") 0)))
      (multiple-value-bind (status json) (admin :patch (format nil "/admin/api/website/media/~a" id) :body (jobject "alt" "New alt"))
        (ok (= status 200))
        (ok (string= (jget json "alt") "New alt"))))
    (testing "a :media field expands in the delivery API"
      (multiple-value-bind (status json)
          (admin :post "/admin/api/website/lists/blog"
                 :body (jobject "data" (jobject "title" "With cover" "cover" id) "publish" t))
        (ok (= status 201))
        (let ((post-id (jget json "id")))
          (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/lists/blog/~a" post-id))
            (ok (= status 200))
            (ok (string= (jget json "cover" "id") id))
            (ok (string= (jget json "cover" "alt") "New alt"))
            (ok (search "/media/website/" (jget json "cover" "url"))))
          (multiple-value-bind (status json) (admin :get (format nil "/admin/api/website/media/~a" id))
            (ok (= status 200))
            (ok (= (jget json "references") 1) "the content is counted as a reference"))
          (multiple-value-bind (status json) (admin :get (format nil "/admin/api/website/lists/blog/~a" post-id))
            (ok (= status 200))
            (ok (string= (jget json "published" "cover") id) "the admin API keeps the id"))
          (testing "a file in use cannot be deleted"
            (multiple-value-bind (status json) (admin :delete (format nil "/admin/api/website/media/~a" id))
              (ok (= status 409))
              (ok (string= (jget json "error" "code") "in_use"))
              (ok (search "1 content" (jget json "error" "message"))))
            (multiple-value-bind (status) (request :get (format nil "/media/website/~a.png" id))
              (ok (= status 200) "file still there")))
          (testing "once nothing uses it, it goes"
            (admin :delete (format nil "/admin/api/website/lists/blog/~a" post-id))
            (multiple-value-bind (status json) (admin :delete (format nil "/admin/api/website/media/~a" id))
              (ok (= status 200))
              (ok (eq (jget json "deleted") t)))
            (multiple-value-bind (status) (request :get (format nil "/media/website/~a.png" id))
              (ok (= status 404) "file gone"))))))
    (testing "richtext media paths are absolute in the delivery API"
      (multiple-value-bind (status json)
          (admin :post "/admin/api/website/lists/blog"
                 :body (jobject "data" (jobject "title" "Inline image"
                                                "body" "<p><img src=\"/media/website/01ARZ3NDEKTSV4RRFFQ69G5FAV.png\"></p>")
                                "publish" t))
        (ok (= status 201))
        (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/lists/blog/~a" (jget json "id")))
          (ok (= status 200))
          (ok (search "src=\"http://localhost:3000/media/website/01ARZ3NDEKTSV4RRFFQ69G5FAV.png\"" (jget json "body"))))
        (multiple-value-bind (status json) (admin :get (format nil "/admin/api/website/lists/blog/~a" (jget json "id")))
          (ok (= status 200))
          (ok (search "src=\"/media/website/" (jget json "published" "body")) "stored and admin-visible as a path"))))
    (testing "rejections"
      (multiple-value-bind (status json)
          (admin-upload "/admin/api/website/media" (list (list "file" "notes.txt" "text/plain" (string-to-octets "hello"))))
        (ok (= status 422))
        (ok (string= (jget json "error" "code") "unsupported_type")))
      (multiple-value-bind (status json) (admin-upload "/admin/api/website/media" (list (list "alt" "no file")))
        (ok (= status 400))
        (ok (string= (jget json "error" "code") "bad_request")))
      (multiple-value-bind (status) (admin-upload "/admin/api/other/media" (list (list "file" "a.png" "image/png" (png-bytes))))
        (ok (= status 403) "a key of another space is refused before the route is reached")))))

(deftest media-inside-a-custom-field
  (replace-schema "website"
                  (make-schema :custom-fields (list (make-custom-field "card" (list (make-field :photo :media)
                                                                                    (make-field :note :richtext))))
                               :models (list (make-model "blog" :list (list (make-field :title :text)
                                                                            (make-field :card :custom :custom-field "card"))))))
  (unwind-protect
       (let* ((id (jget (aref (jget (nth-value 1 (admin-upload "/admin/api/website/media"
                                                               (list (list "file" "inside.png" "image/png" (png-bytes 2 2)))))
                                    "media")
                              0)
                        "id"))
              (post (jget (nth-value 1 (admin :post "/admin/api/website/lists/blog"
                                              :body (jobject "data" (jobject "title" "Inside"
                                                                             "card" (jobject "photo" id
                                                                                             "note" "<p><img src=\"/media/website/x.png\"></p>"))
                                                             "publish" t)))
                          "id")))
         (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/lists/blog/~a" post))
           (ok (= status 200))
           (ok (search "/media/website/" (jget json "card" "photo" "url")) "media inside is expanded")
           (ok (search "src=\"http://localhost:3000/media/website/x.png\"" (jget json "card" "note"))
               "and rich text inside has its media paths made absolute"))
         (ok (= (jget (nth-value 1 (admin :get (format nil "/admin/api/website/media/~a" id))) "references") 1)
             "it counts as a use")
         (ok (= 409 (admin :delete (format nil "/admin/api/website/media/~a" id))) "so it is not deleted")
         (admin :delete (format nil "/admin/api/website/lists/blog/~a" post))
         (admin :delete (format nil "/admin/api/website/media/~a" id)))
    (replace-schema "website" (test-schema))))
