(defpackage #:koya-spec/server/web/pages/editor
  (:use #:cl #:rove)
  (:import-from #:koya-server/usecases/schema #:replace-schema #:resolve-model)
  (:import-from #:koya-server/web/pages/s/<space>/m/<model>/<id>/history #:browse-history)
  (:import-from #:koya-server/web/lib/binds #:on-click #:on-submit)
  (:import-from #:koya-spec/server/web/pages/support
                #:replaced-url #:bound #:call-action #:edit #:moved-to #:blog-model #:request #:location #:setup-pages
                #:log-in #:asked-first)
  (:import-from #:koya-server/web/ui/content/editor #:editor-action #:repeater-row)
  (:import-from #:koya-server/infra/db/connection #:disconnect-db #:exec)
  (:import-from #:koya-server/usecases/ports/contents
                #:list-contents #:list-revisions #:count-revisions #:get-content #:count-contents
                #:update-content #:delete-content)
  (:import-from #:koya-server/domain/content
                #:content-status #:content-published #:content-draft #:content-id #:slugify #:unpublished)
  (:import-from #:koya-server/domain/media #:media-id)
  (:import-from #:koya-server/domain/query #:parse-query)
  (:import-from #:koya-server/domain/revision #:revision-id #:revision-event #:revision-by)
  (:import-from #:koya-core/schema
                #:make-field #:make-model #:make-schema #:field-name #:model-fields #:make-custom-field)
  (:import-from #:koya-core/json #:jget #:jobject)
  (:import-from #:koya-server/usecases/ports/media #:insert-media #:delete-media)
  (:import-from #:koya-server/usecases/contents #:create #:update-draft)
  (:import-from #:koya-server/domain/content #:content-updated-at))
(in-package #:koya-spec/server/web/pages/editor)

(setup (setup-pages) (log-in))

(teardown (disconnect-db))

(deftest editor-flow
  (exec "DELETE FROM contents")
  (testing "validation errors are drawn where they are shown, and the form is left as it is"
    (multiple-value-bind (status body) (edit "/s/website/m/blog/new" :form '(("action" . "save") ("f-body" . "x")))
      (ok (= status 422))
      (ok (search "<div id=\"editor-errors\"" body) "the summary")
      (ok (cl-ppcre:scan "<p id=\"f-title-error\"[^>]*>is required</p>" body) "the field's own line")
      (ok (cl-ppcre:scan "<p id=\"f-body-error\"[^>]*hidden[^>]*></p>" body) "and a field without an error has its line emptied")
      (ng (search "id=\"editor\"" body))
      (ng (search "editor-form" body) "so what was typed, the focus and the rich text stay")
      (ng (search "NIL" body))))
  (testing "an emptied editor, which koya.js sends as nothing, is no value"
    (multiple-value-bind (status body)
        (edit "/s/website/m/blog/new" :form '(("action" . "save") ("f-title" . "Blank body") ("f-body" . "")))
      (ok (= status 200))
      (ok (search "koya.go(this.dataset.go)" body) "the page of the new content is reached on purpose")
      (let* ((loc (moved-to body)) (id (subseq loc (1+ (position #\/ loc :from-end t)))))
        (ok (null (jget (content-draft (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))) "body")))
        (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "delete"))))))
  (let ((id nil))
    (testing "save a draft"
      (multiple-value-bind (status body)
          (edit "/s/website/m/blog/new"
                    :form '(("action" . "save") ("f-title" . "Hello World") ("f-body" . "# Hi")
                           ("f-featured" . "on") ("f-category" . "tech") ("f-labels" . "a,b")
                           ("f-count" . "2.5") ("f-when" . "2026-09-20T10:00")
                           ("f-related" . "x1,x2")))
        (ok (= status 200))
        (let* ((loc (moved-to body))
               (path (subseq loc 0 (position #\? loc))))
          (setf id (subseq path (1+ (position #\/ path :from-end t))))
          (ok (= (length id) 26))))
      (let ((content (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
        (ok (string= (content-status content) "draft"))
        (let ((draft (content-draft content)))
          (ok (string= (jget draft "slug") "hello-world") "slug generated from title")
          (ok (eq (jget draft "featured") t))
          (ok (equalp (jget draft "labels") #("a" "b")))
          (ok (= (jget draft "count") 2.5))
          (ok (string= (jget draft "when") "2026-09-20T10:00:00.000Z") "datetime-local value stored as UTC in the canonical form")
          (ok (equalp (jget draft "related") #("x1" "x2")) "a list is sent comma-separated"))))
    (testing "editor shows the draft and the toast exactly once"
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ok (search "value=\"Hello World\"" body))
        (ok (search "value=\"hello-world\"" body))
        (ok (search "checked" body))
        (ok (search "value=\"2026-09-20T10:00\"" body))
        (ok (search "value=\"2.5\"" body) "floats render without an exponent marker")
        (ok (search "<select id=\"f-related\" name=\"f-related\" multiple" body)
            "reference is a multiple select")
        (ok (search "value=\"x1\" selected" body) "selected ids not in the target model are kept")
        (ok (search (format nil "value=\"~a\"" id) body) "existing contents are offered")
        (ok (search "Draft saved" body))
        (ng (search "NIL" body) "no stray NILs in the page"))
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ng (search "Draft saved" body) "toast is gone on the next request")))
    (testing "text with a literal entity survives the editor"
      (multiple-value-bind (status body)
          (edit "/s/website/m/blog/new"
                    :form '(("action" . "save") ("f-title" . "AT&amp;T <b>") ("f-body" . "<p>x</p>")))
        (ok (= status 200))
        (let ((path (subseq (moved-to body) 0 (position #\? (moved-to body)))))
          (multiple-value-bind (status body) (request :get path)
            (ok (= status 200))
            (ok (search "value=\"AT&amp;amp;T <b>\"" body) "the attribute encodes & so the browser shows AT&amp;T"))
          (edit path :form '(("action" . "delete"))))))
    (testing "list shows field previews and status, newest first"
      (edit "/s/website/m/blog/new"
                :form `(("action" . "save") ("f-title" . "Second post") ("f-body" . "<p>Rich <b>text</b> &amp; more</p>")
                       ("f-related" . ,id) ("f-related" . "x2")))
      (multiple-value-bind (status body) (request :get "/s/website/m/blog")
        (ok (= status 200))
        (ok (search "Hello World" body))
        (ok (< (search "Second post" body) (search "Hello World" body)) "newest created first")
        (ok (search "Rich text &amp; more" body) "rich text is previewed as plain text")
        (ok (not (search "<b>text</b>" body)))
        (ok (search "2026-09-20 10:00 UTC" body) "datetime preview")
        (ok (search ">Yes<" body) "boolean preview")
        (ok (search ">a, b<" body) "multi select preview")
        (ok (search ">2.5<" body) "number preview")
        (ok (search ">draft<" body))
        (ok (search "class=\"after:absolute after:inset-0\" aria-label=\"Open " body) "a row's link covers the row")
        (ok (search "Hello World, x2" body) "a reference previews as the target's label, unknown ids stay ids")
        (ok (not (search ">Hello World</a>" body)) "the title is not a link of its own")
        (ok (not (search "Created at" body)))
        (ok (not (search "Updated at" body))))
      (let ((second (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
        (edit (format nil "/s/website/m/blog/~a" (content-id second)) :form '(("action" . "delete")))))
    (testing "discard a draft"
      (let ((origin '(("origin" . "http://localhost:3000"))))
        (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "publish") ("f-title" . "Hello World") ("f-body" . "<p>x</p>")) :headers origin)
        (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
          (ok (= status 200))
          (ok (not (search "Discard draft" body)) "no draft, no button"))
        (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "save") ("f-title" . "Edited") ("f-body" . "<p>x</p>")) :headers origin)
        (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
          (ok (= status 200))
          (ok (search "Discard draft" body))
          (ok (search "value=\"Edited\"" body)))
        (multiple-value-bind (status body) (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "discard")) :headers origin)
          (ok (= status 200))
          (ok (string= (moved-to body) (format nil "/s/website/m/blog/~a" id)))
          (ok (search "id=\"editor\"" body) "the editor is drawn again")
          (ok (search "Draft discarded." body) "with the toast out of band")
          (ok (search "value=\"Hello World\"" body) "and the published data back in it"))
        (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
          (ok (= status 200))
          (ok (search "value=\"Hello World\"" body) "editor shows the published data again")
          (ok (not (search "Discard draft" body))))
        (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "unpublish")) :headers origin)))
    (testing "publish, unpublish, delete"
      (multiple-value-bind (status body)
          (edit (format nil "/s/website/m/blog/~a" id)
                    :form '(("action" . "publish") ("f-title" . "Hello World") ("f-slug" . "hello-world") ("f-body" . "# Hi")))
        (ok (= status 200))
        (ok (search "Published." body) "toast after publish")
        (ok (string= (moved-to body) (format nil "/s/website/m/blog/~a" id)) "the URL loses any query noise"))
      (let ((content (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
        (ok (string= (content-status content) "published"))
        (ok (null (jget (content-published content) "featured")) "unchecked box stored as false"))
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ok (search "Published page" body) "published + public template gives a page link")
        (ng (search "Preview draft" body) "no draft, no preview link"))
      (multiple-value-bind (status) (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "unpublish")))
        (ok (= status 200)))
      (ok (string= (content-status (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))) "draft"))
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ok (search "Preview draft" body) "draft + preview template gives a preview link")
        (ok (search "https://site.test/blog/" body))
        (ng (search "Published page" body)))
      (multiple-value-bind (status body) (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "delete")))
        (ok (= status 200))
        (ok (string= (moved-to body) "/s/website/m/blog")))
      (ok (null (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all)))))
  (testing "object model editor upserts"
    (multiple-value-bind (status body) (edit "/s/website/m/about" :form '(("action" . "publish") ("f-body" . "about")))
      (ok (= status 200))
      (ok (string= (moved-to body) "/s/website/m/about")))
    (multiple-value-bind (status body) (request :get "/s/website/m/about")
      (ok (= status 200))
      (ok (search "about" body)))))

(deftest an-object-is-edited-at-its-model
  (exec "DELETE FROM contents")
  (testing "the model opens its editor, empty before the first save"
    (multiple-value-bind (status body) (request :get "/s/website/m/about")
      (ok (= status 200))
      (ok (search "id=\"editor\"" body))
      (ng (search "Danger zone" body) "and nothing to take off the site yet")))
  (let ((id nil))
    (testing "the first save makes its content and stays at the model"
      (multiple-value-bind (status body) (edit "/s/website/m/about" :form '(("action" . "save") ("f-body" . "first")))
        (ok (= status 200))
        (ok (search "Draft saved." body))
        (ok (string= (moved-to body) "/s/website/m/about")))
      (setf id (content-id (first (list-contents "website" "about" (nth-value 1 (resolve-model "website" "about")) (parse-query nil) :status :all)))))
    (testing "a later save changes that content"
      (edit "/s/website/m/about" :form `(("action" . "save") ("f-body" . "second")
                                         ("updated-at" . ,(content-updated-at (get-content "website" id)))))
      (ok (= 1 (count-contents "website" "about")))
      (ok (string= (jget (content-draft (get-content "website" id)) "body") "second")))
    (testing "its id and new do not reach it"
      (dolist (path (list (format nil "/s/website/m/about/~a" id) "/s/website/m/about/new"))
        (ok (= (request :get path) 404) path)))
    (testing "it has no delete"
      (edit "/s/website/m/about" :form '(("action" . "publish") ("f-body" . "live")))
      (multiple-value-bind (status body) (request :get "/s/website/m/about")
        (ok (= status 200))
        (ok (search "Unpublish" body) "unpublishing is what takes it off the site")
        (ng (search "Delete" body)))
      (ok (<= 400 (edit "/s/website/m/about" :form '(("action" . "delete"))) 499))
      (ok (get-content "website" id) "and the action does not delete it either"))
    (testing "its history restores at the model"
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/about/~a/history" id))
        (ok (= status 200))
        (ok (search "href=\"/s/website/m/about?revision=" body))
        (ok (search "href=\"/s/website/m/about\"" body) "and leads back to it"))
      (multiple-value-bind (status body)
          (request :get "/s/website/m/about"
                   :query (format nil "revision=~a" (revision-id (car (last (list-revisions "website" id))))))
        (ok (= status 200))
        (ok (search "Restoring the version of" body))
        (ok (search "value=\"first\"" body))))))

(deftest richtext-is-stored-as-sent
  (exec "DELETE FROM contents")
  (let* ((html (format nil "<h2 id=\"intro\">Intro</h2><p>a</p>~%<p>b</p>"))
         (id (multiple-value-bind (space model) (resolve-model "website" "blog")
               (content-id (create space model (let ((data (make-hash-table :test 'equal)))
                                                 (setf (gethash "title" data) "Imported"
                                                       (gethash "body" data) html)
                                                 data)
                                   :publish t))))
         (path (format nil "/s/website/m/blog/~a" id)))
    (testing "the editor carries the HTML whole, its line breaks included"
      (let ((body (nth-value 1 (request :get path))))
        (ok (search (format nil "id=\"f-body\" name=\"f-body\" value=\"<h2 id=&quot;intro&quot;>Intro</h2><p>a</p>~%<p>b</p>\"")
                    body)
            "an untouched field is sent back as it is here: hsx keeps an attribute value's line breaks")))
    (testing "an untouched field comes back as it was, less the CRLF of the form"
      (edit path :form `(("action" . "save") ("f-title" . "Renamed")
                                  ("f-body" . ,(format nil "<h2 id=\"intro\">Intro</h2><p>a</p>~c~%<p>b</p>" #\Return))))
      (ok (string= (jget (content-draft (get-content "website" id)) "body") html)))
    (testing "the whitespace around it is kept too"
      (let ((spaced (format nil "~%<p>a</p>~%")))
        (edit path :form `(("action" . "save") ("f-title" . "Renamed") ("f-body" . ,spaced)))
        (ok (string= (jget (content-draft (get-content "website" id)) "body") spaced))))
    (testing "an edited one is stored as the editor wrote it"
      (edit path :form '(("action" . "save") ("f-title" . "Renamed") ("f-body" . "<p>c</p><p>d</p>")))
      (ok (string= (jget (content-draft (get-content "website" id)) "body") "<p>c</p><p>d</p>")))))

(deftest slugify-test
  (ok (string= (slugify "Hello, World!") "hello-world"))
  (ok (string= (slugify "  Common  Lisp 2026 ") "common-lisp-2026"))
  (ok (string= (slugify "日本語") "") "non-ascii yields empty; validation then reports it"))

(defun new-blog (form)
  (multiple-value-bind (status body) (edit "/s/website/m/blog/new" :form form)
    (ok (= status 200))
    (let ((path (subseq (moved-to body) 0 (position #\? (moved-to body)))))
      (subseq path (1+ (position #\/ path :from-end t))))))

(deftest history-and-restore
  (exec "DELETE FROM contents")
  (let* ((kept (new-blog '(("action" . "publish") ("f-title" . "Kept"))))
         (unpublished (new-blog '(("action" . "publish") ("f-title" . "Unpublished later"))))
         (deleted (new-blog '(("action" . "publish") ("f-title" . "Deleted later"))))
         (media (media-id (insert-media "website" :filename "cover.png" :mime "image/png" :size 1)))
         (first `(("f-title" . "First") ("f-slug" . "first") ("f-category" . "news") ("f-count" . "3")
                  ("f-body" . "<p>Rich <b>old</b></p><img src=x onerror=\"alert(1)\">")
                  ("f-cover" . ,media)
                  ("f-related" . ,kept) ("f-related" . ,unpublished) ("f-related" . ,deleted)))
         (id (new-blog (cons '("action" . "save") first)))
         (url (format nil "/s/website/m/blog/~a" id)))
    (edit url  :form (cons '("action" . "publish") first))
    (edit url  :form '(("action" . "save") ("f-title" . "Second") ("f-category" . "tech")))
    (ok (equal (mapcar #'revision-event (list-revisions "website" id)) '("draft" "publish" "draft")))
    (ok (string= (revision-by (first (list-revisions "website" id))) "owner") "the editor writes as the owner")
    (testing "the editor links to the history"
      (multiple-value-bind (status body) (request :get url)
        (ok (= status 200))
        (ok (search (format nil "href=\"~a/history\"" url) body))))
    (testing "every change, each against the one before"
      (multiple-value-bind (status body) (request :get (format nil "~a/history" url))
        (ok (= status 200))
        (ok (search "All changes (3)" body))
        (ok (search "Published (1)" body))
        (ok (search "Draft saved" body))
        (let ((ids (mapcar #'revision-id (list-revisions "website" id))))
          (ok (< (search (format nil "revision=~a\"" (first ids)) body)
                 (search (format nil "revision=~a\"" (car (last ids))) body))
              "newest first"))
        (ok (search "The oldest version in this view." body))
        (ok (search "cover.png" body) "a media id is shown with its file name")
        (ok (search "Kept (" body) "a reference is shown with its label")
        (ok (search "<iframe sandbox=\"allow-same-origin\"" body) "rich text is drawn in a sandbox without scripts")
        (ok (search "<b>old</b>" body) "as the frame's own document")
        (ok (search "<html class=&quot;overflow-hidden&quot;>" body)
            "which never scrolls: the frame is as tall as what it holds")
        (let ((outside (cl-ppcre:regex-replace-all "srcdoc=\"[^\"]*\"" body "")))
          (ng (search "<b>old</b>" outside) "and never as markup of this page")
          (ng (search "onerror" outside)))
        (ng (search "NIL" body))))
    (testing "the published versions alone"
      (multiple-value-bind (status body) (request :get (format nil "~a/history" url) :query "view=published")
        (ok (= status 200))
        (ng (search "Draft saved" body))
        (ok (search "Published" body))))

    (update-content (unpublished (get-content "website" unpublished)))
    (delete-content "website" deleted)
    (delete-media "website" media)
    (replace-schema "website"
                 (make-schema :models (list (make-model "blog" :list
                                                        (remove-if (lambda (f) (member (field-name f) '("count") :test #'string=))
                                                                   (mapcar (lambda (f)
                                                                             (if (string= (field-name f) "category")
                                                                                 (make-field :category :select :options '("tech" "other"))
                                                                                 f))
                                                                           (model-fields (blog-model))))
                                                        :label :title
                                                        :preview-url "https://site.test/blog/{CONTENT_ID}?draft-key={DRAFT_KEY}"
                                                        :public-url "https://site.test/blog/{CONTENT_ID}")
                                            (make-model "about" :object (list (make-field :body :richtext))))))
    (let* ((published (find "publish" (list-revisions "website" id) :key #'revision-event :test #'string=))
           (before (count-revisions "website" id)))
      (testing "a restore fills the editor with what can come back, and says what cannot"
        (multiple-value-bind (status body)
            (request :get url :query (format nil "revision=~a" (revision-id published)))
          (ok (= status 200))
          (ok (search "Restoring the version of" body))
          (ok (search "value=\"First\"" body) "the old title is in the form")
          (ok (search "value=\"first\"" body) "and its slug, which nobody else has taken")
          (ng (search "<strong>count</strong>" body) "a removed field took its old values with it")
          (ok (search "<strong>category</strong> keeps the current value" body))
          (ok (search "value=\"tech\" selected" body) "the option that is gone leaves the current one")
          (ok (search "<strong>related</strong> lost 2 references" body))
          (ok (search (format nil "value=\"~a\" selected" kept) body) "a published reference comes back")
          (ng (search (format nil "value=\"~a\" selected" unpublished) body) "an unpublished one does not")
          (ng (search deleted body) "nor a deleted one")
          (ok (search "<strong>cover</strong> lost 1 media" body))
          (ng (search media body) "the media that is gone is not in the form")
          (ng (search "NIL" body))))
      (testing "and writes nothing until it is saved"
        (ok (= (count-revisions "website" id) before))
        (ok (string= (jget (content-draft (get-content "website" id)) "title") "Second")))
      (testing "saving it is an ordinary draft save"
        (edit url  :form `(("action" . "save") ("f-title" . "First") ("f-slug" . "first")
                                   ("f-category" . "tech") ("f-related" . ,kept)))
        (ok (= (count-revisions "website" id) (1+ before)))
        (ok (string= (jget (content-draft (get-content "website" id)) "title") "First"))
        (ok (string= (content-status (get-content "website" id)) "published+draft") "what is live is untouched")))
    (testing "a revision this content does not have"
      (multiple-value-bind (status body) (request :get url :query "revision=999999")
        (ok (= status 200))
        (ok (search "does not exist for this content" body))
        (ng (search "Restoring the version of" body))))
    (testing "a deleted content has no history left"
      (edit url  :form '(("action" . "delete")))
      (ok (= (count-revisions "website" id) 0))
      (ok (= (request :get (format nil "~a/history" url)) 404))))
  (replace-schema "website"
               (make-schema :models (list (blog-model)
                                          (make-model "about" :object (list (make-field :body :richtext)))))))

(deftest a-content-is-named-by-its-model-label
  (exec "DELETE FROM contents")
  (let* ((target (new-blog '(("action" . "publish") ("f-title" . "Named target"))))
         (pointer (new-blog `(("action" . "save") ("f-title" . "Pointer") ("f-related" . ,target)))))
    (flet ((list-body () (nth-value 1 (request :get "/s/website/m/blog"))))
      (ok (search "Named target" (list-body)) "the declared field names the reference")
      (ok (search "title=\"Pointer\">Pointer</span>"
                  (nth-value 1 (request :get (format nil "/s/website/m/blog/~a" pointer))))
          "and the editor's crumb")
      (ok (search ">Pointer</a>"
                  (nth-value 1 (request :get (format nil "/s/website/m/blog/~a/history" pointer))))
          "and the history's")
      (replace-schema "website"
                   (make-schema :models (list (make-model "blog" :list (model-fields (blog-model)))
                                              (make-model "about" :object (list (make-field :body :richtext))))))
      (unwind-protect
           (let ((body (list-body)))
             (ok (search (format nil ">~a<" target) body)
                 "without a :label the reference is its id")
             (multiple-value-bind (status editor) (request :get (format nil "/s/website/m/blog/~a" pointer))
               (ok (= status 200))
               (ok (search (format nil "value=\"~a\" selected nm-bind=\"{ selected: () => _has(this.value) }\">~a<" target target) editor)
                   "and so is the option that picks it")
               (ok (search (format nil "title=\"~a\">~a</span>" pointer pointer) editor)
                   "and the crumb")))
        (replace-schema "website"
                     (make-schema :models (list (blog-model)
                                                (make-model "about" :object (list (make-field :body :richtext))))))))))

(deftest a-referenced-content-is-not-deleted-from-the-editor
  (exec "DELETE FROM contents")
  (multiple-value-bind (space model) (resolve-model "website" "blog")
    (let* ((target (content-id (create space model (jobject "title" "Target") :publish t)))
           (path (format nil "/s/website/m/blog/~a" target)))
      (create space model (jobject "title" "Refers" "related" (vector target)) :publish t)
      (multiple-value-bind (status body) (edit path :form '(("action" . "delete")))
        (ok (= status 409))
        (ng (search "id=\"editor\"" body) "the editor stays as it is")
        (ok (null (moved-to body)) "and on this content, not the list")
        (ok (search "referenced by 1 other content" body) "the toast says why")
        (ok (get-content "website" target) "it is still there")))))

(deftest the-editor-asks-before-it-acts
  (exec "DELETE FROM contents")
  (flet ((post (id op) (editor-action :space "website" :model "blog" :id id :op op)))
    (testing "a new content is published from a dialog"
      (let ((body (nth-value 1 (request :get "/s/website/m/blog/new"))))
        (ok (asked-first body "confirm-publish" (post "new" "publish")))
        (ng (search "confirm(" body) "not the browser's own confirm")))
    (let ((id (new-blog '(("action" . "publish") ("f-title" . "Asked")))))
      (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "save") ("f-title" . "Asked again")))
      (let ((body (nth-value 1 (request :get (format nil "/s/website/m/blog/~a" id)))))
        (dolist (op '("publish" "unpublish" "delete" "discard"))
          (testing (format nil "~a opens a dialog, and the dialog does it" op)
            (ok (asked-first body (format nil "confirm-~a" op) (post id op)))))
        (testing "saving a draft is not asked"
          (ok (search (bound (on-click (post id "save") :data "koya.form($refs.form)" :binds "disabled: () => _unchanged()"))
                      body)
              "its button posts the draft itself")
          (ng (search "confirm-save" body)))
        (ng (search "confirm(" body))))))

(deftest history-is-read-in-place
  (exec "DELETE FROM contents")
  (let* ((id (new-blog '(("action" . "publish") ("f-title" . "Once"))))
         (path (format nil "/s/website/m/blog/~a/history" id)))
    (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "save") ("f-title" . "Twice")))
    (testing "the tabs call the action"
      (ok (search (subseq (browse-history) 0 (position #\? (browse-history))) (nth-value 1 (request :get path)))))
    (testing "a tab draws #revisions and puts the view in the URL"
      (multiple-value-bind (status body)
          (call-action :get (browse-history :space "website" :model "blog" :id id :view "published" :page 1))
        (ok (= status 200))
        (ok (search "id=\"revisions\"" body))
        (ng (search "Draft saved" body) "the published versions alone")
        (ok (string= (replaced-url body) (format nil "~a?view=published" path)))))
    (ok (= 404 (call-action :get (browse-history :space "website" :model "blog" :id "nope"))))))

(deftest a-draft-that-changes-nothing-is-none
  (exec "DELETE FROM contents")
  (let* ((id (new-blog '(("action" . "publish") ("f-title" . "Live") ("f-slug" . "live"))))
         (path (format nil "/s/website/m/blog/~a" id))
         (form '(("f-title" . "Live") ("f-slug" . "live"))))
    (testing "the editor holds what the form was drawn with, and Save draft waits for a change"
      (let ((body (nth-value 1 (request :get path))))
        (ok (search "<div id=\"editor\" nm-data=\"...koya.editor(this, false)\">" body)
            "what is shown is what is stored")
        (ok (search "oninput: () => _track(), onchange: () => _track()" body)
            "the form tells it of every change")
        (ok (search "disabled: () => _unchanged()" body))))
    (testing "saving what is published already writes nothing"
      (let ((before (count-revisions "website" id)))
        (multiple-value-bind (status body) (edit path :form (cons '("action" . "save") form))
          (ok (= status 200))
          (ok (search "Nothing to save." body)))
        (ok (= (count-revisions "website" id) before) "no revision")
        (ok (string= (content-status (get-content "website" id)) "published") "and no draft")))
    (testing "a draft taken back to the published data is dropped, and the history says so"
      (edit path :form '(("action" . "save") ("f-title" . "Changed") ("f-slug" . "live")))
      (ok (string= (content-status (get-content "website" id)) "published+draft"))
      (multiple-value-bind (status body) (edit path :form (cons '("action" . "save") form))
        (ok (= status 200))
        (ok (search "Back to the published version" body)))
      (ok (string= (content-status (get-content "website" id)) "published") "the draft is gone")
      (ok (string= (revision-event (first (list-revisions "website" id))) "discard")
          "and it went as a discard, which has something to show"))
    (testing "a restore is marked unsaved"
      (let ((revision (revision-id (car (last (list-revisions "website" id))))))
        (ok (search "koya.editor(this, true)" (nth-value 1 (request :get path :query (format nil "revision=~a" revision)))))))))

(deftest an-unknown-editor-action-is-refused
  (exec "DELETE FROM contents")
  (multiple-value-bind (space model) (resolve-model "website" "blog")
    (let* ((id (content-id (create space model (jobject "title" "Kept"))))
           (path (format nil "/s/website/m/blog/~a" id)))
      (ok (= 404 (edit path :form '(("action" . "foo") ("title" . "Changed"))))
          "an op the editor does not know answers 404")
      (ok (string= (jget (content-draft (get-content "website" id)) "title") "Kept") "and saves nothing")
      (ok (= 1 (count-revisions "website" id)) "nor records anything")
      (ok (= 404 (edit "/s/website/m/blog/new" :form '(("action" . "foo") ("title" . "Made"))))
          "on the new-content form too")
      (ok (= 1 (count-contents "website" "blog")) "which creates nothing"))))

(deftest a-many-reference-is-chips-the-server-draws
  (exec "DELETE FROM contents")
  (multiple-value-bind (space model) (resolve-model "website" "blog")
    (let* ((chosen (content-id (create space model (jobject "title" "Chosen") :publish t)))
           (other (content-id (create space model (jobject "title" "Other") :publish t)))
           (id (content-id (create space model (jobject "title" "Refers" "related" (vector chosen)) :publish t)))
           (body (nth-value 1 (request :get (format nil "/s/website/m/blog/~a" id)))))
      (ok (search "nm-data=\"...koya.references(this)\"" body) "the field holds what is chosen")
      (ok (search "<select id=\"f-related\" name=\"f-related\" multiple hidden" body)
          "the select that is sent stays out of sight")
      (ok (search (format nil "<option value=\"~a\" selected nm-bind=\"{ selected: () => _has(this.value) }\"" chosen) body)
          "and follows the chips")
      (ok (search (format nil "data-id=\"~a\" nm-bind=\"{ hidden: () => !_has(this.dataset.id) }\"" chosen) body)
          "a chip for what is chosen")
      (ok (search (format nil "data-id=\"~a\" hidden nm-bind=\"{ hidden: () => !_has(this.dataset.id) }\"" other) body)
          "and one waiting for each of the rest")
      (ok (search (format nil "<option value=\"~a\" hidden disabled nm-bind=" chosen) body)
          "what is chosen is not offered again")
      (ok (search (format nil "<option value=\"~a\" nm-bind=\"{ hidden: () => _has(this.value), disabled: () => _has(this.value) }\"" other) body)
          "the rest are"))))

(deftest a-save-over-a-change-made-elsewhere-is-refused
  (exec "DELETE FROM contents")
  (let* ((model (nth-value 1 (resolve-model "website" "blog")))
         (id (content-id (create "website" model (jobject "title" "Opened" "slug" "opened")
                                 :updated-at "2024-01-01T00:00:00.000Z")))
         (path (format nil "/s/website/m/blog/~a" id)))
    (ok (search "name=\"updated-at\" value=\"2024-01-01T00:00:00.000Z\""
                (nth-value 1 (request :get path)))
        "the form carries when the content was last written, as it was opened")
    (update-draft "website" model id (jobject "title" "Changed elsewhere"))
    (dolist (op '("save" "publish"))
      (multiple-value-bind (status body)
          (edit path :form `(("action" . ,op) ("f-title" . "Typed here") ("f-slug" . "opened")
                             ("updated-at" . "2024-01-01T00:00:00.000Z")))
        (ok (= status 409) (format nil "~a is refused" op))
        (ok (search "changed elsewhere" body) "and says why")
        (ok (search (format nil "href=\"~a\"" path) body) "with a way to see the change")
        (ng (search "editor-form" body) "while the form, with what was typed, is left as it is")))
    (ok (string= (jget (content-draft (get-content "website" id)) "title") "Changed elsewhere")
        "and the change made elsewhere stays")
    (multiple-value-bind (status)
        (edit path :form `(("action" . "save") ("f-title" . "Typed here") ("f-slug" . "opened")
                           ("updated-at" . ,(content-updated-at (get-content "website" id)))))
      (ok (= status 200) "once the editor has seen it, it saves"))))

(deftest discarding-a-draft-made-elsewhere-is-refused
  (exec "DELETE FROM contents")
  (let* ((model (nth-value 1 (resolve-model "website" "blog")))
         (id (content-id (create "website" model (jobject "title" "Live" "slug" "live") :publish t
                                 :updated-at "2024-01-01T00:00:00.000Z")))
         (path (format nil "/s/website/m/blog/~a" id)))
    (update-draft "website" model id (jobject "title" "Drafted elsewhere"))
    (multiple-value-bind (status body)
        (edit path :form '(("action" . "discard") ("updated-at" . "2024-01-01T00:00:00.000Z")))
      (ok (= status 409) "a draft the editor never saw is not thrown away from it")
      (ok (search "changed elsewhere" body)))
    (ok (string= (jget (content-draft (get-content "website" id)) "title") "Drafted elsewhere"))
    (multiple-value-bind (status)
        (edit path :form `(("action" . "discard") ("updated-at" . ,(content-updated-at (get-content "website" id)))))
      (ok (= status 200) "while one it has seen is"))))

(deftest a-field-tells-the-editor-what-it-expects
  (multiple-value-bind (status body) (request :get "/s/website/m/blog/new")
    (ok (= status 200))
    (let ((label (search "<label for=\"f-cover\"" body))
          (help (search "1200x630, shown when the post is shared" body))
          (control (search "id=\"f-cover\"" body)))
      (ok (and label help control (< label help control)) "under its label, above its control"))
    (ok (= (length (cl-ppcre:all-matches-as-strings "id=\"f-[a-zA-Z]+-help\"" body)) 1) "and a field without one draws nothing for it")))

(deftest the-editor-lists-what-refers-to-a-content
  (exec "DELETE FROM contents")
  (multiple-value-bind (space model) (resolve-model "website" "blog")
    (let* ((target (content-id (create space model (jobject "title" "Target") :publish t)))
           (refers (content-id (create space model (jobject "title" "Refers" "related" (vector target))))))
      (let ((body (nth-value 1 (request :get (format nil "/s/website/m/blog/~a" target)))))
        (ok (search "Referenced by 1 content" body))
        (ok (cl-ppcre:scan "<details class=\"[^\"]*\"><summary" body) "closed until it is opened")
        (ok (< (search "Danger zone" body) (search "Referenced by" body)) "under the danger zone, apart from it")
        (ok (search (format nil "href=\"/s/website/m/blog/~a\"" refers) body) "each one is a link to its editor")
        (ok (search ">Refers<" body) "named by its label"))
      (ng (search "Referenced by" (nth-value 1 (request :get (format nil "/s/website/m/blog/~a" refers))))
          "and a content nothing refers to says nothing about it"))))

(defun with-card ()
  (make-schema :custom-fields (list (make-custom-field "card" (list (make-field :heading :text :required t :max-length 5)
                                                                    (make-field :shown :boolean)
                                                                    (make-field :note :richtext :help "Shown under the heading")
                                                                    (make-field :link :reference :model "blog")
                                                                    (make-field :pinned :boolean :default t))))
               :models (list (blog-model)
                             (make-model "about" :object (list (make-field :body :richtext)))
                             (make-model "page" :list (list (make-field :title :text)
                                                            (make-field :card :custom :custom-field "card" :help "The card")))
                             (make-model "badge" :list (list (make-field :card :custom :custom-field "card" :required t))))))

(deftest a-custom-field-is-edited-as-its-fields
  (exec "DELETE FROM contents")
  (replace-schema "website" (with-card))
  (unwind-protect
       (progn
         (multiple-value-bind (status body) (request :get "/s/website/m/page/new")
           (ok (= status 200))
           (ok (cl-ppcre:scan "<div id=\"f-card-label\" class=\"label\">card<span[^>]*>custom</span><span[^>]*>The card</span></div>" body)
               "a heading like any field's, with its help beside it")
           (ok (search "<fieldset id=\"f-card\" aria-labelledby=\"f-card-label\"" body) "over a fieldset it names")
           (ok (search "The card" body) "with its help")
           (ok (search "id=\"f-card.heading\" name=\"f-card.heading\"" body) "and an input for each field inside")
           (ok (search "name=\"f-card.shown\"" body))
           (ok (search "data-quill-for=\"f-card.note\"" body) "rich text inside has its own editor")
           (ok (search "<select id=\"f-card.link\" name=\"f-card.link\"" body) "and a reference inside is picked under its path")
           (ok (search "name=\"f-card.pinned\" checked" body) "a boolean inside starts as its default says")
           (ok (search "Add card" body) "a custom field that is not required starts absent, to be added")
           (ok (search "<input type=\"hidden\" name=\"f-card\" value=\"on\" disabled" body)
               "so the form does not say it is there")
           (ok (cl-ppcre:scan "<fieldset id=\"f-card\"[^>]* hidden disabled" body) "and its fields are not sent")
           (ok (search "Shown under the heading" body)))
         (let ((body (nth-value 1 (request :get "/s/website/m/badge/new"))))
           (ok (cl-ppcre:scan "<fieldset id=\"f-card\" aria-labelledby=\"f-card-label\" class=\"[^\"]*\" nm-bind" body)
               "a required custom field starts there")
           (ng (search "Add card" body) "and cannot be added")
           (ng (search "Remove card" body) "or removed")
           (ok (search "<input type=\"hidden\" name=\"f-card\" value=\"on\" nm-ref" body) "so the form always says it is there"))
         (multiple-value-bind (status body)
             (edit "/s/website/m/page/new" :form '(("action" . "save") ("f-title" . "Absent") ("f-card.heading" . "Ignored")))
           (ok (= status 200) "without the form saying the custom field is there, what is inside is none")
           (let* ((loc (moved-to body)) (id (subseq loc (1+ (position #\/ loc :from-end t)))))
             (ok (null (nth-value 1 (gethash "card" (content-draft (get-content "website" id))))))))
         (multiple-value-bind (status body)
             (edit "/s/website/m/page/new" :form '(("action" . "save") ("f-title" . "P") ("f-card" . "on") ("f-card.heading" . "Too long")))
           (ok (= status 422))
           (ok (cl-ppcre:scan "<p id=\"f-card.heading-error\"[^>]*>must be at most 5 characters</p>" body)
               "an error inside is drawn under its field"))
         (multiple-value-bind (status body)
             (edit "/s/website/m/page/new" :form '(("action" . "save") ("f-title" . "P") ("f-card" . "on") ("f-card.heading" . "Hi") ("f-card.shown" . "on")
                                                   ("f-card.link" . "01ARZ3NDEKTSV4RRFFQ69G5FAV")))
           (ok (= status 200))
           (let* ((loc (moved-to body)) (id (subseq loc (1+ (position #\/ loc :from-end t)))))
             (let ((editor (nth-value 1 (request :get (format nil "/s/website/m/page/~a" id)))))
               (ok (search "value=\"Hi\"" editor) "and what was saved comes back in it")
               (ok (search "class=\"btn\" nm-bind=\"{ hidden: () => !_on, onclick: () => _remove() }\"" editor)
                   "open, with a button to remove it"))
             (ok (equal (jget (content-draft (get-content "website" id)) "card" "link") "01ARZ3NDEKTSV4RRFFQ69G5FAV")
                 "the reference picked inside is saved")
             (ok (search "Hi" (nth-value 1 (request :get "/s/website/m/page"))) "the list previews it")
             (edit (format nil "/s/website/m/page/~a" id) :form '(("action" . "save") ("f-title" . "P") ("f-card" . "on") ("f-card.heading" . "Bye")))
             (let ((history (nth-value 1 (request :get (format nil "/s/website/m/page/~a/history" id)))))
               (ok (search "heading: Bye" history) "the history shows the fields inside")
               (ng (search "HASH-TABLE" history))))))
    (replace-schema "website" (make-schema :models (list (blog-model)
                                                         (make-model "about" :object (list (make-field :body :richtext))))))))

(defun with-blocks ()
  (make-schema :custom-fields (list (make-custom-field "heading" (list (make-field :text :text :required t :max-length 5)))
                                    (make-custom-field "body" (list (make-field :text :richtext))))
               :models (list (blog-model)
                             (make-model "about" :object (list (make-field :body :richtext)))
                             (make-model "doc" :list (list (make-field :title :text)
                                                           (make-field :blocks :repeater :custom-fields '(heading body) :help "The page"))))))

(deftest a-repeater-is-edited-row-by-row
  (exec "DELETE FROM contents")
  (replace-schema "website" (with-blocks))
  (unwind-protect
       (progn
         (multiple-value-bind (status body) (request :get "/s/website/m/doc/new")
           (ok (= status 200))
           (ok (cl-ppcre:scan "<div id=\"f-blocks-label\" class=\"label\">blocks<span[^>]*>repeater</span><span[^>]*>The page</span></div>" body)
               "a heading like any field's")
           (ok (search "<div id=\"f-blocks-rows\"" body) "over the rows")
           (ok (cl-ppcre:scan "<option value=\"heading\">heading</option><option value=\"body\">body</option>" body)
               "and a choice of the custom fields a row can be"))
         (multiple-value-bind (status body) (call-action :get (repeater-row :space "website" :model "doc" :field "blocks" :kind "body"))
           (ok (= status 200))
           (ok (search "<div id=\"f-blocks-rows\" nm-swap=\"append\">" body) "a row is added at the end of the rows")
           (ok (cl-ppcre:scan "name=\"f-blocks\" value=\"([a-z0-9]+)\"" body) "with a key of its own")
           (ok (cl-ppcre:scan "name=\"f-blocks\\.[a-z0-9]+\\.fieldId\" value=\"body\"" body) "naming its custom field")
           (ok (cl-ppcre:scan "data-quill-for=\"f-blocks\\.[a-z0-9]+\\.text\"" body) "and its fields under its key"))
         (ok (= 404 (call-action :get (repeater-row :space "website" :model "doc" :field "blocks" :kind "ghost")))
             "a custom field the repeater does not list makes no row")
         (multiple-value-bind (status body)
             (edit "/s/website/m/doc/new" :form '(("action" . "save") ("f-title" . "D") ("f-blocks" . "a,b")
                                                  ("f-blocks.a.fieldId" . "body") ("f-blocks.a.text" . "<p>Hi</p>")
                                                  ("f-blocks.b.fieldId" . "heading") ("f-blocks.b.text" . "Too long")))
           (ok (= status 422))
           (ok (cl-ppcre:scan "<p id=\"f-blocks.b.text-error\"[^>]*>must be at most 5 characters</p>" body)
               "an error in a row is drawn under its field"))
         (multiple-value-bind (status body)
             (edit "/s/website/m/doc/new" :form '(("action" . "save") ("f-title" . "D") ("f-blocks" . "a,b")
                                                  ("f-blocks.a.fieldId" . "body") ("f-blocks.a.text" . "<p>Hi</p>")
                                                  ("f-blocks.b.fieldId" . "heading") ("f-blocks.b.text" . "Head")))
           (ok (= status 200))
           (let* ((loc (moved-to body)) (id (subseq loc (1+ (position #\/ loc :from-end t)))))
             (let ((rows (jget (content-draft (get-content "website" id)) "blocks")))
               (ok (equal (map 'list (lambda (r) (jget r "fieldId")) rows) '("body" "heading")) "the rows are saved in order"))
             (let ((editor (nth-value 1 (request :get (format nil "/s/website/m/doc/~a" id)))))
               (ok (search "value=\"Head\"" editor) "and drawn again")
               (ok (search "aria-label=\"Move row up\"" editor) "each one movable")
               (ok (search "aria-label=\"Remove row\"" editor) "and removable"))
             (ok (search "2 rows" (nth-value 1 (request :get "/s/website/m/doc"))) "the list counts them")
             (edit (format nil "/s/website/m/doc/~a" id)
                   :form '(("action" . "save") ("f-title" . "D") ("f-blocks" . "b")
                           ("f-blocks.b.fieldId" . "heading") ("f-blocks.b.text" . "Bye")))
             (let ((history (nth-value 1 (request :get (format nil "/s/website/m/doc/~a/history" id)))))
               (ok (search "heading: text: Bye" history) "the history shows each row")
               (ng (search "HASH-TABLE" history))))))
    (replace-schema "website" (make-schema :models (list (blog-model)
                                                         (make-model "about" :object (list (make-field :body :richtext))))))))
