(defpackage #:koya-spec/server/web/pages/media
  (:use #:cl #:rove)
  (:import-from #:koya-server/web/lib/binds #:on-search #:on-reveal #:on-pick)
  (:import-from #:koya-spec/server/web/pages/support
                #:replaced-url #:bound #:post-login #:edit #:moved-to #:*secret* #:*cookie* #:blog-model #:request
                #:location #:request-url #:call-action #:setup-pages #:log-in)
  (:import-from #:koya-server/infra/db/connection #:disconnect-db)
  (:import-from #:koya-server/usecases/ports/contents #:list-contents)
  (:import-from #:koya-server/domain/content #:content-id)
  (:import-from #:koya-server/usecases/ports/media #:list-media #:count-media)
  (:import-from #:koya-server/domain/media #:media-id #:media-filename)
  (:import-from #:koya-server/web/ui/media/picker
                #:media-picker #:media-picker-search #:media-picker-more #:media-picker-upload)
  (:import-from #:koya-server/web/pages/s/<space>/media
                #:browse-media #:upload-media #:delete-media-action #:delete-selected-media #:preview-media #:save-alt)
  (:import-from #:koya-spec/server/usecases/media #:png-bytes)
  (:import-from #:koya-server/domain/query #:parse-query)
  (:import-from #:koya-server/usecases/media #:store-upload)
  (:import-from #:koya-server/usecases/contents #:create)
  (:import-from #:koya-server/usecases/schema #:resolve-model)
  (:import-from #:koya-core/json #:jobject)
  (:import-from #:babel #:string-to-octets))
(in-package #:koya-spec/server/web/pages/media)

(defun escaped (url)
  (cl-ppcre:regex-replace-all "&" url "&amp;"))

(defun count-matches (needle haystack)
  (loop :for start := 0 :then (+ found (length needle))
        :for found := (search needle haystack :start2 start)
        :while found :count t))

(setup (setup-pages) (log-in))

(teardown (disconnect-db))

(deftest media-library
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (multiple-value-bind (status body) (request :get "/s/website/media")
      (ok (= status 200))
      (ok (search "No media yet" body))
      (ok (search (bound (on-pick (upload-media :space "website" :q "" :page 1))) body)
          "a file goes as it is chosen"))
    (testing "upload from the library page"
      (multiple-value-bind (status body)
          (call-action :post (upload-media :space "website" :q "" :page 1)
                       :multipart (list (list "file" "cover.png" "image/png" (png-bytes 4 4))
                                        (list "file" "second.png" "image/png" (png-bytes 8 8))))
        (ok (= status 200))
        (ok (search "id=\"library\"" body) "the library is drawn again")
        (ok (search "Uploaded 2 files." body))
        (ok (search "cover.png" body)))
      (multiple-value-bind (status body) (request :get "/s/website/media")
        (ok (= status 200))
        (ok (search "<dialog id=\"media-preview\"" body) "preview modal is on the page")
        (ok (search (subseq (preview-media) 0 (position #\? (preview-media))) body) "cards ask for it")
        (ok (search "/media/website/" body)))
      (multiple-value-bind (status body) (request :get "/s/website/media" :query "q=second")
        (ok (= status 200))
        (ok (search "second.png" body))
        (ok (not (search "cover.png" body)) "search narrows the grid"))
      (multiple-value-bind (status body) (call-action :get (browse-media :space "website" :q "second" :page 1))
        (ok (= status 200))
        (ok (search "id=\"library\"" body) "a search is answered in place")
        (ok (search "second.png" body))
        (ng (search "cover.png" body))
        (ok (search "<span id=\"media-count\" class=\"ml-3 text-base font-normal text-muted\">1 file<" body)
            "with the count beside it")
        (ng (search "Search file names" body) "and not the box being typed in")
        (ok (string= (replaced-url body) "/s/website/media?q=second")))
      (ok (search (format nil "nm-data=\"...koya.search()\" ~a" (bound (on-search (browse-media :space "website"))))
                  (nth-value 1 (request :get "/s/website/media")))
          "the box searches as the typing stops")
      (multiple-value-bind (status body)
          (call-action :post (upload-media :space "website" :q "" :page 1)
                       :multipart (list (list "file" "notes.txt" "text/plain" (babel:string-to-octets "hi"))))
        (ok (= status 200))
        (ok (search "Only PNG, JPEG, GIF and WebP" body) "rejection shows as a toast")))
    (testing "editor offers the picker for a :media field"
      (multiple-value-bind (status body) (request :get "/s/website/m/blog/new")
        (ok (= status 200))
        (ok (search "nm-data=\"...koya.mediaField({&quot;id&quot;:&quot;&quot;" body) "the field holds the file it shows")
        (ok (search "onclick: () => _choose()" body))
        (ok (search "<dialog id=\"media-picker\"" body))
        (ok (search (format nil "nm-data=\"...koya.mediaPicker(this, &quot;~a&quot;)\"" (media-picker :space "website")) body)
            "and the picker who opened it")
        (ok (search (bound "{ onclick: (e) => e.target === this && _close(), onopenpicker: (e) => _open(e.detail) }")
                    body)
            "the picker opens itself, from whichever control asks")
        (ok (search (media-picker :space "website") body) "dialog knows the picker URL")))
    (testing "picker fragment"
      (multiple-value-bind (status body) (call-action :get (media-picker :space "website"))
        (ok (= status 200))
        (ok (search "data-pick-id=" body))
        (ok (search "data-pick-url=\"/media/website/" body))
        (ok (not (search "<html" body)) "a fragment, not a page")
        (ok (search "nm-bind=\"{ onclick: () => _pick(this.dataset) }\"" body) "a card hands its file over")
        (ok (search (bound (on-search (media-picker-search :space "website"))) body) "the box searches as the typing stops")
        (ok (search (bound (on-pick (media-picker-upload :space "website"))) body)))
      (multiple-value-bind (status body) (call-action :get (media-picker-search :space "website" :q "zzz-nothing"))
        (ok (= status 200))
        (ok (search "<div id=\"media-picker-grid\"" body) "a search answers the grid")
        (ng (search "Search file names" body) "and not the box being typed in")
        (ng (search "data-pick-id=" body) "narrowed by what was typed"))
      (let ((*cookie* nil))
        (multiple-value-bind (status) (call-action :get (media-picker :space "website"))
          (ok (= status 401) "the picker needs the owner session")))
      (ok (= (request-url :get (media-picker :space "website")) 400)
          "an action answers the admin UI only: a plain request is refused"))
    (testing "picker upload"
      (flet ((upload (name &rest args)
               (apply #'call-action :post (media-picker-upload :space "website")
                      :multipart (list (list "file" name "image/png" (png-bytes 2 2)))
                      args)))
        (multiple-value-bind (status body) (upload "picked.png" :headers origin)
          (ok (= status 200))
          (ok (search "picked.png" body) "the new file is in the returned grid"))
        (let ((*cookie* nil))
          (ok (= (upload "anon.png" :headers origin) 401) "uploading needs the owner session"))
        (ok (= (upload "cross.png" :headers '(("origin" . "https://evil.test"))) 403)
            "a cross-origin upload is rejected")
        (ok (null (list-media "website" :search "anon")))
        (ok (null (list-media "website" :search "cross")))))
    (testing "every action is behind the owner session"
      (let ((*cookie* nil))
        (ok (= (call-action :get "/actions/not-an-action-000000") 401)
            "the gate is at the mount, not in each action")))
    (testing "the preview, alt and delete"
      (let ((id (media-id (first (list-media "website" :search "cover")))))
        (multiple-value-bind (status body) (call-action :get (preview-media :space "website" :id id))
          (ok (= status 200))
          (ok (search "<dialog id=\"media-preview\" closedby=\"any\" nm-bind=\"{ oninit: () => this.showModal() }\"" body)
              "the dialog is drawn for the file, and opens itself")
          (ok (search "4×4" body))
          (ok (search "value=\"\"" body) "with its alt text"))
        (multiple-value-bind (status body) (call-action :post (save-alt :space "website" :id id) :form '(("alt" . "New alt")))
          (ok (= status 200))
          (ok (search "<span id=\"alt-saved\" class=\"shrink-0 text-sm text-ok\">Saved.</span>" body)))
        (ok (search "value=\"New alt\"" (nth-value 1 (call-action :get (preview-media :space "website" :id id)))))
        (multiple-value-bind (status body) (call-action :post (delete-media-action :space "website" :q "" :page 1)
                                                        :form `(("id" . ,id)))
          (ok (= status 200))
          (ok (search "Media deleted." body))
          (ok (search "<dialog id=\"media-preview\" closedby=\"any\" class=" body)
              "an empty dialog takes the open one's place"))
        (ok (null (list-media "website" :search "cover")))
        (ok (= 404 (call-action :get (preview-media :space "website" :id id))) "a file that is gone has no preview")))))

(deftest bulk-delete-in-the-media-library
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (setf *cookie* nil)
    (post-login :form `(("secret" . ,*secret*)))
    (flet ((upload (name)
             (call-action :post (upload-media :space "website" :q "" :page 1)
                          :multipart (list (list "file" name "image/png" (png-bytes))))

             (media-id (find name (list-media "website") :key #'media-filename :test #'string=)))
           (delete-selected (&rest ids)
             (nth-value 1 (call-action :post (delete-selected-media :space "website" :q "bulk" :page 1)
                                       :form (and ids `(("id" . ,(format nil "~{~a~^,~}" ids))))))))
      (let ((a (upload "bulk-a.png"))
            (b (upload "bulk-b.png")))
        (testing "every card carries a box, tied to the selection form"
          (multiple-value-bind (status body) (request :get "/s/website/media")
            (ok (= status 200))
            (ok (search "Select all on this page" body))
            (ok (search "id=\"media-bulk\"" body))
            (ok (search (format nil "name=\"id\" value=\"~a\" form=\"media-bulk\"" a) body)
                "the box posts to the form outside the card, because forms do not nest")))
        (testing "deleting a selection deletes each file, and answers the search it was made from"
          (multiple-value-bind (status body)
              (call-action :post (delete-selected-media :space "website" :q "bulk" :page 1)
                           :form `(("id" . ,(format nil "~a,~a" a b))))
            (declare (ignore status))
            (ok (search "Deleted 2 files." body))
            (ok (string= (replaced-url body) "/s/website/media?q=bulk") "the URL keeps the search"))
          (ok (null (list-media "website" :search "bulk")) "both gone"))
        (testing "a file a content still uses stays, and the rest still go"
          (let* ((kept (upload "bulk-kept.png"))
                 (other (upload "bulk-other.png")))
            (edit "/s/website/m/blog/new"
                      :form `(("action" . "save") ("f-title" . "Uses an image") ("f-cover" . ,kept))
                     :headers origin)
            (let ((body (delete-selected kept other)))
              (ok (search "Deleted 1 of 2; 1 could not be" body))
              (ok (search "is used by 1 content" body) "and says which and why"))
            (ok (find kept (list-media "website") :key #'media-id :test #'string=) "the one in use is still there")
            (ng (find other (list-media "website") :key #'media-id :test #'string=))
            (let ((content (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
              (edit (format nil "/s/website/m/blog/~a" (content-id content))
                        :form '(("action" . "delete")) :headers origin))
            (call-action :post (delete-media-action :space "website") :form `(("id" . ,kept)))))
        (testing "nothing selected is not an action"
          (ok (search "Nothing was selected." (delete-selected))))))))

(deftest the-picker-scrolls-through-the-library
  (dotimes (i 17)
    (store-upload "website" (png-bytes 1 1) :filename (format nil "paged-~2,'0d.png" i)))
  (flet ((cards (body) (count-matches "data-pick-id=" body))
         (answer (url) (nth-value 1 (call-action :get url))))
    (let* ((total (count-media "website"))
           (pages (ceiling total 12)))
      (let ((body (answer (media-picker :space "website"))))
        (ok (= (cards body) 12) "the picker opens on three rows of four")
        (let ((more (media-picker-more :space "website" :q "" :page 2)))
          (ok (search (format nil "<li id=\"~a\" class=\"col-span-full py-2 text-center text-xs text-muted\" ~a"
                              (escaped more) (bound (on-reveal more)))
                      body)
              "and fetches the next ones as its last row comes into view")))
      (let* ((url (media-picker-more :space "website" :q "" :page pages))
             (body (answer url)))
        (ok (= (cards body) (- total (* 12 (1- pages)))) "the last fetch holds the rest")
        (ng (search "koya.reveal" body) "and asks for nothing after it")
        (ok (eql 0 (search (format nil "<ul id=\"~a\" nm-swap=\"before\">" (escaped url)) body))
            "cards to put before the placeholder that asked, which is gone if the picker was drawn again")
        (ok (search (format nil "</ul><li id=\"~a\" hidden></li>" (escaped url)) body)
            "and the placeholder put out of sight"))
      (let ((body (answer (media-picker :space "website" :q "paged-"))))
        (ok (= (cards body) 12) "a search is fetched the same way")
        (ok (search (bound (on-reveal (media-picker-more :space "website" :q "paged-" :page 2))) body)))
      (ok (= (cards (answer (media-picker-more :space "website" :q "paged-" :page 2))) 5)))))

(deftest the-preview-lists-what-uses-a-file
  (let ((id (media-id (store-upload "website" (png-bytes 1 1) :filename "used.png"))))
    (ok (null (search "Used by" (nth-value 1 (call-action :get (preview-media :space "website" :id id)))))
        "a file nothing uses says nothing about it")
    (multiple-value-bind (space model) (resolve-model "website" "blog")
      (let ((user (content-id (create space model (jobject "title" "Has a cover" "cover" id)))))
        (let ((body (nth-value 1 (call-action :get (preview-media :space "website" :id id)))))
          (ok (search "Used by 1 content" body))
          (ok (search (format nil "href=\"/s/website/m/blog/~a\"" user) body) "each one is a link to its editor")
          (ok (search ">Has a cover<" body) "named by its label"))
        (call-action :post (delete-media-action :space "website") :form `(("id" . ,id)))
        (ok (search "Used by" (nth-value 1 (call-action :get (preview-media :space "website" :id id))))
            "and a refused delete leaves it in use")))))
