(defpackage #:koya-spec/server/web/pages/settings
  (:use #:cl #:rove)
  (:import-from #:koya-server/web/lib/binds #:on-click #:on-submit)
  (:import-from #:koya-spec/server/web/pages/support
                #:bound #:post-login #:edit #:moved-to #:*secret* #:*cookie* #:blog-model #:request
                #:location #:call-action #:setup-pages #:log-in)
  (:import-from #:koya-server/web/pages/settings
                #:save-timezone-action #:begin-two-factor-action #:cancel-two-factor-action
                #:enable-two-factor-action #:disable-two-factor-action #:end-other-sessions-action)
  (:import-from #:koya-server/infra/db/connection #:disconnect-db)
  (:import-from #:koya-server/usecases/ports/contents #:list-contents)
  (:import-from #:koya-server/domain/content #:content-draft #:content-id)
  (:import-from #:koya-server/domain/totp #:totp)
  (:import-from #:koya-server/domain/timezone #:find-timezone)
  (:import-from #:koya-server/usecases/settings
                #:*totp-last-counter* #:totp-enabled-p #:display-timezone-name)
  (:import-from #:koya-server/domain/query #:parse-query)
  (:import-from #:cl-ppcre #:scan-to-strings)
  (:import-from #:koya-core/json #:jget))
(in-package #:koya-spec/server/web/pages/settings)

(setup (setup-pages) (log-in))

(teardown (disconnect-db))

(defun forget-used-code () (setf *totp-last-counter* -1))

(defun another-session (&optional code)
  (let ((*cookie* nil))
    (post-login :form `(("secret" . ,*secret*) ,@(and code `(("code" . ,code)))))
    *cookie*))

(defun owner-p (cookie)
  (let ((*cookie* cookie))
    (= 200 (request :get "/settings"))))

(defun setup-secret ()
  (aref (nth-value 1 (scan-to-strings "secret=([A-Z2-7]+)&amp;" (nth-value 1 (call-action :post (begin-two-factor-action)))))
        0))

(deftest two-factor-settings
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (setf *cookie* nil)
    (post-login :form `(("secret" . ,*secret*)))
    (ok (not (totp-enabled-p)) "starts disabled")
    (multiple-value-bind (status body) (request :get "/settings")
      (ok (= status 200))
      (ok (search "Disabled" body))
      (ok (search "Set up two-factor login" body)))
    (ok (= 200 (call-action :post (begin-two-factor-action))))
    (let ((secret nil))
      (multiple-value-bind (status body) (request :get "/settings")
        (ok (= status 200))
        (ok (search "data-qr=\"otpauth://totp/koya:owner?secret=" body) "QR code carries the otpauth URI")
        (multiple-value-bind (match groups) (scan-to-strings "secret=([A-Z2-7]+)&amp;" body)
          (ok match)
          (setf secret (and match (aref groups 0)))))
      (ok (not (totp-enabled-p)) "not enabled until a code confirms the app has the secret")
      (multiple-value-bind (status body) (call-action :post (enable-two-factor-action) :form '(("code" . "000000")))
        (ok (= status 422))
        (ok (search "did not match" body)))
      (forget-used-code)
      (multiple-value-bind (status body)
          (call-action :post (enable-two-factor-action) :form `(("code" . ,(totp secret))))
        (ok (= status 200))
        (ok (search "Two-factor login is on" body) "toast"))
      (ok (totp-enabled-p))
      (multiple-value-bind (status body) (request :get "/settings")
        (ok (= status 200))
        (ok (search "Disable two-factor login" body)))
      (testing "logging in now needs the code"
        (let ((*cookie* nil))
          (multiple-value-bind (status) (post-login :form `(("secret" . ,*secret*)))
            (ok (= status 401)))
          (forget-used-code)
          (multiple-value-bind (status) (post-login :form `(("secret" . ,*secret*) ("code" . ,(totp secret))))
            (ok (= status 200)))))
      (testing "disabling needs a code too"
        (multiple-value-bind (status body) (call-action :post (disable-two-factor-action) :form '(("code" . "000000")))
          (ok (= status 422))
          (ok (search "still on" body)))
        (ok (totp-enabled-p))
        (forget-used-code)
        (ok (= 200 (call-action :post (disable-two-factor-action) :form `(("code" . ,(totp secret))))))
        (ok (not (totp-enabled-p)))
        (let ((*cookie* nil))
          (multiple-value-bind (status) (post-login :form `(("secret" . ,*secret*)))
            (ok (= status 200) "secret alone logs in again")))))))

(deftest time-zone-setting
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (setf *cookie* nil)
    (post-login :form `(("secret" . ,*secret*)))
    (multiple-value-bind (status body) (request :get "/settings")
      (ok (= status 200))
      (ok (search "Time zone" body))
      (ok (search "value=\"UTC\"" body) "UTC until the owner picks a zone")
      (ok (search "<option value=\"UTC\">" body) "the datalist offers the zones"))
    (multiple-value-bind (status body) (call-action :post (save-timezone-action) :form '(("timezone" . "Mars/Olympus_Mons")))
      (ok (= status 422))
      (ok (search "not a time zone" body))
      (ok (string= (display-timezone-name) "UTC") "nothing stored"))
    (if (null (find-timezone "Asia/Tokyo"))
        (skip "no zone database on this machine")
        (progn
          (multiple-value-bind (status body) (call-action :post (save-timezone-action) :form '(("timezone" . "Asia/Tokyo")))
            (ok (= status 200))
            (ok (search "Times are now shown in Asia&#x2F;Tokyo" body) "toast (text is escaped, attributes are not)")
            (ok (search "value=\"Asia/Tokyo\"" body)))
          (ok (string= (display-timezone-name) "Asia/Tokyo"))
          (testing "the editor takes and shows datetimes in that zone"
            (let ((id nil))
              (multiple-value-bind (status body)
                  (edit "/s/website/m/blog/new"
                            :form '(("action" . "save") ("f-title" . "Tokyo time") ("f-when" . "2026-09-21T08:30")) :headers origin)
                (ok (= status 200))
                (let* ((loc (moved-to body)) (path (subseq loc 0 (position #\? loc))))
                  (setf id (subseq path (1+ (position #\/ path :from-end t))))))
              (let ((content (find-if (lambda (c) (string= (content-id c) id))
                                      (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
                (ok (string= (jget (content-draft content) "when") "2026-09-20T23:30:00.000Z") "stored as UTC"))
              (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
                (ok (= status 200))
                (ok (search "value=\"2026-09-21T08:30\"" body) "shown back in the zone")
                (ok (search ">Asia&#x2F;Tokyo<" body) "the hint names the zone")
                (ok (search " JST</span>" body) "created at is in the zone"))
              (multiple-value-bind (status body) (request :get "/s/website/m/blog")
                (ok (= status 200))
                (ok (search "2026-09-21 08:30 JST" body) "list preview in the zone"))
              (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "delete")) :headers origin)))
          (ok (= 200 (call-action :post (save-timezone-action) :form '(("timezone" . "UTC")))))
          (ok (string= (display-timezone-name) "UTC") "back to UTC for the other tests")))))

(deftest settings-are-worked-on-in-place
  (setf *cookie* nil)
  (post-login :form `(("secret" . ,*secret*)))
  (testing "the time zone card is answered in place"
    (multiple-value-bind (status body) (call-action :post (save-timezone-action) :form '(("timezone" . "Asia/Tokyo")))
      (ok (= status 200))
      (ok (search "id=\"time-zone\"" body))
      (ok (search "Times are now shown in Asia&#x2F;Tokyo." body))
      (ok (search "<div id=\"toast\"" body) "the toast beside it")
      (ng (search "<html" body)))
    (multiple-value-bind (status body) (call-action :post (save-timezone-action) :form '(("timezone" . "Mars/Olympus")))
      (ok (= status 422))
      (ok (search "is not a time zone" body) "the error is inside the card")
      (ng (search "<div id=\"toast\"" body)))
    (call-action :post (save-timezone-action) :form '(("timezone" . "UTC"))))
  (testing "two-factor login is set up step by step in its card"
    (let ((secret nil))
      (multiple-value-bind (status body) (call-action :post (begin-two-factor-action))
        (ok (= status 200))
        (ok (search "id=\"two-factor\"" body))
        (ok (search "data-qr=\"otpauth://" body))
        (ok (search "nm-bind=\"{ oninit: () => koya.qr(this) }\"" body) "drawn as it comes in")
        (ok (search (format nil "<button type=\"button\" class=\"btn\" ~a" (bound (on-click (cancel-two-factor-action)))) body)
            "cancelling sends no form, so it needs no code")
        (multiple-value-bind (match groups) (scan-to-strings "secret=([A-Z2-7]+)&amp;" body)
          (ok match)
          (setf secret (and match (aref groups 0)))))
      (multiple-value-bind (status body) (call-action :post (cancel-two-factor-action))
        (ok (= status 200))
        (ok (search "Set up two-factor login" body) "cancelling goes back to the start"))
      (multiple-value-bind (status body) (call-action :post (begin-two-factor-action))
        (declare (ignore status))
        (setf secret (aref (nth-value 1 (scan-to-strings "secret=([A-Z2-7]+)&amp;" body)) 0)))
      (multiple-value-bind (status body) (call-action :post (enable-two-factor-action) :form '(("code" . "000000")))
        (ok (= status 422))
        (ok (search "did not match" body))
        (ok (search "data-qr=" body) "and the setup stays open"))
      (forget-used-code)
      (multiple-value-bind (status body) (call-action :post (enable-two-factor-action) :form `(("code" . ,(totp secret))))
        (ok (= status 200))
        (ok (search "Two-factor login is on" body))
        (ok (search "Disable two-factor login" body)))
      (ok (totp-enabled-p))
      (forget-used-code)
      (multiple-value-bind (status body) (call-action :post (disable-two-factor-action) :form `(("code" . ,(totp secret))))
        (ok (= status 200))
        (ok (search "Two-factor login is off." body)))
      (ok (not (totp-enabled-p)))))
  (testing "no session, no action"
    (let ((*cookie* nil))
      (ok (= 401 (call-action :post (begin-two-factor-action)))))))

(deftest turning-two-factor-on-or-off-ends-every-other-session
  (log-in)
  (let ((other (another-session))
        (secret (setup-secret)))
    (forget-used-code)
    (ok (= 200 (call-action :post (enable-two-factor-action) :form `(("code" . ,(totp secret))))))
    (ng (owner-p other) "a session from before is over")
    (ok (owner-p *cookie*) "while the one that turned it on goes on")
    (forget-used-code)
    (let ((other (another-session (totp secret))))
      (ok (owner-p other))
      (forget-used-code)
      (ok (= 200 (call-action :post (disable-two-factor-action) :form `(("code" . ,(totp secret))))))
      (ng (owner-p other) "and turning it off ends the others too")
      (ok (owner-p *cookie*)))))

(deftest other-sessions-are-ended-from-the-settings-page
  (log-in)
  (let ((other (another-session)))
    (let ((body (nth-value 1 (request :get "/settings"))))
      (ok (search "Log out other sessions" body))
      (ok (search (bound (on-submit (end-other-sessions-action))) body)))
    (multiple-value-bind (status body) (call-action :post (end-other-sessions-action))
      (ok (= status 200))
      (ok (search "Every other session has ended." body)))
    (ng (owner-p other))
    (ok (owner-p *cookie*) "this one goes on")))
