(defpackage #:koya-server/web/admin-api/schema/<space>/plan
  (:use #:cl)
  (:import-from #:koya-core/schema #:jobject->schema)
  (:import-from #:koya-core/diff #:destructive-changes-p)
  (:import-from #:koya-server/web/lib/presenters #:changes->jarray)
  (:import-from #:koya-core/json #:jobject)
  (:import-from #:koya-server/web/lib/http #:read-json-body #:path-param)
  (:import-from #:koya-server/usecases/schema #:plan)
  (:export #:@post))
(in-package #:koya-server/web/admin-api/schema/<space>/plan)

(defun @post (params)
  (let ((changes (plan (path-param params :space) (jobject->schema (read-json-body)))))
    (jobject "changes" (changes->jarray changes)
             "destructive" (destructive-changes-p changes))))
