(defsystem "koya-spec"
  :class :package-inferred-system
  :pathname "spec"
  :depends-on ("rove"
               "koya-sdk"
               "koya-server"
               "koya-spec/core/ulid"
               "koya-spec/core/case"
               "koya-spec/core/schema"
               "koya-spec/core/validate"
               "koya-spec/core/diff"
               "koya-spec/sdk/config"
               "koya-spec/sdk/main"
               "koya-spec/server/domain/totp"
               "koya-spec/server/domain/timezone"
               "koya-spec/server/domain/number"
               "koya-spec/server/domain/address"
               "koya-spec/server/domain/references"
               "koya-spec/server/domain/content"
               "koya-spec/server/usecases/settings"
               "koya-spec/server/infra/db"
               "koya-spec/server/infra/webhook-sender"
               "koya-spec/server/usecases/contents"
               "koya-spec/server/usecases/delivery"
               "koya-spec/server/usecases/revisions"
               "koya-spec/server/usecases/media"
               "koya-spec/server/web/lib/http"
               "koya-spec/server/usecases/webhooks"
               "koya-spec/server/web/admin-api/schema"
               "koya-spec/server/web/admin-api/contents"
               "koya-spec/server/web/admin-api/media"
               "koya-spec/server/web/admin-api/keys"
               "koya-spec/server/web/app"
               "koya-spec/server/web/lib/auth"
               "koya-spec/server/web/lib/binds"
               "koya-spec/server/web/lib/forms"
               "koya-spec/server/web/lib/health"
               "koya-spec/server/web/ui/elements"
               "koya-spec/server/web/pages/login"
               "koya-spec/server/web/pages/index"
               "koya-spec/server/web/pages/settings"
               "koya-spec/server/web/pages/keys"
               "koya-spec/server/web/pages/webhooks"
               "koya-spec/server/web/pages/deploys"
               "koya-spec/server/web/pages/media"
               "koya-spec/server/web/pages/content-list"
               "koya-spec/server/web/pages/editor"
               "koya-spec/server/web/pages/space-import"
               "koya-spec/server/usecases/ports/main"
               "koya-spec/server/layers"
               "koya-spec/sdk/client")
  :perform (test-op (o c) (symbol-call :rove :run c :style :dot)))
