(defsystem "koya-tests"
  :class :package-inferred-system
  :pathname "tests"
  :depends-on ("rove"
               "koya"
               "koya-server"
               "koya-tests/core/ulid"
               "koya-tests/core/case"
               "koya-tests/core/schema"
               "koya-tests/core/validate"
               "koya-tests/core/diff"
               "koya-tests/config"
               "koya-tests/server/domain/totp"
               "koya-tests/server/domain/timezone"
               "koya-tests/server/db"
               "koya-tests/server/features/contents/service"
               "koya-tests/server/features/media/store"
               "koya-tests/server/http"
               "koya-tests/server/features/webhooks/notify"
               "koya-tests/server/admin-api/schema"
               "koya-tests/server/admin-api/contents"
               "koya-tests/server/admin-api/media"
               "koya-tests/server/admin-api/keys"
               "koya-tests/server/app"
               "koya-tests/server/pages/login"
               "koya-tests/server/pages/index"
               "koya-tests/server/pages/settings"
               "koya-tests/server/pages/keys"
               "koya-tests/server/pages/webhooks"
               "koya-tests/server/pages/deploys"
               "koya-tests/server/pages/media"
               "koya-tests/server/pages/content-list"
               "koya-tests/server/pages/editor"
               "koya-tests/server/pages/space-import"
               "koya-tests/client")
  :perform (test-op (o c) (symbol-call :rove :run c :style :dot)))
