(defsystem "koya-tests"
  :class :package-inferred-system
  :pathname "tests"
  :depends-on ("rove"
               "koya"
               "koya-server"
               "koya-tests/core/ulid"
               "koya-tests/core/case"
               "koya-tests/core/schema"
               "koya-tests/core/validate"
               "koya-tests/core/diff"
               "koya-tests/config"
               "koya-tests/server/domain/totp"
               "koya-tests/server/domain/timezone"
               "koya-tests/server/usecases/settings/two-factor"
               "koya-tests/server/infra/db"
               "koya-tests/server/usecases/contents/write"
               "koya-tests/server/usecases/media/library"
               "koya-tests/server/web/http"
               "koya-tests/server/usecases/webhooks/notify"
               "koya-tests/server/web/admin-api/schema"
               "koya-tests/server/web/admin-api/contents"
               "koya-tests/server/web/admin-api/media"
               "koya-tests/server/web/admin-api/keys"
               "koya-tests/server/web/app"
               "koya-tests/server/web/pages/login"
               "koya-tests/server/web/pages/index"
               "koya-tests/server/web/pages/settings"
               "koya-tests/server/web/pages/keys"
               "koya-tests/server/web/pages/webhooks"
               "koya-tests/server/web/pages/deploys"
               "koya-tests/server/web/pages/media"
               "koya-tests/server/web/pages/content-list"
               "koya-tests/server/web/pages/editor"
               "koya-tests/server/web/pages/space-import"
               "koya-tests/server/layers"
               "koya-tests/client")
  :perform (test-op (o c) (symbol-call :rove :run c :style :dot)))
