(defpackage #:koya-tests/server/app
  (:use #:cl #:rove)
  (:import-from #:koya-tests/server/pages/support #:edit #:moved-to #:*cookie* #:request #:location #:setup-pages #:log-in)
  (:import-from #:koya-server/app #:*app*)
  (:import-from #:koya-server/infra/db/connection #:disconnect-db)
  (:import-from #:alexandria #:alist-hash-table)
  (:import-from #:babel #:string-to-octets)
  (:import-from #:flexi-streams #:make-in-memory-input-stream)
  (:import-from #:koya-server/pages/index #:import-space-action))
(in-package #:koya-tests/server/app)

(setup (setup-pages) (log-in))

(teardown (disconnect-db))

(deftest pages
  (multiple-value-bind (status body) (request :get "/s/website")
    (ok (= status 200))
    (ok (search "blog" body))
    (ok (search "about" body)))
  (multiple-value-bind (status body) (request :get "/s/website/m/blog")
    (ok (= status 200))
    (ok (search "New content" body)))
  (multiple-value-bind (status body headers) (request :get "/s/website/m/about")
    (declare (ignore body))
    (ok (= status 302))
    (ok (string= (location headers) "/s/website/m/about/new") "object model goes straight to its editor"))
  (multiple-value-bind (status body) (request :get "/s/website/m/blog/new")
    (ok (= status 200))
    (ok (search "name=\"f-title\"" body))
    (ok (search "name=\"f-body\"" body))
    (ok (search "type=\"checkbox\"" body))
    (ok (search "datetime-local" body))
    (ok (search "data-quill-for=\"f-body\"" body) "rich text gets a Quill holder")
    (ok (search "id=\"editor-form\" class=\"space-y-6\" data-editor-form hx-post=" body) "the form is an action"))
  (multiple-value-bind (status) (request :get "/s/nope")
    (ok (= status 404)))
  (multiple-value-bind (status) (edit "/s/website/m/blog/new" :form '(("action" . "delete")))
    (ok (= status 404) "delete on /new has nothing to delete"))
  (multiple-value-bind (status) (edit "/s/website/m/blog/new" :form '(("action" . "unpublish")))
    (ok (= status 404)))
  (multiple-value-bind (status) (request :get "/s/website/m/nope")
    (ok (= status 404)))
  (multiple-value-bind (status) (request :get "/s/website/m/blog/01ARZ3NDEKTSV4RRFFQ69G5FAV")
    (ok (= status 404))))

(deftest every-page-offers-the-source
  (let ((version (asdf:component-version (asdf:find-system "koya-server"))))
    (flet ((footer-p (body)
             (and (search (format nil "koya ~a" version) body)
                  (search "href=\"https://github.com/skyizwhite/koya\"" body)
                  (search "GNU AGPL v3.0" body))))
      (ok (footer-p (nth-value 1 (request :get "/s/website"))) "a page behind the session")
      (let ((*cookie* nil))
        (ok (footer-p (nth-value 1 (request :get "/login"))) "the login page, before any session")))))

(deftest cache-control
  ;; icon.svg, not the stylesheet: dist.css is built by Tailwind and is not in
  ;; the repository, so it is there only on a machine that has run `just build`
  (multiple-value-bind (status body headers) (request :get "/assets/icon.svg")
    (declare (ignore body))
    (ok (= status 200))
    (ok (string= (getf headers :cache-control) "public, max-age=31536000, immutable") "assets are immutable"))
  (multiple-value-bind (status body headers) (request :get "/assets/nope.css")
    (declare (ignore body))
    (ok (= status 404))
    (ok (string= (getf headers :cache-control) "no-store") "a missing asset is not cached"))
  (let ((*cookie* nil))
    (multiple-value-bind (status body headers) (request :get "/login")
      (ok (= status 200))
      (ok (string= (getf headers :cache-control) "no-store") "pages are not cached")
      (ok (search "/assets/style/dist.css?v=" body) "asset URLs carry a version")
      (ok (search "/assets/icon.svg?v=" body)))))

(deftest body-size-limit
  (flet ((huge-post (headers &key (path "/login") (mb 3000) (content-type "multipart/form-data; boundary=x"))
           (funcall *app* (list :request-method :post :script-name "" :path-info path :query-string ""
                                :server-name "localhost" :server-port 3000 :server-protocol :http/1.1
                                :request-uri path :url-scheme "http" :remote-addr "127.0.0.1"
                                :headers (alist-hash-table (acons "host" "localhost:3000" headers) :test 'equal)
                                :content-type content-type :content-length (* mb 1024 1024)
                                :raw-body (make-in-memory-input-stream (string-to-octets ""))))))
    (destructuring-bind (status headers body) (huge-post nil)
      (declare (ignore headers))
      (ok (= status 413) "a huge Content-Length is refused before the body is read")
      (ok (search "too_large" (first body))))
    (destructuring-bind (status headers body) (huge-post '(("hx-request" . "true")))
      (ok (= status 413))
      (ok (search "text/html" (getf headers :content-type)) "htmx swaps it in, so it is HTML")
      (ok (search "limited to" (first body)))
      (ok (not (search "too_large" (first body)))))
    (testing "an import may be larger, but not without end"
      (ok (/= 413 (first (huge-post nil :path (import-space-action) :mb 100 :content-type "application/zip")))
          "a space archive carries every media file")
      (ok (= 413 (first (huge-post nil :path (import-space-action) :mb 100)))
          "but only as the body itself: lack would hold a multipart one in memory")
      (destructuring-bind (status headers body) (huge-post nil :path (import-space-action) :content-type "application/zip")
        (ok (= status 413))
        (ok (search "text/html" (getf headers :content-type)) "a form post, so it is HTML")
        (ok (search "limited to 512 MB" (first body)))))))

