(defpackage #:koya-tests/server/http
  (:use #:cl #:rove)
  (:import-from #:koya-server/app #:*app*)
  (:import-from #:koya-server/db/connection #:connect-db #:disconnect-db #:exec)
  (:import-from #:koya-server/db/migrations #:migrate)
  (:import-from #:koya-server/db/schema-store #:save-schema)
  (:import-from #:koya-server/db/api-keys #:create-api-key)
  (:import-from #:koya-server/lib/webhook #:*webhook-sender* #:*webhook-async*)
  (:import-from #:koya/core/schema #:make-field #:make-model #:make-space #:make-schema #:schema->jobject)
  (:import-from #:koya/core/json #:parse-json #:to-json #:jobject #:jget #:json-null)
  (:import-from #:alexandria #:alist-hash-table)
  (:import-from #:babel #:string-to-octets)
  (:import-from #:flexi-streams #:make-in-memory-input-stream))
(in-package #:koya-tests/server/http)

(defparameter *secret* "test-secret")
(defvar *api-key* nil)
(defvar *webhooks* '())

(defun test-schema ()
  (make-schema (list (make-space "website"
                                 :webhooks '("https://example.com/hook")
                                 :models (list (make-model "blog" :list (list (make-field :title :text :required t :unique t)
                                                                              (make-field :body :richtext)
                                                                              (make-field :tags :reference :model "tag" :many t)))
                                               (make-model "tag" :list (list (make-field :name :text :required t)))
                                               (make-model "about" :object (list (make-field :body :richtext))))))))

(setup
  (setf (uiop:getenv "KOYA_SECRET") *secret*)
  (connect-db ":memory:")
  (migrate)
  (save-schema (test-schema))
  (setf *api-key* (create-api-key "website" :label "test"))
  (setf *webhook-async* nil)
  (setf *webhook-sender* (lambda (url payload headers) (push (list url (parse-json payload) headers) *webhooks*))))

(teardown
  (disconnect-db))

(defhook :before
  (exec "DELETE FROM contents")
  (setf *webhooks* '()))

(defun request (method path &key query body headers)
  "Call the app with a synthetic Lack env. Returns (values status parsed-json raw-body)."
  (let* ((env (list :request-method method :script-name "" :path-info path :query-string (or query "")
                    :server-name "localhost" :server-port 3000 :server-protocol :http/1.1
                    :request-uri (format nil "~a~@[?~a~]" path query) :url-scheme "http" :remote-addr "127.0.0.1"
                    :headers (alist-hash-table headers :test 'equal)
                    :content-type nil :content-length nil :raw-body nil)))
    (when body
      (let ((octets (string-to-octets (to-json body) :encoding :utf-8)))
        (setf (getf env :content-type) "application/json"
              (getf env :content-length) (length octets)
              (getf env :raw-body) (make-in-memory-input-stream octets))))
    (destructuring-bind (status response-headers body) (funcall *app* env)
      (declare (ignore response-headers))
      (let ((text (apply #'concatenate 'string (if (listp body) body (list body)))))
        (values status (and (plusp (length text)) (ignore-errors (parse-json text))) text)))))

(defun admin (method path &key body query)
  (request method path :query query :body body
                       :headers `(("authorization" . ,(format nil "Bearer ~a" *secret*)))))

(defun delivery (path &key query (key *api-key*))
  (request :get path :query query :headers (and key `(("x-koya-api-key" . ,key)))))

(defun webhook-types () (mapcar (lambda (w) (jget (second w) "type")) (reverse *webhooks*)))

(deftest admin-auth
  (multiple-value-bind (status json) (request :get "/admin/api/me")
    (ok (= status 401))
    (ok (string= (jget json "error" "code") "unauthorized")))
  (multiple-value-bind (status) (request :get "/admin/api/me" :headers '(("authorization" . "Bearer wrong")))
    (ok (= status 401)))
  (multiple-value-bind (status json) (admin :get "/admin/api/me")
    (ok (= status 200))
    (ok (eq (jget json "owner") t))))

(deftest schema-endpoints
  (multiple-value-bind (status json) (admin :get "/admin/api/schema")
    (ok (= status 200))
    (ok (= (length (jget json "spaces")) 1)))
  (let ((new (make-schema (list (make-space "website" :models (list (make-model "blog" :list (list (make-field :title :text)))))))))
    (multiple-value-bind (status json) (admin :post "/admin/api/schema/plan" :body (schema->jobject new))
      (ok (= status 200))
      (ok (eq (jget json "destructive") t))
      (ok (plusp (length (jget json "changes")))))
    (multiple-value-bind (status json) (admin :put "/admin/api/schema" :body (schema->jobject new))
      (ok (= status 409))
      (ok (string= (jget json "error" "code") "destructive_changes"))
      (ok (plusp (length (jget json "error" "details")))))
    (multiple-value-bind (status json) (admin :get "/admin/api/schema")
      (ok (= status 200))
      (ok (= (length (jget (aref (jget json "spaces") 0) "models")) 3) "not applied")))
  (testing "non-destructive push applies without force"
    (let ((new (make-schema (list (make-space "website"
                                              :webhooks '("https://example.com/hook")
                                              :models (list (make-model "blog" :list (list (make-field :title :text :required t :unique t)
                                                                                           (make-field :body :richtext)
                                                                                           (make-field :tags :reference :model "tag" :many t)
                                                                                           (make-field :extra :text)))
                                                            (make-model "tag" :list (list (make-field :name :text :required t)))
                                                            (make-model "about" :object (list (make-field :body :richtext)))))))))
      (multiple-value-bind (status json) (admin :put "/admin/api/schema" :body (schema->jobject new))
        (ok (= status 200))
        (ok (= (length (jget json "applied")) 1))
        (ok (string= (jget (aref (jget json "applied") 0) "op") "add_field")))
      ;; restore
      (admin :put "/admin/api/schema" :body (schema->jobject (test-schema)) :query "force=true")))
  (testing "invalid schema is a 400"
    (multiple-value-bind (status json) (admin :put "/admin/api/schema" :body (jobject "koyaSchema" 1 "spaces" (vector (jobject "name" "Bad Name"))))
      (ok (= status 400))
      (ok (string= (jget json "error" "code") "invalid_schema"))))
  (testing "malformed JSON is a 400"
    (multiple-value-bind (status json) (request :put "/admin/api/schema" :headers `(("authorization" . ,(format nil "Bearer ~a" *secret*))) :body "not json")
      (ok (= status 400))
      (ok (string= (jget json "error" "code") "bad_json")))))

(deftest content-flow
  (let ((tag-id nil) (post-id nil))
    (testing "create a published tag"
      (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/tag" :body (jobject "data" (jobject "name" "lisp") "publish" t))
        (ok (= status 201))
        (ok (string= (jget json "status") "published"))
        (setf tag-id (jget json "id"))))
    (testing "validation errors are 422 with details"
      (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/blog" :body (jobject "data" (jobject "body" "x")))
        (ok (= status 422))
        (ok (string= (jget json "error" "code") "validation_failed"))
        (ok (string= (jget (aref (jget json "error" "details") 0) "field") "title"))))
    (testing "create a draft post, then publish it"
      (multiple-value-bind (status json)
          (admin :post "/admin/api/contents/website/blog"
                 :body (jobject "data" (jobject "title" "Hello" "body" "# Hi" "tags" (vector tag-id))))
        (ok (= status 201))
        (ok (string= (jget json "status") "draft"))
        (ok (eq (jget json "published") json-null))
        (setf post-id (jget json "id")))
      (multiple-value-bind (status json) (delivery "/api/v1/website/blog")
        (ok (= status 200))
        (ok (= (jget json "totalCount") 0) "drafts are not delivered"))
      (multiple-value-bind (status json) (admin :post (format nil "/admin/api/contents/website/blog/~a/publish" post-id))
        (ok (= status 200))
        (ok (string= (jget json "status") "published"))
        (ok (string= (jget json "published" "body") "# Hi")))
      (ok (equal (webhook-types) '("new" "new")) "tag and post publish fired webhooks")
      (ok (string= (jget (second (first *webhooks*)) "api") "blog"))
      (ok (string= (jget (second (first *webhooks*)) "contents" "new" "title") "Hello"))
      (ok (string= (first (first *webhooks*)) "https://example.com/hook"))
      (ok (= (length (cdr (assoc "X-KOYA-WEBHOOK-KEY" (third (first *webhooks*)) :test #'string=))) 48)
          "webhook carries the space secret"))
    (testing "uniqueness"
      (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/blog" :body (jobject "data" (jobject "title" "Hello")))
        (ok (= status 422))
        (ok (string= (jget (aref (jget json "error" "details") 0) "code") "unique"))))
    (testing "delivery list and item, with reference expansion and fields"
      (multiple-value-bind (status json) (delivery "/api/v1/website/blog")
        (ok (= status 200))
        (ok (= (jget json "totalCount") 1))
        (ok (= (jget json "limit") 10))
        (let ((item (aref (jget json "contents") 0)))
          (ok (string= (jget item "id") post-id))
          (ok (string= (jget item "title") "Hello"))
          (ok (string= (jget (aref (jget item "tags") 0) "name") "lisp") "depth=1 expands references")
          (ok (stringp (jget item "publishedAt")))))
      (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/blog/~a" post-id) :query "fields=id,title&depth=0")
        (ok (= status 200))
        (ok (equal (sort (koya/core/json:jkeys json) #'string<) '("id" "title"))))
      (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/blog/~a" post-id) :query "depth=0")
        (ok (= status 200))
        (ok (string= (aref (jget json "tags") 0) tag-id) "depth=0 keeps ids"))
      (multiple-value-bind (status) (delivery "/api/v1/website/blog" :query "filters=title[equals]Hello")
        (ok (= status 200)))
      (multiple-value-bind (status json) (delivery "/api/v1/website/blog" :query "filters=nope[equals]1")
        (ok (= status 400))
        (ok (string= (jget json "error" "code") "bad_query"))))
    (testing "draft edits and preview with draftKey"
      (multiple-value-bind (status json) (admin :patch (format nil "/admin/api/contents/website/blog/~a" post-id) :body (jobject "data" (jobject "title" "Hello v2")))
        (ok (= status 200))
        (ok (string= (jget json "status") "published+draft"))
        (ok (string= (jget json "draft" "title") "Hello v2"))
        (ok (string= (jget json "draft" "body") "# Hi") "patch merges onto existing data"))
      (multiple-value-bind (status json) (admin :post (format nil "/admin/api/contents/website/blog/~a/draft-key" post-id))
        (ok (= status 200))
        (let ((key (jget json "draftKey")))
          (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/blog/~a" post-id))
            (ok (= status 200))
            (ok (string= (jget json "title") "Hello") "without key: published"))
          (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/blog/~a" post-id) :query (format nil "draftKey=~a" key))
            (ok (= status 200))
            (ok (string= (jget json "title") "Hello v2") "with key: draft"))
          (multiple-value-bind (status) (delivery (format nil "/api/v1/website/blog/~a" post-id) :query "draftKey=wrong")
            (ok (= status 200) "wrong key falls back to published")))))
    (testing "unpublish and delete"
      (multiple-value-bind (status json) (admin :post (format nil "/admin/api/contents/website/blog/~a/unpublish" post-id))
        (ok (= status 200))
        (ok (string= (jget json "status") "draft")))
      (multiple-value-bind (status) (delivery (format nil "/api/v1/website/blog/~a" post-id))
        (ok (= status 404)))
      (multiple-value-bind (status json) (admin :delete (format nil "/admin/api/contents/website/blog/~a" post-id))
        (ok (= status 200))
        (ok (eq (jget json "deleted") t)))
      (multiple-value-bind (status) (admin :get (format nil "/admin/api/contents/website/blog/~a" post-id))
        (ok (= status 404)))
      (ok (equal (webhook-types) '("new" "new" "edit")) "unpublish fires edit; deleting an unpublished draft fires nothing"))))

(deftest delete-published-webhook
  (let ((post-id nil))
    (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/blog" :body (jobject "data" (jobject "title" "Bye") "publish" t))
      (ok (= status 201))
      (setf post-id (jget json "id")))
    (multiple-value-bind (status json) (admin :delete (format nil "/admin/api/contents/website/blog/~a" post-id))
      (ok (= status 200))
      (ok (eq (jget json "deleted") t)))
    (ok (equal (webhook-types) '("new" "delete")))
    (let ((hook (first *webhooks*)))
      (ok (string= (jget (second hook) "id") post-id))
      (ok (string= (jget (second hook) "contents" "old" "title") "Bye"))
      (ok (eq (jget (second hook) "contents" "new") json-null))
      (ok (= (length (cdr (assoc "X-KOYA-WEBHOOK-KEY" (third hook) :test #'string=))) 48)
          "delete webhook carries the space secret"))))

(deftest import-style-create
  (testing "explicit id and publishedAt"
    (multiple-value-bind (status json)
        (admin :post "/admin/api/contents/website/tag"
               :body (jobject "data" (jobject "name" "old") "publish" t "id" "hg2papkhis4" "publishedAt" "2025-04-30T15:00:00.000Z"))
      (ok (= status 201))
      (ok (string= (jget json "id") "hg2papkhis4"))
      (ok (string= (jget json "publishedAt") "2025-04-30T15:00:00.000Z")))
    (multiple-value-bind (status json) (delivery "/api/v1/website/tag/hg2papkhis4")
      (ok (= status 200))
      (ok (string= (jget json "publishedAt") "2025-04-30T15:00:00.000Z")))
    (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/tag" :body (jobject "data" (jobject "name" "dup") "id" "hg2papkhis4"))
      (ok (= status 409))
      (ok (string= (jget json "error" "code") "conflict")))
    (multiple-value-bind (status) (admin :post "/admin/api/contents/website/tag" :body (jobject "data" (jobject "name" "x") "id" "bad id!"))
      (ok (= status 400)))
    (multiple-value-bind (status) (admin :post "/admin/api/contents/website/tag" :body (jobject "data" (jobject "name" "x") "publish" t "publishedAt" "yesterday"))
      (ok (= status 400))))
  (testing "publish with publishedAt override"
    (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/tag" :body (jobject "data" (jobject "name" "later")))
      (ok (= status 201))
      (multiple-value-bind (status json) (admin :post (format nil "/admin/api/contents/website/tag/~a/publish" (jget json "id"))
                                                :body (jobject "publishedAt" "2024-01-01T00:00:00.000Z"))
        (ok (= status 200))
        (ok (string= (jget json "publishedAt") "2024-01-01T00:00:00.000Z"))))))

(deftest object-model
  (multiple-value-bind (status) (delivery "/api/v1/website/about")
    (ok (= status 404) "nothing yet"))
  (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/about" :body (jobject "data" (jobject "body" "about me") "publish" t))
    (ok (= status 201))
    (ok (string= (jget json "status") "published")))
  (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/about" :body (jobject "data" (jobject "body" "about me v2") "publish" t))
    (ok (= status 201))
    (ok (string= (jget json "published" "body") "about me v2") "object models upsert"))
  (multiple-value-bind (status json) (delivery "/api/v1/website/about")
    (ok (= status 200))
    (ok (string= (jget json "body") "about me v2")))
  (multiple-value-bind (status json) (admin :get "/admin/api/contents/website/about")
    (ok (= status 200))
    (ok (= (jget json "totalCount") 1))))

(deftest delivery-auth
  (multiple-value-bind (status json) (delivery "/api/v1/website/blog" :key nil)
    (ok (= status 401))
    (ok (string= (jget json "error" "code") "unauthorized")))
  (multiple-value-bind (status) (delivery "/api/v1/website/blog" :key "koya_wrong")
    (ok (= status 401)))
  (multiple-value-bind (status) (request :get "/api/v1/website/blog" :headers `(("x-microcms-api-key" . ,*api-key*)))
    (ok (= status 200) "microCMS header name is accepted"))
  (save-schema (make-schema (list (make-space "website" :webhooks '("https://example.com/hook")
                                              :models (list (make-model "blog" :list (list (make-field :title :text :required t :unique t)
                                                                                           (make-field :body :richtext)
                                                                                           (make-field :tags :reference :model "tag" :many t)))
                                                            (make-model "tag" :list (list (make-field :name :text :required t)))
                                                            (make-model "about" :object (list (make-field :body :richtext)))))
                                  (make-space "other"))))
  (multiple-value-bind (status json) (delivery "/api/v1/other/blog")
    (ok (= status 403))
    (ok (string= (jget json "error" "code") "forbidden")))
  (multiple-value-bind (status json) (delivery "/api/v1/website/nope")
    (ok (= status 404))
    (ok (string= (jget json "error" "code") "not_found")))
  (multiple-value-bind (status json) (request :get "/api/nothing/here")
    (ok (= status 404))
    (ok (string= (jget json "error" "code") "not_found"))))

(deftest api-keys
  (multiple-value-bind (status json) (admin :post "/admin/api/keys/website" :body (jobject "label" "second"))
    (ok (= status 201))
    (let ((key (jget json "key")) (id (jget json "id")))
      (ok (string= (subseq key 0 5) "koya_"))
      (multiple-value-bind (status) (delivery "/api/v1/website/blog" :key key)
        (ok (= status 200)))
      (multiple-value-bind (status json) (admin :get "/admin/api/keys/website")
        (ok (= status 200))
        (ok (= (length (jget json "keys")) 2))
        (ok (every (lambda (k) (null (jget k "key"))) (jget json "keys")) "plaintext never listed")
        (ok (= (length (jget json "webhookSecret")) 48)))
      (multiple-value-bind (status) (admin :delete (format nil "/admin/api/keys/website/~a" id))
        (ok (= status 200)))
      (multiple-value-bind (status) (delivery "/api/v1/website/blog" :key key)
        (ok (= status 401)))))
  (multiple-value-bind (status) (admin :get "/admin/api/keys/nope")
    (ok (= status 404))))
