(defpackage #:koya-tests/server/ui
  (:use #:cl #:rove)
  (:import-from #:koya-server/app #:*app*)
  (:import-from #:koya-server/db/connection #:connect-db #:disconnect-db #:exec)
  (:import-from #:koya-server/db/migrations #:migrate)
  (:import-from #:koya-server/db/schema-store #:save-schema)
  (:import-from #:koya-server/db/contents #:list-contents #:content-status #:content-published #:content-draft #:content-id)
  (:import-from #:koya-server/lib/query #:parse-query)
  (:import-from #:koya-server/lib/webhook #:*webhook-sender* #:*webhook-async*)
  (:import-from #:koya-server/lib/forms #:slugify #:normalize-richtext)
  (:import-from #:koya/core/schema #:make-field #:make-model #:make-space #:make-schema)
  (:import-from #:koya/core/json #:jget)
  (:import-from #:alexandria #:alist-hash-table)
  (:import-from #:babel #:string-to-octets)
  (:import-from #:flexi-streams #:make-in-memory-input-stream)
  (:import-from #:quri #:url-encode-params))
(in-package #:koya-tests/server/ui)

(defparameter *secret* "ui-secret")
(defvar *cookie* nil)

(defun blog-model ()
  (make-model "blog" :list (list (make-field :title :text :required t)
                                 (make-field :slug :slug :from :title :unique t)
                                 (make-field :body :richtext)
                                 (make-field :featured :boolean)
                                 (make-field :category :select :options '("news" "tech"))
                                 (make-field :labels :select :options '("a" "b") :many t)
                                 (make-field :count :number)
                                 (make-field :when :datetime)
                                 (make-field :related :reference :model "blog" :many t))
              :preview-url "https://site.test/blog/{CONTENT_ID}?draft-key={DRAFT_KEY}"
              :public-url "https://site.test/blog/{CONTENT_ID}"))

(setup
  (setf (uiop:getenv "KOYA_SECRET") *secret*)
  (setf *webhook-async* nil)
  (setf *webhook-sender* (lambda (url payload headers) (declare (ignore url payload headers))))
  (connect-db ":memory:")
  (migrate)
  (save-schema (make-schema (list (make-space "website" :models (list (blog-model)
                                                                      (make-model "about" :object (list (make-field :body :richtext)))))))))

(teardown (disconnect-db))

(defun request (method path &key form headers query)
  "Returns (values status body-string headers-plist)."
  (let* ((env (list :request-method method :script-name "" :path-info path :query-string (or query "")
                    :server-name "localhost" :server-port 3000 :server-protocol :http/1.1
                    :request-uri path :url-scheme "http" :remote-addr "127.0.0.1"
                    :headers (alist-hash-table (append headers (and *cookie* (list (cons "cookie" *cookie*)))
                                                       (list (cons "host" "localhost:3000")))
                                               :test 'equal)
                    :content-type nil :content-length nil :raw-body nil)))
    (when form
      (let ((octets (string-to-octets (url-encode-params form) :encoding :utf-8)))
        (setf (getf env :content-type) "application/x-www-form-urlencoded"
              (getf env :content-length) (length octets)
              (getf env :raw-body) (make-in-memory-input-stream octets))))
    (destructuring-bind (status response-headers body) (funcall *app* env)
      (let ((set-cookie (getf response-headers :set-cookie)))
        (when set-cookie
          (setf *cookie* (subseq set-cookie 0 (position #\; set-cookie)))))
      (values status (apply #'concatenate 'string (if (listp body) body (list body))) response-headers))))

(defun location (headers) (getf headers :location))

(deftest health
  (let ((*cookie* nil))
    (multiple-value-bind (status body) (request :get "/health")
      (ok (= status 200))
      (ok (search "ok" body)))))

(deftest login-flow
  (setf *cookie* nil)
  (multiple-value-bind (status body headers) (request :get "/")
    (declare (ignore body))
    (ok (= status 302))
    (ok (string= (location headers) "/login")))
  (multiple-value-bind (status body) (request :get "/login")
    (ok (= status 200))
    (ok (search "Owner secret" body)))
  (multiple-value-bind (status body) (request :post "/login" :form '(("secret" . "nope")))
    (ok (= status 401))
    (ok (search "Wrong secret" body)))
  (multiple-value-bind (status body headers) (request :post "/login" :form `(("secret" . ,*secret*)))
    (declare (ignore body))
    (ok (= status 303))
    (ok (string= (location headers) "/"))
    (ok *cookie* "session cookie set"))
  (multiple-value-bind (status body) (request :get "/")
    (ok (= status 200))
    (ok (search "website" body) "space listed"))
  (testing "cross-origin posts are rejected"
    (multiple-value-bind (status) (request :post "/logout" :headers '(("origin" . "https://evil.example")))
      (ok (= status 403)))
    (multiple-value-bind (status) (request :post "/s/website/keys" :form '(("action" . "create")) :headers '(("origin" . "https://evil.example")))
      (ok (= status 403)))
    (multiple-value-bind (status) (request :post "/logout" :headers '(("origin" . "null")))
      (ok (= status 403) "an opaque origin is not 'no origin'")))
  (testing "same-origin post is fine"
    (multiple-value-bind (status body) (request :post "/s/website/keys" :form '(("action" . "create") ("label" . "ui"))
                                                :headers '(("origin" . "http://localhost:3000")))
      (ok (= status 200))
      (ok (search "koya_" body) "new key shown once")
      (ok (search "Webhook secret" body)))))

(deftest pages
  (multiple-value-bind (status body) (request :get "/s/website")
    (ok (= status 200))
    (ok (search "blog" body))
    (ok (search "about" body)))
  (multiple-value-bind (status body) (request :get "/s/website/m/blog")
    (ok (= status 200))
    (ok (search "New content" body)))
  (multiple-value-bind (status body headers) (request :get "/s/website/m/about")
    (declare (ignore body))
    (ok (= status 302))
    (ok (string= (location headers) "/s/website/m/about/new") "object model goes straight to its editor"))
  (multiple-value-bind (status body) (request :get "/s/website/m/blog/new")
    (ok (= status 200))
    (ok (search "name=\"f-title\"" body))
    (ok (search "name=\"f-body\"" body))
    (ok (search "type=\"checkbox\"" body))
    (ok (search "datetime-local" body))
    (ok (search "data-quill-for=\"f-body\"" body) "rich text gets a Quill holder")
    (ok (search "data-editor-form" body)))
  (multiple-value-bind (status) (request :get "/s/nope")
    (ok (= status 404)))
  (multiple-value-bind (status) (request :get "/s/website/m/nope")
    (ok (= status 404)))
  (multiple-value-bind (status) (request :get "/s/website/m/blog/01ARZ3NDEKTSV4RRFFQ69G5FAV")
    (ok (= status 404))))

(deftest editor-flow
  (exec "DELETE FROM contents")
  (testing "validation errors re-render the form"
    (multiple-value-bind (status body) (request :post "/s/website/m/blog/new" :form '(("action" . "save") ("f-body" . "x")))
      (ok (= status 422))
      (ok (search "is required" body))
      (ng (search "NIL" body))))
  (testing "an empty Quill document counts as blank"
    (multiple-value-bind (status body headers)
        (request :post "/s/website/m/blog/new" :form '(("action" . "save") ("f-title" . "Blank body") ("f-body" . "<p><br></p>")))
      (declare (ignore body))
      (ok (= status 303))
      (let* ((loc (location headers)) (id (subseq loc (1+ (position #\/ loc :from-end t)))))
        (ok (null (jget (content-draft (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))) "body")))
        (request :post (format nil "/s/website/m/blog/~a" id) :form '(("action" . "delete"))))))
  (let ((id nil))
    (testing "save a draft"
      (multiple-value-bind (status body headers)
          (request :post "/s/website/m/blog/new"
                   :form '(("action" . "save") ("f-title" . "Hello World") ("f-body" . "# Hi")
                           ("f-featured" . "on") ("f-category" . "tech") ("f-labels" . "a") ("f-labels" . "b")
                           ("f-count" . "2.5") ("f-when" . "2026-09-20T10:00")
                           ("f-related" . "x1") ("f-related" . "x2")))
        (declare (ignore body))
        (ok (= status 303))
        (let* ((loc (location headers))
               (path (subseq loc 0 (position #\? loc))))
          (setf id (subseq path (1+ (position #\/ path :from-end t))))
          (ok (= (length id) 26))))
      (let ((content (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
        (ok (string= (content-status content) "draft"))
        (let ((draft (content-draft content)))
          (ok (string= (jget draft "slug") "hello-world") "slug generated from title")
          (ok (eq (jget draft "featured") t))
          (ok (equalp (jget draft "labels") #("a" "b")))
          (ok (= (jget draft "count") 2.5))
          (ok (string= (jget draft "when") "2026-09-20T10:00:00Z"))
          (ok (equalp (jget draft "related") #("x1" "x2")) "a multiple select repeats the name"))))
    (testing "editor shows the draft and the flash exactly once"
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ok (search "value=\"Hello World\"" body))
        (ok (search "value=\"hello-world\"" body))
        (ok (search "checked" body))
        (ok (search "value=\"2026-09-20T10:00\"" body))
        (ok (search "value=\"2.5\"" body) "floats render without an exponent marker")
        (ok (search "<select id=\"f-related\" name=\"f-related\" multiple" body)
            "reference is a multiple select")
        (ok (search "value=\"x1\" selected" body) "selected ids not in the target model are kept")
        (ok (search (format nil "value=\"~a\"" id) body) "existing contents are offered")
        (ok (search "Draft saved" body))
        (ng (search "NIL" body) "no stray NILs in the page"))
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ng (search "Draft saved" body) "flash is gone on the next request")))
    (testing "list shows field previews and status, newest first"
      (request :post "/s/website/m/blog/new"
               :form `(("action" . "save") ("f-title" . "Second post") ("f-body" . "<p>Rich <b>text</b> &amp; more</p>")
                       ("f-related" . ,id) ("f-related" . "x2")))
      (multiple-value-bind (status body) (request :get "/s/website/m/blog")
        (ok (= status 200))
        (ok (search "Hello World" body))
        (ok (< (search "Second post" body) (search "Hello World" body)) "newest created first")
        (ok (search "Rich text &amp; more" body) "rich text is previewed as plain text")
        (ok (not (search "<b>text</b>" body)))
        (ok (search "2026-09-20 10:00 UTC" body) "datetime preview")
        (ok (search ">Yes<" body) "boolean preview")
        (ok (search ">a, b<" body) "multi select preview")
        (ok (search ">2.5<" body) "number preview")
        (ok (search ">draft<" body))
        (ok (search "data-href=\"/s/website/m/blog/" body) "rows link to the editor")
        (ok (search "Hello World, x2" body) "a reference previews as the target's label, unknown ids stay ids")
        (ok (not (search "<a href=\"/s/website/m/blog/0" body)) "no title link")
        (ok (not (search "Created at" body)))
        (ok (not (search "Updated at" body))))
      (let ((second (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
        (request :post (format nil "/s/website/m/blog/~a" (content-id second)) :form '(("action" . "delete")))))
    (testing "publish, unpublish, delete"
      (multiple-value-bind (status body headers)
          (request :post (format nil "/s/website/m/blog/~a" id)
                   :form '(("action" . "publish") ("f-title" . "Hello World") ("f-slug" . "hello-world") ("f-body" . "# Hi")))
        (declare (ignore body))
        (ok (= status 303))
        (ok (string= (location headers) (format nil "/s/website/m/blog/~a" id)) "redirects back without query noise"))
      (let ((content (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
        (ok (string= (content-status content) "published"))
        (ok (null (jget (content-published content) "featured")) "unchecked box stored as false"))
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ok (search "Published." body) "flash after publish")
        (ok (search "Published page" body) "published + public template gives a page link")
        (ng (search "Preview draft" body) "no draft, no preview link"))
      (multiple-value-bind (status) (request :post (format nil "/s/website/m/blog/~a" id) :form '(("action" . "unpublish")))
        (ok (= status 303)))
      (ok (string= (content-status (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))) "draft"))
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ok (search "Preview draft" body) "draft + preview template gives a preview link")
        (ok (search "https://site.test/blog/" body))
        (ng (search "Published page" body)))
      (multiple-value-bind (status body headers) (request :post (format nil "/s/website/m/blog/~a" id) :form '(("action" . "delete")))
        (declare (ignore body))
        (ok (= status 303))
        (ok (string= (location headers) "/s/website/m/blog")))
      (ok (null (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all)))))
  (testing "object model editor upserts"
    (multiple-value-bind (status body headers) (request :post "/s/website/m/about/new" :form '(("action" . "publish") ("f-body" . "about")))
      (declare (ignore body))
      (ok (= status 303))
      (ok (search "/s/website/m/about/" (location headers))))
    (multiple-value-bind (status body headers) (request :get "/s/website/m/about")
      (declare (ignore body))
      (ok (= status 302))
      (ng (search "/new" (location headers)) "now redirects to the existing content"))))

(deftest normalize-richtext-test
  (ok (string= (normalize-richtext "<p>a</p><p></p><h2>b</h2><ul><li>x</li><li>y</li></ul><hr><p>c<br>d</p>")
               "<p>a</p>
<p><br></p>
<h2>b</h2>
<ul><li>x</li>
<li>y</li>
</ul>
<hr>
<p>c<br>d</p>"))
  (ok (string= (normalize-richtext "<p>x</p>
") "<p>x</p>") "already formatted input is left alone apart from trailing whitespace")
  (ok (string= (normalize-richtext "<p>a&nbsp;b</p>") "<p>a&nbsp;b</p>") "entities are not touched server-side"))

(deftest slugify-test
  (ok (string= (slugify "Hello, World!") "hello-world"))
  (ok (string= (slugify "  Common  Lisp 2026 ") "common-lisp-2026"))
  (ok (string= (slugify "日本語") "") "non-ascii yields empty; validation then reports it"))
