(defpackage #:koya-tests/server/ui
  (:use #:cl #:rove)
  (:import-from #:koya-server/app #:*app*)
  (:import-from #:koya-server/db/connection #:connect-db #:disconnect-db #:exec #:fetch-one #:col)
  (:import-from #:koya-server/db/migrations #:migrate)
  (:import-from #:koya-server/db/schema-store #:save-schema)
  (:import-from #:koya-server/db/contents #:list-contents #:content-status #:content-published #:content-draft #:content-id)
  (:import-from #:koya-server/db/api-keys #:list-api-keys)
  (:import-from #:koya-server/db/media #:list-media #:media-id)
  (:import-from #:koya-server/actions/media-picker #:media-picker)
  (:import-from #:koya-tests/server/media #:png-bytes #:*media-root* #:multipart-body)
  (:import-from #:koya-server/lib/totp #:totp #:*totp-last-counter* #:totp-enabled-p)
  (:import-from #:koya-server/lib/timezone #:display-timezone-name #:find-timezone)
  (:import-from #:koya-server/lib/auth #:clear-login-failures)
  (:import-from #:cl-ppcre #:scan-to-strings)
  (:import-from #:koya-server/lib/query #:parse-query)
  (:import-from #:koya-server/lib/webhook #:*webhook-sender* #:*webhook-async*)
  (:import-from #:koya-server/db/webhook-deliveries #:record-delivery)
  (:import-from #:koya/core/schema #:make-webhook)
  (:import-from #:koya-server/lib/forms #:slugify #:normalize-richtext)
  (:import-from #:koya/core/schema #:make-field #:make-model #:make-space #:make-schema)
  (:import-from #:koya/core/json #:jget)
  (:import-from #:alexandria #:alist-hash-table)
  (:import-from #:babel #:string-to-octets)
  (:import-from #:flexi-streams #:make-in-memory-input-stream)
  (:import-from #:quri #:url-encode-params))
(in-package #:koya-tests/server/ui)

(defparameter *secret* "ui-secret")
(defvar *cookie* nil)
(defvar *set-cookie* nil "The last Set-Cookie header seen, flags included.")

(defun blog-model ()
  (make-model "blog" :list (list (make-field :title :text :required t)
                                 (make-field :slug :slug :from :title :unique t)
                                 (make-field :body :richtext)
                                 (make-field :featured :boolean)
                                 (make-field :category :select :options '("news" "tech"))
                                 (make-field :labels :select :options '("a" "b") :many t)
                                 (make-field :count :number)
                                 (make-field :when :datetime)
                                 (make-field :cover :media)
                                 (make-field :related :reference :model "blog" :many t))
              :preview-url "https://site.test/blog/{CONTENT_ID}?draft-key={DRAFT_KEY}"
              :public-url "https://site.test/blog/{CONTENT_ID}"))

(setup
  (setf (uiop:getenv "KOYA_SECRET") *secret*)
  (setf (uiop:getenv "KOYA_BASE_URL") "http://localhost:3000")
  (setf (uiop:getenv "KOYA_MEDIA_DIR") (namestring *media-root*))
  (setf *webhook-async* nil)
  (setf *webhook-sender* (lambda (url payload headers) (declare (ignore url payload headers))))
  (connect-db ":memory:")
  (migrate)
  (save-schema (make-schema (list (make-space "website" :models (list (blog-model)
                                                                      (make-model "about" :object (list (make-field :body :richtext)))))))))

(teardown (disconnect-db))

(defun request (method path &key form multipart headers query)
  "Returns (values status body-string headers-plist). FORM is urlencoded; MULTIPART
is a list of parts for MULTIPART-BODY."
  (let* ((env (list :request-method method :script-name "" :path-info path :query-string (or query "")
                    :server-name "localhost" :server-port 3000 :server-protocol :http/1.1
                    :request-uri path :url-scheme "http" :remote-addr "127.0.0.1"
                    :headers (alist-hash-table (append headers (and *cookie* (list (cons "cookie" *cookie*)))
                                                       (list (cons "host" "localhost:3000")))
                                               :test 'equal)
                    :content-type nil :content-length nil :raw-body nil)))
    (when form
      (let ((octets (string-to-octets (url-encode-params form) :encoding :utf-8)))
        (setf (getf env :content-type) "application/x-www-form-urlencoded"
              (getf env :content-length) (length octets)
              (getf env :raw-body) (make-in-memory-input-stream octets))))
    (when multipart
      (multiple-value-bind (octets content-type) (multipart-body multipart)
        (setf (getf env :content-type) content-type
              (getf env :content-length) (length octets)
              (getf env :raw-body) (make-in-memory-input-stream octets))))
    (destructuring-bind (status response-headers body) (funcall *app* env)
      (let ((set-cookie (getf response-headers :set-cookie)))
        (when set-cookie
          (setf *set-cookie* set-cookie
                *cookie* (subseq set-cookie 0 (position #\; set-cookie)))))
      (values status
              (if (pathnamep body) "" (apply #'concatenate 'string (if (listp body) body (list body))))
              response-headers))))

(defun location (headers) (getf headers :location))

(defun request-url (method url &rest args)
  "REQUEST with a URL that may carry a query string, e.g. an action endpoint."
  (let ((q (position #\? url)))
    (apply #'request method (subseq url 0 q) :query (and q (subseq url (1+ q))) args)))

(deftest health
  (let ((*cookie* nil))
    (multiple-value-bind (status body) (request :get "/health")
      (ok (= status 200))
      (ok (search "ok" body)))))

(deftest login-flow
  (setf *cookie* nil)
  (multiple-value-bind (status body headers) (request :get "/")
    (declare (ignore body))
    (ok (= status 302))
    (ok (string= (location headers) "/login")))
  (multiple-value-bind (status body) (request :get "/login")
    (ok (= status 200))
    (ok (search "Owner secret" body)))
  (multiple-value-bind (status body) (request :post "/login" :form '(("secret" . "nope")))
    (ok (= status 401))
    (ok (search "Wrong secret" body)))
  (multiple-value-bind (status body headers) (request :post "/login" :form `(("secret" . ,*secret*)))
    (declare (ignore body))
    (ok (= status 303))
    (ok (string= (location headers) "/"))
    (ok *cookie* "session cookie set")
    (ok (search "HttpOnly" *set-cookie*) "cookie is HttpOnly")
    (ok (search "SameSite=Lax" *set-cookie*) "cookie is SameSite=Lax")
    (ok (col (fetch-one "SELECT count(*) AS n FROM sessions") "n")
        "the session is in the database, not only in the process"))
  (multiple-value-bind (status body) (request :get "/")
    (ok (= status 200))
    (ok (search "website" body) "space listed"))
  (testing "two-factor login when KOYA_TOTP_SECRET is set"
    (let ((secret "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ"))
      (setf (uiop:getenv "KOYA_TOTP_SECRET") secret
            *totp-last-counter* -1)
      (unwind-protect
           (let ((*cookie* nil))
             (multiple-value-bind (status body) (request :get "/login")
               (ok (= status 200))
               (ok (search "One-time code" body) "the form asks for a code"))
             (multiple-value-bind (status body) (request :post "/login" :form `(("secret" . ,*secret*)))
               (ok (= status 401))
               (ok (search "one-time code" body) "secret alone is not enough"))
             (multiple-value-bind (status body) (request :post "/login" :form `(("secret" . "nope") ("code" . ,(totp secret))))
               (ok (= status 401))
               (ok (search "Wrong secret" body) "a wrong secret is reported as such, and does not consume the code"))
             (let ((code (totp secret)))
               (multiple-value-bind (status body headers) (request :post "/login" :form `(("secret" . ,*secret*) ("code" . ,code)))
                 (declare (ignore body))
                 (ok (= status 303))
                 (ok (string= (location headers) "/")))
               (let ((*cookie* nil))
                 (multiple-value-bind (status body) (request :post "/login" :form `(("secret" . ,*secret*) ("code" . ,code)))
                   (ok (= status 401))
                   (ok (search "one-time code" body) "the same code cannot log in twice")))))
        (setf (uiop:getenv "KOYA_TOTP_SECRET") ""))))
  (testing "cross-origin posts are rejected"
    (multiple-value-bind (status) (request :post "/logout" :headers '(("origin" . "https://evil.example")))
      (ok (= status 403)))
    (multiple-value-bind (status) (request :post "/s/website/keys" :form '(("action" . "create")) :headers '(("origin" . "https://evil.example")))
      (ok (= status 403)))
    (multiple-value-bind (status) (request :post "/logout" :headers '(("origin" . "null")))
      (ok (= status 403) "an opaque origin is not 'no origin'")))
  (testing "same-origin post is fine"
    (multiple-value-bind (status body) (request :post "/s/website/keys" :form '(("action" . "create") ("label" . "ui"))
                                                :headers '(("origin" . "http://localhost:3000")))
      (ok (= status 200))
      (ok (search "koya_" body) "new key shown once")
      (ok (search "Webhook secret" body))))
  (testing "delete and rotate redirect instead of re-rendering"
    (let ((id (getf (first (list-api-keys "website")) :id)))
      (multiple-value-bind (status body headers)
          (request :post "/s/website/keys" :form `(("action" . "delete") ("id" . ,id)) :headers '(("origin" . "http://localhost:3000")))
        (declare (ignore body))
        (ok (= status 303))
        (ok (string= (location headers) "/s/website/keys")))
      (multiple-value-bind (status body) (request :get "/s/website/keys")
        (ok (= status 200))
        (ok (search "Key deleted." body) "flash shown after the redirect")))
    (multiple-value-bind (status body headers)
        (request :post "/s/website/keys" :form '(("action" . "rotate-webhook-secret")) :headers '(("origin" . "http://localhost:3000")))
      (declare (ignore body))
      (ok (= status 303))
      (ok (string= (location headers) "/s/website/keys")))))

(deftest pages
  (multiple-value-bind (status body) (request :get "/s/website")
    (ok (= status 200))
    (ok (search "blog" body))
    (ok (search "about" body)))
  (multiple-value-bind (status body) (request :get "/s/website/m/blog")
    (ok (= status 200))
    (ok (search "New content" body)))
  (multiple-value-bind (status body headers) (request :get "/s/website/m/about")
    (declare (ignore body))
    (ok (= status 302))
    (ok (string= (location headers) "/s/website/m/about/new") "object model goes straight to its editor"))
  (multiple-value-bind (status body) (request :get "/s/website/m/blog/new")
    (ok (= status 200))
    (ok (search "name=\"f-title\"" body))
    (ok (search "name=\"f-body\"" body))
    (ok (search "type=\"checkbox\"" body))
    (ok (search "datetime-local" body))
    (ok (search "data-quill-for=\"f-body\"" body) "rich text gets a Quill holder")
    (ok (search "data-editor-form" body)))
  (multiple-value-bind (status) (request :get "/s/nope")
    (ok (= status 404)))
  (multiple-value-bind (status) (request :post "/s/website/m/blog/new" :form '(("action" . "delete")))
    (ok (= status 404) "delete on /new has nothing to delete"))
  (multiple-value-bind (status) (request :post "/s/website/m/blog/new" :form '(("action" . "unpublish")))
    (ok (= status 404)))
  (multiple-value-bind (status) (request :get "/s/website/m/nope")
    (ok (= status 404)))
  (multiple-value-bind (status) (request :get "/s/website/m/blog/01ARZ3NDEKTSV4RRFFQ69G5FAV")
    (ok (= status 404))))

(deftest editor-flow
  (exec "DELETE FROM contents")
  (testing "validation errors re-render the form"
    (multiple-value-bind (status body) (request :post "/s/website/m/blog/new" :form '(("action" . "save") ("f-body" . "x")))
      (ok (= status 422))
      (ok (search "is required" body))
      (ng (search "NIL" body))))
  (testing "an empty Quill document counts as blank"
    (multiple-value-bind (status body headers)
        (request :post "/s/website/m/blog/new" :form '(("action" . "save") ("f-title" . "Blank body") ("f-body" . "<p><br></p>")))
      (declare (ignore body))
      (ok (= status 303))
      (let* ((loc (location headers)) (id (subseq loc (1+ (position #\/ loc :from-end t)))))
        (ok (null (jget (content-draft (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))) "body")))
        (request :post (format nil "/s/website/m/blog/~a" id) :form '(("action" . "delete"))))))
  (let ((id nil))
    (testing "save a draft"
      (multiple-value-bind (status body headers)
          (request :post "/s/website/m/blog/new"
                   :form '(("action" . "save") ("f-title" . "Hello World") ("f-body" . "# Hi")
                           ("f-featured" . "on") ("f-category" . "tech") ("f-labels" . "a") ("f-labels" . "b")
                           ("f-count" . "2.5") ("f-when" . "2026-09-20T10:00")
                           ("f-related" . "x1") ("f-related" . "x2")))
        (declare (ignore body))
        (ok (= status 303))
        (let* ((loc (location headers))
               (path (subseq loc 0 (position #\? loc))))
          (setf id (subseq path (1+ (position #\/ path :from-end t))))
          (ok (= (length id) 26))))
      (let ((content (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
        (ok (string= (content-status content) "draft"))
        (let ((draft (content-draft content)))
          (ok (string= (jget draft "slug") "hello-world") "slug generated from title")
          (ok (eq (jget draft "featured") t))
          (ok (equalp (jget draft "labels") #("a" "b")))
          (ok (= (jget draft "count") 2.5))
          (ok (string= (jget draft "when") "2026-09-20T10:00:00.000Z") "datetime-local value stored as UTC in the canonical form")
          (ok (equalp (jget draft "related") #("x1" "x2")) "a multiple select repeats the name"))))
    (testing "editor shows the draft and the flash exactly once"
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ok (search "value=\"Hello World\"" body))
        (ok (search "value=\"hello-world\"" body))
        (ok (search "checked" body))
        (ok (search "value=\"2026-09-20T10:00\"" body))
        (ok (search "value=\"2.5\"" body) "floats render without an exponent marker")
        (ok (search "<select id=\"f-related\" name=\"f-related\" multiple" body)
            "reference is a multiple select")
        (ok (search "value=\"x1\" selected" body) "selected ids not in the target model are kept")
        (ok (search (format nil "value=\"~a\"" id) body) "existing contents are offered")
        (ok (search "Draft saved" body))
        (ng (search "NIL" body) "no stray NILs in the page"))
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ng (search "Draft saved" body) "flash is gone on the next request")))
    (testing "text with a literal entity survives the editor"
      (multiple-value-bind (status body headers)
          (request :post "/s/website/m/blog/new"
                   :form '(("action" . "save") ("f-title" . "AT&amp;T <b>") ("f-body" . "<p>x</p>")))
        (declare (ignore body))
        (ok (= status 303))
        (let ((path (subseq (location headers) 0 (position #\? (location headers)))))
          (multiple-value-bind (status body) (request :get path)
            (ok (= status 200))
            (ok (search "value=\"AT&amp;amp;T <b>\"" body) "the attribute encodes & so the browser shows AT&amp;T"))
          (request :post path :form '(("action" . "delete"))))))
    (testing "list shows field previews and status, newest first"
      (request :post "/s/website/m/blog/new"
               :form `(("action" . "save") ("f-title" . "Second post") ("f-body" . "<p>Rich <b>text</b> &amp; more</p>")
                       ("f-related" . ,id) ("f-related" . "x2")))
      (multiple-value-bind (status body) (request :get "/s/website/m/blog")
        (ok (= status 200))
        (ok (search "Hello World" body))
        (ok (< (search "Second post" body) (search "Hello World" body)) "newest created first")
        (ok (search "Rich text &amp; more" body) "rich text is previewed as plain text")
        (ok (not (search "<b>text</b>" body)))
        (ok (search "2026-09-20 10:00 UTC" body) "datetime preview")
        (ok (search ">Yes<" body) "boolean preview")
        (ok (search ">a, b<" body) "multi select preview")
        (ok (search ">2.5<" body) "number preview")
        (ok (search ">draft<" body))
        (ok (search "data-href=\"/s/website/m/blog/" body) "rows link to the editor")
        (ok (search "Hello World, x2" body) "a reference previews as the target's label, unknown ids stay ids")
        (ok (not (search "<a href=\"/s/website/m/blog/0" body)) "no title link")
        (ok (not (search "Created at" body)))
        (ok (not (search "Updated at" body))))
      (let ((second (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
        (request :post (format nil "/s/website/m/blog/~a" (content-id second)) :form '(("action" . "delete")))))
    (testing "discard a draft"
      (let ((origin '(("origin" . "http://localhost:3000"))))
        (request :post (format nil "/s/website/m/blog/~a" id) :form '(("action" . "publish") ("f-title" . "Hello World") ("f-body" . "<p>x</p>")) :headers origin)
        (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
          (ok (= status 200))
          (ok (not (search "Discard draft" body)) "no draft, no button"))
        (request :post (format nil "/s/website/m/blog/~a" id) :form '(("action" . "save") ("f-title" . "Edited") ("f-body" . "<p>x</p>")) :headers origin)
        (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
          (ok (= status 200))
          (ok (search "Discard draft" body))
          (ok (search "value=\"Edited\"" body)))
        (multiple-value-bind (status body headers) (request :post (format nil "/s/website/m/blog/~a" id) :form '(("action" . "discard")) :headers origin)
          (declare (ignore body))
          (ok (= status 303))
          (ok (string= (location headers) (format nil "/s/website/m/blog/~a" id))))
        (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
          (ok (= status 200))
          (ok (search "Draft discarded." body))
          (ok (search "value=\"Hello World\"" body) "editor shows the published data again")
          (ok (not (search "Discard draft" body))))
        (request :post (format nil "/s/website/m/blog/~a" id) :form '(("action" . "unpublish")) :headers origin)))
    (testing "publish, unpublish, delete"
      (multiple-value-bind (status body headers)
          (request :post (format nil "/s/website/m/blog/~a" id)
                   :form '(("action" . "publish") ("f-title" . "Hello World") ("f-slug" . "hello-world") ("f-body" . "# Hi")))
        (declare (ignore body))
        (ok (= status 303))
        (ok (string= (location headers) (format nil "/s/website/m/blog/~a" id)) "redirects back without query noise"))
      (let ((content (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
        (ok (string= (content-status content) "published"))
        (ok (null (jget (content-published content) "featured")) "unchecked box stored as false"))
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ok (search "Published." body) "flash after publish")
        (ok (search "Published page" body) "published + public template gives a page link")
        (ng (search "Preview draft" body) "no draft, no preview link"))
      (multiple-value-bind (status) (request :post (format nil "/s/website/m/blog/~a" id) :form '(("action" . "unpublish")))
        (ok (= status 303)))
      (ok (string= (content-status (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))) "draft"))
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ok (search "Preview draft" body) "draft + preview template gives a preview link")
        (ok (search "https://site.test/blog/" body))
        (ng (search "Published page" body)))
      (multiple-value-bind (status body headers) (request :post (format nil "/s/website/m/blog/~a" id) :form '(("action" . "delete")))
        (declare (ignore body))
        (ok (= status 303))
        (ok (string= (location headers) "/s/website/m/blog")))
      (ok (null (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all)))))
  (testing "object model editor upserts"
    (multiple-value-bind (status body headers) (request :post "/s/website/m/about/new" :form '(("action" . "publish") ("f-body" . "about")))
      (declare (ignore body))
      (ok (= status 303))
      (ok (search "/s/website/m/about/" (location headers))))
    (multiple-value-bind (status body headers) (request :get "/s/website/m/about")
      (declare (ignore body))
      (ok (= status 302))
      (ng (search "/new" (location headers)) "now redirects to the existing content"))))

(deftest normalize-richtext-test
  (ok (string= (normalize-richtext "<p>a</p><p></p><h2>b</h2><ul><li>x</li><li>y</li></ul><hr><p>c<br>d</p>")
               "<p>a</p>
<p><br></p>
<h2>b</h2>
<ul><li>x</li>
<li>y</li>
</ul>
<hr>
<p>c<br>d</p>"))
  (ok (string= (normalize-richtext "<p>x</p>
") "<p>x</p>") "already formatted input is left alone apart from trailing whitespace")
  (ok (string= (normalize-richtext "<p>a&nbsp;b</p>") "<p>a&nbsp;b</p>") "entities are not touched server-side")
  (ok (string= (normalize-richtext "<p><img src=\"http://localhost:3000/media/website/X.png\"></p>")
               "<p><img src=\"/media/website/X.png\"></p>")
      "the editor's absolute media URLs are stored as paths"))

(deftest slugify-test
  (ok (string= (slugify "Hello, World!") "hello-world"))
  (ok (string= (slugify "  Common  Lisp 2026 ") "common-lisp-2026"))
  (ok (string= (slugify "日本語") "") "non-ascii yields empty; validation then reports it"))

(deftest media-library
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (multiple-value-bind (status body) (request :get "/s/website/media")
      (ok (= status 200))
      (ok (search "No media yet" body)))
    (testing "upload from the library page"
      (multiple-value-bind (status body headers)
          (request :post "/s/website/media" :headers origin
                   :multipart (list (list "action" "upload") (list "alt" "Cover")
                                    (list "file" "cover.png" "image/png" (png-bytes 4 4))
                                    (list "file" "second.png" "image/png" (png-bytes 8 8))))
        (declare (ignore body))
        (ok (= status 303))
        (ok (string= (location headers) "/s/website/media")))
      (multiple-value-bind (status body) (request :get "/s/website/media")
        (ok (= status 200))
        (ok (search "Uploaded 2 files." body))
        (ok (search "cover.png" body))
        (ok (search "4×4" body))
        (ok (search "<dialog id=\"media-preview\"" body) "preview modal is on the page")
        (ok (search "data-preview-src=\"/media/website/" body) "cards open it")
        (ok (search "/media/website/" body)))
      (multiple-value-bind (status body) (request :get "/s/website/media" :query "q=second")
        (ok (= status 200))
        (ok (search "second.png" body))
        (ok (not (search "cover.png" body)) "search narrows the grid"))
      (multiple-value-bind (status body)
          (request :post "/s/website/media" :headers origin
                   :multipart (list (list "action" "upload") (list "file" "notes.txt" "text/plain" (babel:string-to-octets "hi"))))
        (declare (ignore body))
        (ok (= status 303)))
      (multiple-value-bind (status body) (request :get "/s/website/media")
        (ok (= status 200))
        (ok (search "Only PNG, JPEG, GIF and WebP" body) "rejection shows as a flash")))
    (testing "editor offers the picker for a :media field"
      (multiple-value-bind (status body) (request :get "/s/website/m/blog/new")
        (ok (= status 200))
        (ok (search "data-media-pick-for=\"f-cover\"" body))
        (ok (search "<dialog id=\"media-picker\"" body))
        (ok (search (media-picker :space "website") body) "dialog knows the picker URL")))
    (testing "picker fragment"
      (multiple-value-bind (status body) (request-url :get (media-picker :space "website"))
        (ok (= status 200))
        (ok (search "data-pick-id=" body))
        (ok (search "data-pick-url=\"/media/website/" body))
        (ok (not (search "<html" body)) "a fragment, not a page"))
      (let ((*cookie* nil))
        (multiple-value-bind (status) (request-url :get (media-picker :space "website"))
          (ok (= status 403) "the picker needs the owner session"))))
    (testing "alt and delete"
      (let ((id (media-id (first (list-media "website" :search "cover")))))
        (multiple-value-bind (status body headers)
            (request :post "/s/website/media" :form `(("action" . "alt") ("id" . ,id) ("alt" . "New alt")) :headers origin)
          (declare (ignore body))
          (ok (= status 303))
          (ok (string= (location headers) "/s/website/media")))
        (multiple-value-bind (status body) (request :get "/s/website/media")
          (ok (= status 200))
          (ok (search "data-preview-alt=\"New alt\"" body) "the dialog opens with the file's alt text"))
        (multiple-value-bind (status body headers)
            (request :post "/s/website/media" :form `(("action" . "delete") ("id" . ,id)) :headers origin)
          (declare (ignore body))
          (ok (= status 303))
          (ok (string= (location headers) "/s/website/media")))
        (ok (null (list-media "website" :search "cover")))))))

(deftest two-factor-settings
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (setf *cookie* nil)
    (request :post "/login" :form `(("secret" . ,*secret*)))
    (ok (not (totp-enabled-p)) "starts disabled")
    (multiple-value-bind (status body) (request :get "/settings")
      (ok (= status 200))
      (ok (search "Disabled" body))
      (ok (search "Set up two-factor login" body)))
    (multiple-value-bind (status body headers) (request :post "/settings" :form '(("action" . "begin")) :headers origin)
      (declare (ignore body))
      (ok (= status 303))
      (ok (string= (location headers) "/settings")))
    (let ((secret nil))
      (multiple-value-bind (status body) (request :get "/settings")
        (ok (= status 200))
        (ok (search "data-qr=\"otpauth://totp/koya:owner?secret=" body) "QR code carries the otpauth URI")
        (multiple-value-bind (match groups) (scan-to-strings "secret=([A-Z2-7]+)&amp;" body)
          (ok match)
          (setf secret (and match (aref groups 0)))))
      (ok (not (totp-enabled-p)) "not enabled until a code confirms the app has the secret")
      (multiple-value-bind (status body) (request :post "/settings" :form '(("action" . "enable") ("code" . "000000")) :headers origin)
        (ok (= status 422))
        (ok (search "did not match" body)))
      (setf *totp-last-counter* -1)
      (multiple-value-bind (status body headers)
          (request :post "/settings" :form `(("action" . "enable") ("code" . ,(totp secret))) :headers origin)
        (declare (ignore body))
        (ok (= status 303))
        (ok (string= (location headers) "/settings")))
      (ok (totp-enabled-p))
      (multiple-value-bind (status body) (request :get "/settings")
        (ok (= status 200))
        (ok (search "Two-factor login is on" body) "flash")
        (ok (search "Disable two-factor login" body)))
      (testing "logging in now needs the code"
        (let ((*cookie* nil))
          (multiple-value-bind (status) (request :post "/login" :form `(("secret" . ,*secret*)))
            (ok (= status 401)))
          (setf *totp-last-counter* -1) ; pretend a new 30 s step has begun
          (multiple-value-bind (status) (request :post "/login" :form `(("secret" . ,*secret*) ("code" . ,(totp secret))))
            (ok (= status 303)))))
      (testing "disabling needs a code too"
        (multiple-value-bind (status body) (request :post "/settings" :form '(("action" . "disable") ("code" . "000000")) :headers origin)
          (ok (= status 422))
          (ok (search "still on" body)))
        (ok (totp-enabled-p))
        (setf *totp-last-counter* -1)
        (multiple-value-bind (status) (request :post "/settings" :form `(("action" . "disable") ("code" . ,(totp secret))) :headers origin)
          (ok (= status 303)))
        (ok (not (totp-enabled-p)))
        (let ((*cookie* nil))
          (multiple-value-bind (status) (request :post "/login" :form `(("secret" . ,*secret*)))
            (ok (= status 303) "secret alone logs in again")))))))

(deftest list-paging
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (setf *cookie* nil)
    (request :post "/login" :form `(("secret" . ,*secret*)))
    (dotimes (i 101)
      (request :post "/s/website/m/blog/new" :form `(("action" . "save") ("f-title" . ,(format nil "Page filler ~3,'0d" i))) :headers origin))
    (multiple-value-bind (status body) (request :get "/s/website/m/blog")
      (ok (= status 200))
      (ok (search "Page 1 of 2" body))
      (ok (search "?page=2" body) "a link to the next page")
      (ok (search "Page filler 100" body) "newest first")
      (ok (not (search "Page filler 000" body)) "the oldest is on the next page"))
    (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query "page=2")
      (ok (= status 200))
      (ok (search "Page 2 of 2" body))
      (ok (search "Page filler 000" body))
      (ok (search "?page=1" body) "and back"))
    (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query "page=9")
      (ok (= status 200))
      (ok (search "Nothing on this page." body)))
    (exec "DELETE FROM contents WHERE json_extract(COALESCE(draft, published), '$.title') LIKE 'Page filler %'")))

(deftest time-zone-setting
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (setf *cookie* nil)
    (request :post "/login" :form `(("secret" . ,*secret*)))
    (multiple-value-bind (status body) (request :get "/settings")
      (ok (= status 200))
      (ok (search "Time zone" body))
      (ok (search "value=\"UTC\"" body) "UTC until the owner picks a zone")
      (ok (search "<option value=\"UTC\">" body) "the datalist offers the zones"))
    (multiple-value-bind (status body) (request :post "/settings" :form '(("action" . "timezone") ("timezone" . "Mars/Olympus_Mons")) :headers origin)
      (ok (= status 422))
      (ok (search "not a time zone" body))
      (ok (string= (display-timezone-name) "UTC") "nothing stored"))
    (if (null (find-timezone "Asia/Tokyo"))
        (skip "no zone database on this machine")
        (progn
          (multiple-value-bind (status body headers) (request :post "/settings" :form '(("action" . "timezone") ("timezone" . "Asia/Tokyo")) :headers origin)
            (declare (ignore body))
            (ok (= status 303))
            (ok (string= (location headers) "/settings")))
          (ok (string= (display-timezone-name) "Asia/Tokyo"))
          (multiple-value-bind (status body) (request :get "/settings")
            (ok (= status 200))
            (ok (search "Times are now shown in Asia&#x2F;Tokyo" body) "flash (text is escaped, attributes are not)")
            (ok (search "value=\"Asia/Tokyo\"" body)))
          (testing "the editor takes and shows datetimes in that zone"
            (let ((id nil))
              (multiple-value-bind (status body headers)
                  (request :post "/s/website/m/blog/new"
                           :form '(("action" . "save") ("f-title" . "Tokyo time") ("f-when" . "2026-09-21T08:30")) :headers origin)
                (declare (ignore body))
                (ok (= status 303))
                (let* ((loc (location headers)) (path (subseq loc 0 (position #\? loc))))
                  (setf id (subseq path (1+ (position #\/ path :from-end t))))))
              (let ((content (find-if (lambda (c) (string= (content-id c) id))
                                      (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
                (ok (string= (jget (content-draft content) "when") "2026-09-20T23:30:00.000Z") "stored as UTC"))
              (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
                (ok (= status 200))
                (ok (search "value=\"2026-09-21T08:30\"" body) "shown back in the zone")
                (ok (search ">Asia&#x2F;Tokyo<" body) "the hint names the zone")
                (ok (search " JST</span>" body) "created at is in the zone"))
              (multiple-value-bind (status body) (request :get "/s/website/m/blog")
                (ok (= status 200))
                (ok (search "2026-09-21 08:30 JST" body) "list preview in the zone"))
              (request :post (format nil "/s/website/m/blog/~a" id) :form '(("action" . "delete")) :headers origin)))
          (multiple-value-bind (status) (request :post "/settings" :form '(("action" . "timezone") ("timezone" . "UTC")) :headers origin)
            (ok (= status 303)))
          (ok (string= (display-timezone-name) "UTC") "back to UTC for the other tests")))))

(deftest cache-control
  (multiple-value-bind (status body headers) (request :get "/assets/style/dist.css")
    (declare (ignore body))
    (ok (= status 200))
    (ok (string= (getf headers :cache-control) "public, max-age=31536000, immutable") "assets are immutable"))
  (multiple-value-bind (status body headers) (request :get "/assets/nope.css")
    (declare (ignore body))
    (ok (= status 404))
    (ok (string= (getf headers :cache-control) "no-store") "a missing asset is not cached"))
  (let ((*cookie* nil))
    (multiple-value-bind (status body headers) (request :get "/login")
      (ok (= status 200))
      (ok (string= (getf headers :cache-control) "no-store") "pages are not cached")
      (ok (search "/assets/style/dist.css?v=" body) "asset URLs carry a version")
      (ok (search "/assets/icon.svg?v=" body)))))

(deftest login-lockout
  (let ((*cookie* nil))
    (clear-login-failures "127.0.0.1")
    (dotimes (i 5)
      (multiple-value-bind (status) (request :post "/login" :form '(("secret" . "nope")))
        (ok (= status 401))))
    (multiple-value-bind (status body) (request :post "/login" :form `(("secret" . ,*secret*)))
      (ok (= status 403) "even the right secret is refused while locked")
      (ok (search "Too many attempts" body)))
    (clear-login-failures "127.0.0.1")
    (multiple-value-bind (status) (request :post "/login" :form `(("secret" . ,*secret*)))
      (ok (= status 303) "logs in again once the lock is cleared"))))

(deftest body-size-limit
  (let ((env (list :request-method :post :script-name "" :path-info "/login" :query-string ""
                   :server-name "localhost" :server-port 3000 :server-protocol :http/1.1
                   :request-uri "/login" :url-scheme "http" :remote-addr "127.0.0.1"
                   :headers (alist-hash-table '(("host" . "localhost:3000")) :test 'equal)
                   :content-type "multipart/form-data; boundary=x" :content-length (* 3000 1024 1024)
                   :raw-body (make-in-memory-input-stream (string-to-octets "")))))
    (destructuring-bind (status headers body) (funcall *app* env)
      (declare (ignore headers))
      (ok (= status 413) "a huge Content-Length is refused before the body is read")
      (ok (search "too_large" (first body))))))

(deftest list-columns-are-bounded
  (multiple-value-bind (status body headers)
      (request :post "/s/website/m/blog/new" :form '(("action" . "save") ("f-title" . "Columns") ("f-body" . "<p>x</p>"))
               :headers '(("origin" . "http://localhost:3000")))
    (declare (ignore body))
    (ok (= status 303))
    (let ((path (subseq (location headers) 0 (position #\? (location headers)))))
      (multiple-value-bind (status body) (request :get "/s/website/m/blog")
        (ok (= status 200))
        (ok (search ">related<" body) "every field keeps its column")
        (ok (search "min-w-16 max-w-20" body) "a boolean column stays narrow")
        (ok (search "min-w-36 max-w-64" body) "a richtext column is allowed to be wide")
        (ok (search "line-clamp-2" body) "a preview is clamped to two lines")
        (ok (search "h-14" body) "every row is the same height")
        (ok (< (search ">status<" body) (search ">title<" body)) "status leads the row"))
      (request :post path :form '(("action" . "delete")) :headers '(("origin" . "http://localhost:3000"))))))

(deftest webhook-log-page
  (let ((hooked (make-schema (list (make-space "website"
                                               :webhooks (list (make-webhook "revalidate" "https://site.test/api/revalidate"))
                                               :models (list (blog-model)
                                                             (make-model "about" :object (list (make-field :body :richtext)))))))))
    (unwind-protect
         (progn
           (save-schema hooked)
           (exec "DELETE FROM webhook_deliveries")
           (record-delivery "website" :label "revalidate" :url "https://site.test/api/revalidate"
                                      :model "blog" :event "publish" :content-id "01ARZ3NDEKTSV4RRFFQ69G5FAV"
                                      :ok t :status 200 :response "{\"revalidated\":[\"/blog\"]}"
                                      :error "" :duration-ms 42)
           (record-delivery "website" :label "revalidate" :url "https://site.test/api/revalidate"
                                      :model "blog" :event "draft" :content-id "01ARZ3NDEKTSV4RRFFQ69G5FAW"
                                      :ok nil :status nil :response ""
                                      :error "connection refused" :duration-ms 5001)
           (testing "the space page sends each webhook to its own log"
             (multiple-value-bind (status body) (request :get "/s/website")
               (ok (= status 200))
               (ok (search "/s/website/webhooks?label=revalidate" body) "the row is a link to that hook's log")
               (ok (search "\"/s/website/webhooks\"" body) "and View log links to the unfiltered log")
               (ok (search "View log" body))))
           (testing "a model page links to the log narrowed to that model"
             (multiple-value-bind (status body) (request :get "/s/website/m/blog")
               (ok (= status 200))
               (ok (search "/s/website/webhooks?model=blog" body))))
           (testing "an object model has no list page, so its editor carries the link"
             (multiple-value-bind (status body) (request :get "/s/website/m/about/new")
               (ok (= status 200))
               (ok (search "/s/website/webhooks?model=about" body))))
           (testing "the log shows the outcome and what came back"
             (multiple-value-bind (status body) (request :get "/s/website/webhooks")
               (ok (= status 200))
               (ok (search "200" body) "the status is shown")
               (ok (search "revalidated" body) "so is the response body")
               (ok (search "connection refused" body) "and the error of the call that never arrived")
               (ok (search "42 ms" body))
               (ok (search "no response" body) "a call with no status says so")))
           (testing "the filters can be set from the page itself"
             (multiple-value-bind (status body) (request :get "/s/website/webhooks")
               (ok (= status 200))
               (ok (search "<form method=\"get\" action=\"/s/website/webhooks\"" body)
                   "an unfiltered page still offers the form")
               (ok (search "name=\"label\"" body))
               (ok (search "name=\"model\"" body))
               (ok (search "<option value=\"revalidate\"" body) "the schema's webhooks are offered")
               (ok (search "<option value=\"blog\"" body))
               (ok (search "<option value=\"about\"" body)
                   "every model of the space is offered, not only the ones that have fired")
               (ok (search "<button type=\"submit\" class=\"btn\"" body) "with a button to apply them")
               (ng (search "Clear" body) "nothing to clear when nothing is filtered")))
           (testing "either filter narrows it"
             (multiple-value-bind (status body) (request :get "/s/website/webhooks" :query "label=revalidate")
               (ok (= status 200))
               (ok (search "revalidated" body) "the hook's own calls are still there")
               (ok (search "Clear" body)))
             (multiple-value-bind (status body) (request :get "/s/website/webhooks" :query "model=blog")
               (ok (= status 200))
               (ok (search "connection refused" body) "blog's calls are all there"))
             (multiple-value-bind (status body) (request :get "/s/website/webhooks" :query "model=about")
               (ok (= status 200))
               (ok (search "Nothing matches these filters" body)
                   "a model that has never fired is selectable and simply empty"))
             (multiple-value-bind (status body) (request :get "/s/website/webhooks" :query "label=nothing")
               (ok (= status 200))
               (ok (search "Nothing matches these filters" body))
               (ok (search "<option value=\"nothing\" selected" body)
                   "a value neither the schema nor the log knows still shows as the filter, so the other select cannot drop it"))
             (testing "both together, and the selects show what is filtered"
               (multiple-value-bind (status body)
                   (request :get "/s/website/webhooks" :query "label=revalidate&model=blog")
                 (ok (= status 200))
                 (ok (search "<option value=\"revalidate\" selected" body))
                 (ok (search "<option value=\"blog\" selected" body)))))
           (multiple-value-bind (status) (request :get "/s/nope/webhooks")
             (ok (= status 404))))
      (save-schema (make-schema (list (make-space "website"
                                                  :models (list (blog-model)
                                                                (make-model "about" :object (list (make-field :body :richtext))))))))
      (exec "DELETE FROM webhook_deliveries")))
  (testing "with the webhooks gone, nothing offers a log that can only be empty"
    (multiple-value-bind (status body) (request :get "/s/website/m/blog")
      (ok (= status 200))
      (ng (search "/s/website/webhooks" body)))
    (multiple-value-bind (status body) (request :get "/s/website/m/about/new")
      (ok (= status 200))
      (ng (search "/s/website/webhooks" body)))))
