(defpackage #:koya-spec/server/web/lib/forms
  (:use #:cl #:rove)
  (:import-from #:koya-server/web/lib/forms #:form->data)
  (:import-from #:koya-core/schema #:make-field #:make-model #:make-schema #:make-custom-field #:schema-model)
  (:import-from #:koya-core/json #:jget))
(in-package #:koya-spec/server/web/lib/forms)

(defparameter +crlf+ (format nil "~C~C" #\Return #\Newline))

(defun lines (&rest lines)
  (format nil "~{~a~^~%~}" lines))

(deftest a-textarea-is-read-as-it-was-written
  (let ((model (make-model "note" :list (list (make-field :text :textarea) (make-field :title :text)))))
    (flet ((read-field (name value)
             (multiple-value-list (gethash name (form->data model (list (cons (format nil "f-~a" name) value)))))))
      (ok (equal (read-field "text" (format nil "a~ab" +crlf+)) (list (lines "a" "b") t))
          "the CRLF a browser sends is the line break it was given")
      (ok (equal (read-field "text" (format nil "  indented~a" +crlf+)) (list (format nil "  indented~%") t))
          "and nothing around the text is trimmed")
      (ok (equal (read-field "text" (format nil " ~a " +crlf+)) (list nil nil))
          "but whitespace alone is no value")
      (ok (equal (read-field "title" "  Title  ") (list "Title" t))
          "a one-line text is trimmed as before"))))

(deftest a-custom-field-is-read-from-its-fields
  (let ((model (schema-model (make-schema :custom-fields (list (make-custom-field "card" (list (make-field :title :text)
                                                                                                (make-field :shown :boolean)
                                                                                                (make-field :rank :number))))
                                          :models (list (make-model "page" :list (list (make-field :card :custom :custom-field "card")))))
                             "page")))
    (let ((card (gethash "card" (form->data model '(("f-card" . "on") ("f-card.title" . " Hi ") ("f-card.shown" . "on") ("f-card.rank" . "2"))))))
      (ok (string= (jget card "title") "Hi") "each field inside is read as it is at the top")
      (ok (eq (jget card "shown") t))
      (ok (= (jget card "rank") 2)))
    (let ((card (gethash "card" (form->data model '(("f-card" . "on"))))))
      (ok (hash-table-p card) "a custom field the form says is there is there, though nothing inside is filled")
      (ok (eq (nth-value 1 (gethash "shown" card)) t))
      (ok (null (jget card "shown")) "and a box left unchecked inside is false"))
    (ok (null (nth-value 1 (gethash "card" (form->data model '(("f-card.title" . "Hi") ("f-card.shown" . "on"))))))
        "without the form saying it is there, whatever is inside is none")))

(deftest a-repeater-is-read-row-by-row
  (let ((model (schema-model (make-schema :custom-fields (list (make-custom-field "heading" (list (make-field :text :text)))
                                                               (make-custom-field "flag" (list (make-field :on :boolean)
                                                                                               (make-field :rank :number))))
                                          :models (list (make-model "page" :list (list (make-field :blocks :repeater :custom-fields '(heading flag))))))
                             "page")))
    (let ((rows (gethash "blocks" (form->data model '(("f-blocks" . "k2,k1")
                                                      ("f-blocks.k1.fieldId" . "heading") ("f-blocks.k1.text" . "Second")
                                                      ("f-blocks.k2.fieldId" . "flag") ("f-blocks.k2.rank" . "3"))))))
      (ok (= (length rows) 2) "a row for each key")
      (ok (string= (jget (aref rows 0) "fieldId") "flag") "in the order the keys come")
      (ok (= (jget (aref rows 0) "rank") 3) "each row read as its custom field")
      (ok (eq (nth-value 1 (gethash "on" (aref rows 0))) t))
      (ok (null (jget (aref rows 0) "on")) "an unchecked box is false")
      (ok (string= (jget (aref rows 1) "text") "Second")))
    (ok (null (nth-value 1 (gethash "blocks" (form->data model '())))) "no rows is no value")))
