(defpackage #:koya-spec/server/usecases/delivery
  (:use #:cl #:rove)
  (:import-from #:koya-server/infra/db/connection #:connect-db #:disconnect-db #:exec)
  (:import-from #:koya-server/infra/db/migrations #:migrate)
  (:import-from #:koya-server/usecases/schema #:replace-schema #:find-model)
  (:import-from #:koya-server/usecases/spaces #:create-space)
  (:import-from #:koya-server/usecases/contents #:create #:update-draft #:draft-key)
  (:import-from #:koya-server/usecases/delivery
                #:deliver #:delivered-data #:delivered-p #:delivered-content
                #:delivered-list-content #:delivered-list #:delivered-object
                #:delivered-list-content-by-slug)
  (:import-from #:koya-server/usecases/ports/media #:insert-media)
  (:import-from #:koya-server/domain/media #:media-p #:media-id)
  (:import-from #:koya-server/domain/content #:content-id)
  (:import-from #:koya-server/domain/errors #:not-found)
  (:import-from #:koya-server/domain/query #:parse-query #:query-error)
  (:import-from #:koya-core/schema #:make-field #:make-model #:make-schema #:make-custom-field)
  (:import-from #:koya-core/json #:jobject #:jget #:json-null-p))
(in-package #:koya-spec/server/usecases/delivery)

(setup
  (connect-db ":memory:")
  (migrate)
  (create-space "site")
  (replace-schema "site"
                  (make-schema :models (list (make-model "post" :list (list (make-field :title :text :required t)
                                                                           (make-field :cover :media)
                                                                           (make-field :author :reference :model "author")
                                                                           (make-field :tags :reference :model "tag" :many t)
                                                                           (make-field :body :richtext)))
                                             (make-model "author" :list (list (make-field :name :text)
                                                                             (make-field :avatar :media)
                                                                             (make-field :favorite :reference :model "tag")))
                                             (make-model "tag" :list (list (make-field :name :text)))
                                             (make-model "page" :list (list (make-field :title :text)
                                                                           (make-field :slug :slug)))
                                             (make-model "about" :object (list (make-field "body" :text)))))))

(teardown (disconnect-db))

(defhook :before (exec "DELETE FROM contents") (exec "DELETE FROM media"))

(defun model (name) (find-model "site" name))
(defun make (model-name data &rest args)
  (apply #'create "site" (model model-name) (jobject-from data) args))
(defun jobject-from (plist)
  (let ((object (make-hash-table :test 'equal)))
    (loop :for (k v) :on plist :by #'cddr :do (setf (gethash k object) v))
    object))
(defun query (&rest kv) (parse-query (loop :for (k v) :on kv :by #'cddr :collect (cons k v))))
(defun picture (id)
  (media-id (insert-media "site" :id id :filename "p.png" :mime "image/png" :size 1 :width 1 :height 1)))

(deftest media-fields-hold-their-media
  (let* ((cover (picture "01ARZ3NDEKTSV4RRFFQ69G5FAA"))
         (post (make "post" (list "title" "One" "cover" cover) :publish t))
         (data (delivered-data (deliver post (model "post") "site"))))
    (ok (media-p (jget data "cover")) "the id became the media, without being asked")
    (ok (string= (media-id (jget data "cover")) cover))
    (testing "a media that has since gone is null, not a dangling id"
      (exec "DELETE FROM media")
      (ok (json-null-p (jget (delivered-data (deliver post (model "post") "site")) "cover"))))
    (testing "the content itself is untouched"
      (ok (stringp (jget (koya-server/domain/content:content-published post) "cover"))))))

(deftest references-stay-ids-unless-included
  (let* ((author (make "author" (list "name" "Ann") :publish t))
         (tag (make "tag" (list "name" "lisp") :publish t))
         (draft-tag (make "tag" (list "name" "unseen")))
         (post (make "post" (list "title" "One" "author" (content-id author)
                                  "tags" (vector (content-id tag) (content-id draft-tag) "gone"))
                     :publish t)))
    (let ((plain (delivered-data (deliver post (model "post") "site"))))
      (ok (string= (jget plain "author") (content-id author)) "an id, as stored")
      (ok (= (length (jget plain "tags")) 3)))
    (let ((data (delivered-data (deliver post (model "post") "site" :include '(("author") ("tags"))))))
      (ok (delivered-p (jget data "author")) "included: the content, delivered in turn")
      (ok (string= (jget (delivered-data (jget data "author")) "name") "Ann"))
      (ok (= (length (jget data "tags")) 1) "of three tags only the published one that exists is delivered")
      (ok (string= (jget (delivered-data (aref (jget data "tags") 0)) "name") "lisp")))
    (testing "what is included carries its media, and a path names its references"
      (let* ((avatar (picture "01ARZ3NDEKTSV4RRFFQ69G5FAB"))
             (pictured (make "author" (list "name" "Bo" "avatar" avatar "favorite" (content-id tag)) :publish t))
             (post (make "post" (list "title" "Two" "author" (content-id pictured)) :publish t))
             (shallow (delivered-data (jget (delivered-data (deliver post (model "post") "site" :include '(("author")))) "author")))
             (deep (delivered-data (jget (delivered-data (deliver post (model "post") "site" :include '(("author" "favorite")))) "author"))))
        (ok (media-p (jget shallow "avatar")) "media, always")
        (ok (stringp (jget shallow "favorite")) "a reference, only when its path is asked for")
        (ok (delivered-p (jget deep "favorite")))
        (ok (string= (jget (delivered-data (jget deep "favorite")) "name") "lisp"))))
    (testing "an include that names no reference field is a bad query"
      (ok (signals (delivered-list "site" (model "post") (query "include" "title")) 'query-error)))))

(deftest an-include-is-checked-before-anything-is-read
  (flet ((refused (thunk)
           (handler-case (progn (funcall thunk) nil)
             (query-error (e) (princ-to-string e)))))
    (testing "on a list with nothing in it"
      (ok (refused (lambda () (delivered-list "site" (model "post") (query "include" "title"))))
          "a field that is no reference")
      (ok (refused (lambda () (delivered-list "site" (model "post") (query "include" "bogus"))))
          "a field the model does not have"))
    (testing "a path is checked to its end, whatever the references hold"
      (make "post" (list "title" "No tags" "tags" (vector)) :publish t)
      (let ((message (refused (lambda () (delivered-list "site" (model "post") (query "include" "tags.name"))))))
        (ok message "a segment that is no reference of the model it reaches")
        (ok (search "tags.name" message) "named by its path"))
      (ok (refused (lambda () (delivered-list "site" (model "post") (query "include" "author.favorite.name")))))
      (ok (null (refused (lambda () (delivered-list "site" (model "post") (query "include" "author.favorite,tags")))))
          "a path that only names references is fine"))
    (testing "before one content is looked for"
      (ok (refused (lambda () (delivered-list-content "site" (model "post") "nothing-here" (query "include" "title"))))
          "a bad query, not a missing content")
      (ok (refused (lambda () (delivered-object "site" (model "about") (query "include" "body"))))))))

(deftest searching
  (let ((lisp (make "post" (list "title" "Lisp macros" "body" "<p>Write <strong>macros</strong> in Lisp</p>") :publish t))
        (other (make "post" (list "title" "Other" "body" "<p>AT&amp;T and 100%</p>") :publish t)))
    (make "post" (list "title" "Draft lisp"))
    (flet ((found (&rest kv)
             (sort (mapcar (lambda (d) (content-id (delivered-content d))) (delivered-list "site" (model "post") (apply #'query kv)))
                   #'string<))
           (ids (&rest contents) (sort (mapcar #'content-id contents) #'string<)))
      (testing "q searches the text fields of what is published"
        (ok (equal (found "q" "lisp") (ids lisp)) "the title, either case, and not the draft")
        (ok (equal (found "q" "macros in") (ids lisp)) "rich text is searched as the text it reads")
        (ok (equal (found "q" "AT&T") (ids other)) "with its character references read")
        (ok (null (found "q" "strong")) "and not its tags")
        (ok (equal (found "q" "100%") (ids other)))
        (ok (null (found "q" "_")) "a LIKE wildcard is only itself")
        (ok (equal (found "q" (content-id other)) (ids other)) "the id, whole")
        (ok (equal (found "q" "") (ids lisp other)) "an empty q is no search"))
      (testing "q and filters both apply"
        (ok (null (found "q" "lisp" "filters" "title[equals]Other")))
        (ok (equal (found "q" "and" "filters" "title[equals]Other") (ids other))))
      (testing "a filter on rich text reads its text as well"
        (ok (null (found "filters" "body[contains]strong")))
        (ok (equal (found "filters" "body[contains]macros in") (ids lisp)))
        (ok (equal (found "filters" "body[begins_with]Write") (ids lisp)))
        (ok (equal (found "filters" "body[not_contains]strong") (ids lisp other)))))))

(deftest what-is-delivered-and-what-is-not
  (let* ((live (make "post" (list "title" "Live") :publish t))
         (draft (make "post" (list "title" "Draft")))
         (id (content-id draft)))
    (ok (string= (jget (delivered-data (delivered-list-content "site" (model "post") (content-id live) (query))) "title") "Live"))
    (ok (signals (delivered-list-content "site" (model "post") id (query)) 'not-found) "a draft is not there")
    (ok (signals (delivered-list-content "site" (model "post") "nope" (query)) 'not-found))
    (testing "but its draft key opens it, as a preview"
      (let ((key (draft-key "site" (model "post") id)))
        (ok (string= (jget (delivered-data (delivered-list-content "site" (model "post") id (query) :draft-key key)) "title") "Draft"))
        (ok (signals (delivered-list-content "site" (model "post") id (query) :draft-key "wrong") 'not-found))
        (testing "and shows the draft of a published content, where the key is the new draft's"
          (update-draft "site" (model "post") (content-id live) (jobject-from (list "title" "Live, edited")))
          (let ((key (draft-key "site" (model "post") (content-id live))))
            (ok (string= (jget (delivered-data (delivered-list-content "site" (model "post") (content-id live) (query) :draft-key key)) "title")
                         "Live, edited"))
            (ok (string= (jget (delivered-data (delivered-list-content "site" (model "post") (content-id live) (query))) "title")
                         "Live") "without it, what is live")))
        (testing "and embeds only what is published, as publishing this one alone would show it"
          (let* ((tag (make "tag" (list "name" "lisp") :publish t))
                 (new-tag (make "tag" (list "name" "new")))
                 (author (make "author" (list "name" "Ann") :publish t))
                 (preview (make "post" (list "title" "Preview" "author" (content-id author)
                                             "tags" (vector (content-id tag) (content-id new-tag))))))
            (update-draft "site" (model "tag") (content-id tag) (jobject-from (list "name" "lisp, edited")))
            (update-draft "site" (model "author") (content-id author) (jobject-from (list "name" "Ann, edited")))
            (let* ((key (draft-key "site" (model "post") (content-id preview)))
                   (data (delivered-data (delivered-list-content "site" (model "post") (content-id preview)
                                                        (query "include" "author,tags") :draft-key key)))
                   (tags (jget data "tags")))
              (ok (= (length tags) 1) "a tag never published drops out")
              (ok (string= (jget (delivered-data (aref tags 0)) "name") "lisp") "a published tag shows what is live, not its draft")
              (ok (string= (jget (delivered-data (jget data "author")) "name") "Ann")))))))
    (testing "a list is the published ones, with how many there are"
      (multiple-value-bind (items total) (delivered-list "site" (model "post") (query "limit" "1"))
        (ok (= total 1))
        (ok (= (length items) 1))
        (ok (string= (content-id (delivered-content (first items))) (content-id live)))))
    (testing "an object model delivers its one content"
      (ok (signals (delivered-object "site" (model "about") (query)) 'not-found) "none yet")
      (make "about" (list "body" "hi") :publish t)
      (ok (string= (jget (delivered-data (delivered-object "site" (model "about") (query))) "body") "hi")))))

(defun with-byline ()
  (make-schema :custom-fields (list (make-custom-field "byline" (list (make-field :note :richtext)
                                                                      (make-field :caption :text)
                                                                      (make-field :kind :select :options '("zebra" "other"))
                                                                      (make-field :photo :media)
                                                                      (make-field :by :reference :model "author"))))
               :models (list (make-model "story" :list (list (make-field :title :text)
                                                             (make-field :byline :custom :custom-field "byline")))
                             (make-model "author" :list (list (make-field :name :text))))))

(deftest a-content-is-delivered-by-its-slug
  (flet ((title (slug &key draft-key)
           (jget (delivered-data (delivered-list-content-by-slug "site" (model "page") slug (query) :draft-key draft-key))
                 "title")))
    (let ((live (content-id (make "page" (list "title" "Live" "slug" "live") :publish t)))
          (drafted (content-id (make "page" (list "title" "Drafted" "slug" "drafted")))))
      (update-draft "site" (model "page") live (jobject-from (list "title" "Live, next" "slug" "live-next")))
      (ok (string= (title "live") "Live") "by its published slug, as published")
      (ok (signals (title "live-next") 'not-found) "not by its draft's")
      (ok (signals (title "drafted") 'not-found) "nor a content that is only a draft")
      (ok (signals (title "nope") 'not-found))
      (testing "with its draft key"
        (let ((key (draft-key "site" (model "page") live)))
          (ok (string= (title "live-next" :draft-key key) "Live, next") "by its draft's slug, as the draft")
          (ok (string= (title "live" :draft-key key) "Live, next") "and by its published slug, as the draft too"))
        (ok (string= (title "drafted" :draft-key (draft-key "site" (model "page") drafted)) "Drafted")
            "a content that is only a draft"))
      (testing "with a key that is not the content's"
        (ok (signals (title "live-next" :draft-key "wrong") 'not-found)
            "its draft's slug finds nothing, so the slug is not given away")
        (ok (signals (title "live-next" :draft-key (draft-key "site" (model "page") drafted)) 'not-found)
            "nor does another content's key")
        (ok (string= (title "live" :draft-key "wrong") "Live") "its published slug finds it, as published")))))

(deftest a-custom-field-is-delivered-like-the-fields-it-holds
  (replace-schema "site" (with-byline))
  (unwind-protect
       (let* ((photo (picture "01ARZ3NDEKTSV4RRFFQ69G5FAC"))
              (ann (make "author" (list "name" "Ann") :publish t))
              (story (make "story" (list "title" "Plain"
                                         "byline" (jobject "note" "<p>Written <em>slowly</em> <img src=\"/media/site/x.png\"></p>"
                                                           "caption" "a <b and c> d" "kind" "zebra"
                                                           "photo" photo "by" (content-id ann)))
                           :publish t)))
         (let ((byline (jget (delivered-data (deliver story (model "story") "site")) "byline")))
           (ok (media-p (jget byline "photo")) "media inside is expanded")
           (ok (stringp (jget byline "by")) "a reference inside stays an id"))
         (let ((byline (jget (delivered-data (deliver story (model "story") "site" :include '(("byline" "by")))) "byline")))
           (ok (delivered-p (jget byline "by")) "until a path names it")
           (ok (string= (jget (delivered-data (jget byline "by")) "name") "Ann")))
         (ok (null (handler-case (progn (delivered-list "site" (model "story") (query "include" "byline.by")) nil)
                     (query-error (e) e)))
             "and the path is checked through the custom field")
         (ok (signals (delivered-list "site" (model "story") (query "include" "byline.note")) 'query-error))
         (flet ((found (&rest kv) (length (delivered-list "site" (model "story") (apply #'query kv)))))
           (ok (= (found "q" "slowly") 1) "q reads the text inside")
           (ok (= (found "q" "b and c") 1) "a text inside is matched as it is written, not as HTML")
           (ok (= (found "q" "zebra") 0) "only the text fields inside are searched")
           (ok (= (found "q" "d written") 0) "each one on its own")
           (ok (= (found "filters" "byline[contains]written slowly") 1) "and so does contains")
           (ok (signals (found "filters" "byline[equals]x") 'query-error) "but nothing else filters it")
           (ok (signals (found "orders" "byline") 'query-error) "or orders by it")))
    (replace-schema "site" (make-schema :models (list (make-model "post" :list (list (make-field :title :text :required t)
                                                                                    (make-field :cover :media)
                                                                                    (make-field :author :reference :model "author")
                                                                                    (make-field :tags :reference :model "tag" :many t)
                                                                                    (make-field :body :richtext)))
                                                      (make-model "author" :list (list (make-field :name :text)
                                                                                      (make-field :avatar :media)
                                                                                      (make-field :favorite :reference :model "tag")))
                                                      (make-model "tag" :list (list (make-field :name :text)))
                                                      (make-model "about" :object (list (make-field "body" :text))))))))

(defun with-blocks ()
  (make-schema :custom-fields (list (make-custom-field "byline" (list (make-field :by :reference :model "author")
                                                                      (make-field :photo :media)
                                                                      (make-field :text :text)))
                                    (make-custom-field "body" (list (make-field :text :richtext)
                                                                    (make-field :by :text)
                                                                    (make-field :kind :select :options '("zebra" "other")))))
               :models (list (make-model "story" :list (list (make-field :title :text)
                                                             (make-field :blocks :repeater :custom-fields '(byline body))))
                             (make-model "author" :list (list (make-field :name :text))))))

(deftest a-repeater-is-delivered-row-by-row
  (replace-schema "site" (with-blocks))
  (unwind-protect
       (let* ((photo (picture "01ARZ3NDEKTSV4RRFFQ69G5FAD"))
              (ann (make "author" (list "name" "Ann") :publish t))
              (story (make "story" (list "title" "Rows"
                                         "blocks" (vector (jobject "fieldId" "body" "text" "<p>Written <em>slowly</em></p>" "kind" "zebra"
                                                                   "by" "Someone")
                                                          (jobject "fieldId" "byline" "photo" photo "by" (content-id ann))))
                           :publish t)))
         (let ((rows (jget (delivered-data (deliver story (model "story") "site")) "blocks")))
           (ok (string= (jget (aref rows 0) "fieldId") "body") "each row names its custom field")
           (ok (media-p (jget (aref rows 1) "photo")) "media in a row is expanded")
           (ok (stringp (jget (aref rows 1) "by")) "a reference in a row stays an id"))
         (let ((rows (jget (delivered-data (deliver story (model "story") "site" :include '(("blocks" "by")))) "blocks")))
           (ok (delivered-p (jget (aref rows 1) "by")) "until a path names it")
           (ok (equal (jget (aref rows 0) "by") "Someone")
               "and a field of that name in another custom field, which is no reference, is left as it is"))
         (ok (signals (delivered-list "site" (model "story") (query "include" "blocks.text")) 'query-error)
             "a path names a reference in the rows")
         (flet ((found (&rest kv) (length (delivered-list "site" (model "story") (apply #'query kv)))))
           (ok (= (found "q" "written slowly") 1) "q reads the text fields of the rows")
           (ok (= (found "q" "zebra") 0) "and only those")
           (ok (= (found "q" "em") 0) "a rich text field in a row is read as its text, whatever another custom field calls text")
           (ok (= (found "filters" "blocks[contains]slowly") 1) "and so does contains")
           (ok (= (found "filters" "blocks[not_contains]slowly") 0))
           (ok (signals (found "filters" "blocks[equals]x") 'query-error) "but nothing else filters it")
           (ok (signals (found "orders" "blocks") 'query-error) "or orders by it")))
    (replace-schema "site" (make-schema :models (list (make-model "post" :list (list (make-field :title :text :required t)
                                                                                    (make-field :cover :media)
                                                                                    (make-field :author :reference :model "author")
                                                                                    (make-field :tags :reference :model "tag" :many t)
                                                                                    (make-field :body :richtext)))
                                                      (make-model "author" :list (list (make-field :name :text)
                                                                                      (make-field :avatar :media)
                                                                                      (make-field :favorite :reference :model "tag")))
                                                      (make-model "tag" :list (list (make-field :name :text)))
                                                      (make-model "about" :object (list (make-field "body" :text))))))))

(deftest several-media-in-one-field
  (replace-schema "site" (make-schema :models (list (make-model "album" :list (list (make-field :title :text)
                                                                                  (make-field :photos :media :many t))))))
  (unwind-protect
       (let* ((a (picture "01ARZ3NDEKTSV4RRFFQ69G5FAE"))
              (b (picture "01ARZ3NDEKTSV4RRFFQ69G5FAF"))
              (album (make "album" (list "title" "A" "photos" (vector b "01ARZ3NDEKTSV4RRFFQ69G5GON" a)) :publish t))
              (photos (jget (delivered-data (deliver album (model "album") "site")) "photos")))
         (ok (= (length photos) 2) "a file that is gone drops out")
         (ok (and (media-p (aref photos 0)) (string= (media-id (aref photos 0)) b)) "the rest are media, in their order")
         (ok (string= (media-id (aref photos 1)) a)))
    (replace-schema "site" (make-schema :models (list (make-model "post" :list (list (make-field :title :text :required t)
                                                                                    (make-field :cover :media)
                                                                                    (make-field :author :reference :model "author")
                                                                                    (make-field :tags :reference :model "tag" :many t)
                                                                                    (make-field :body :richtext)))
                                                      (make-model "author" :list (list (make-field :name :text)
                                                                                      (make-field :avatar :media)
                                                                                      (make-field :favorite :reference :model "tag")))
                                                      (make-model "tag" :list (list (make-field :name :text)))
                                                      (make-model "about" :object (list (make-field "body" :text))))))))
