(defpackage #:koya-server/web/pages/s/<space>/m/<model>/<id>
  (:use #:cl #:hsx)
  (:import-from #:jingle #:set-response-status)
  (:import-from #:koya-core/schema #:model-kind #:model-name)
  (:import-from #:koya-server/usecases/contents #:find-content)
  (:import-from #:koya-server/web/lib/http #:path-param #:redirect-to)
  (:import-from #:koya-server/domain/errors #:not-found)
  (:import-from #:koya-server/web/lib/urls #:model-url)
  (:import-from #:koya-server/web/ui/layout #:~layout)
  (:import-from #:koya-server/web/ui/content/editor #:new-p #:show-editor)
  (:import-from #:koya-server/usecases/schema #:resolve-model)
  (:export #:@get))
(in-package #:koya-server/web/pages/s/<space>/m/<model>/<id>)

(defun load-editor (params)
  (multiple-value-bind (space model) (resolve-model (path-param params :space) (path-param params :model))
    (let ((id (path-param params :id)))
      (values space model (and (not (new-p id))
                               (find-content space (model-name model) id))))))

(defmacro with-editor ((space model content) params &body body)
  `(handler-case
       (multiple-value-bind (,space ,model ,content) (load-editor ,params)
         (if (and (null ,content) (not (new-p (path-param ,params :id))))
             (progn (set-response-status 404)
                    (hsx (~layout :space (path-param ,params :space) (h1 :class "text-xl font-bold" "Content not found"))))
             (progn ,@body)))
     (not-found ()
       (set-response-status 404)
       (hsx (~layout (h1 :class "text-xl font-bold" "Model not found"))))))

(defun @get (params)
  (with-editor (space model content) params
    (if (eq (model-kind model) :object)
        (redirect-to (model-url space (model-name model)) 302)
        (show-editor params space model content))))
