(defpackage #:koya-spec/core/validate
  (:use #:cl #:rove)
  (:import-from #:koya-core/schema
                #:make-field #:make-model #:make-schema #:make-custom-field #:schema-model)
  (:import-from #:koya-core/validate
                #:validate-content)
  (:import-from #:koya-core/json
                #:parse-json))
(in-package #:koya-spec/core/validate)

(defparameter *model*
  (make-model "blog" :list
              (list (make-field :title :text :required t :max-length 10 :pattern "^[A-Z]")
                    (make-field :slug :slug :from :title)
                    (make-field :body :richtext)
                    (make-field :count :number :integer t :min 0 :max 10)
                    (make-field :featured :boolean)
                    (make-field :day :date)
                    (make-field :event-at :datetime :required t)
                    (make-field :category :select :options (quote ("news" "tech")))
                    (make-field :labels :select :options (quote ("a" "b")) :many t)
                    (make-field :tags :reference :model "tag" :many t)
                    (make-field :cover :media))))

(defun codes (json)
  (mapcar (lambda (e) (cons (getf e :field) (getf e :code)))
          (validate-content *model* (parse-json json))))

(deftest valid-content
  (ok (null (codes "{\"title\": \"Hello\", \"eventAt\": \"2026-09-20T00:00:00Z\", \"slug\": \"hello-world\",
                     \"count\": 3, \"featured\": true, \"day\": \"2026-09-20\", \"category\": \"news\",
                     \"labels\": [\"a\", \"b\"], \"tags\": [\"01ARZ3NDEKTSV4RRFFQ69G5FAV\"],
                     \"cover\": \"01ARZ3NDEKTSV4RRFFQ69G5FAV\", \"body\": \"# hi\"}")))
  (ok (null (codes "{\"title\": \"Hello\", \"eventAt\": \"2026-09-20T00:00:00Z\", \"featured\": false}"))
      "false boolean is fine"))

(deftest required
  (ok (equal (codes "{}") '(("title" . "required") ("eventAt" . "required"))))
  (ok (equal (codes "{\"title\": \"  \", \"eventAt\": null}")
             '(("title" . "required") ("eventAt" . "required")))
      "blank and null count as missing")
  (let ((model (make-model "note" :list (list (make-field :body :richtext :required t)))))
    (ok (null (validate-content model (parse-json "{\"body\": \"<p><br></p>\"}")))
        "rich text is blank as any string is: markup is a value")
    (ok (equal (mapcar (lambda (e) (getf e :code))
                       (validate-content model (parse-json "{\"body\": \" \\n \"}")))
               '("required")))
    (ok (null (validate-content model (parse-json "{\"body\": \"<p>a</p>\"}")))))
  (testing "partial skips missing fields"
    (ok (null (validate-content *model* (parse-json "{}") :partial t)))
    (ok (equal (mapcar (lambda (e) (getf e :code))
                       (validate-content *model* (parse-json "{\"title\": null}") :partial t))
               '("required")))))

(deftest false-and-empty-array-are-values
  (ok (equal (codes "{\"title\": false, \"eventAt\": \"2026-09-20T00:00:00Z\", \"count\": false}")
             '(("title" . "type") ("count" . "type")))
      "false is only a boolean")
  (ok (equal (codes "{\"title\": [], \"eventAt\": \"2026-09-20T00:00:00Z\"}")
             '(("title" . "type")))
      "[] on a single-value field")
  (ok (null (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T00:00:00Z\", \"labels\": [], \"tags\": []}"))
      "[] on a many field is blank"))

(deftest type-errors
  (ok (equal (codes "{\"title\": 1, \"eventAt\": \"nope\"}")
             '(("title" . "type") ("eventAt" . "type"))))
  (ok (null (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T19:00+09:00\"}"))
      "a datetime may leave out its seconds, in any zone")
  (ok (null (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T10:00Z\"}")))
  (ok (equal (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T10:00\"}")
             '(("eventAt" . "type")))
      "but not its zone")
  (ok (equal (codes "{\"title\": \"Toolongtitle!\", \"eventAt\": \"2026-09-20T00:00:00Z\"}")
             '(("title" . "max_length"))))
  (ok (equal (codes "{\"title\": \"lower\", \"eventAt\": \"2026-09-20T00:00:00Z\"}")
             '(("title" . "pattern"))))
  (ok (equal (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T00:00:00Z\", \"slug\": \"Not Slug\"}")
             '(("slug" . "slug"))))
  (ok (equal (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T00:00:00Z\", \"count\": 2.5}")
             '(("count" . "integer"))))
  (ok (equal (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T00:00:00Z\", \"count\": 11}")
             '(("count" . "max"))))
  (ok (equal (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T00:00:00Z\", \"featured\": \"yes\"}")
             '(("featured" . "type"))))
  (ok (equal (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T00:00:00Z\", \"day\": \"2026-9-20\"}")
             '(("day" . "type"))))
  (ok (equal (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-02-30T00:00:00Z\", \"day\": \"2026-02-30\"}")
             '(("day" . "type") ("eventAt" . "type")))
      "calendar-invalid dates are type errors, not crashes")
  (ok (equal (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20\"}")
             '(("eventAt" . "type")))
      "a datetime needs a time and a zone")
  (ok (null (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T09:00:00+09:00\"}")) "offsets are fine")
  (ok (equal (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T00:00:00Z\", \"category\": \"sports\"}")
             '(("category" . "option"))))
  (ok (equal (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T00:00:00Z\", \"labels\": \"a\"}")
             '(("labels" . "type")))
      "many requires an array")
  (ok (equal (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T00:00:00Z\", \"cover\": \"abc\\n\", \"slug\": \"ok\\n\", \"day\": \"2026-09-20\\n\"}")
             '(("slug" . "slug") ("day" . "type") ("cover" . "type")))
      "a trailing newline is not accepted by anchored patterns")
  (ok (equal (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T00:00:00Z\", \"tags\": [\"bad id!\"]}")
             '(("tags" . "type"))))
  (ok (equal (codes "{\"title\": \"Ok\", \"eventAt\": \"2026-09-20T00:00:00Z\", \"extra\": 1}")
             '(("extra" . "unknown_field")))))

(defparameter *with-seo*
  (schema-model
   (make-schema :custom-fields (list (make-custom-field "seo" (list (make-field :title :text :required t :max-length 5)
                                                                    (make-field :image :media)
                                                                    (make-field :indexed :boolean :required t))))
                :models (list (make-model "page" :list (list (make-field :meta :custom :custom-field "seo")))
                              (make-model "post" :list (list (make-field :meta :custom :custom-field "seo" :required t)))))
   "page"))

(defun seo-codes (json &optional (model *with-seo*))
  (mapcar (lambda (e) (cons (getf e :field) (getf e :code)))
          (validate-content model (parse-json json))))

(deftest a-custom-field-is-an-object-of-its-fields
  (ok (null (seo-codes "{\"meta\": {\"title\": \"Hi\", \"image\": \"01ARZ3NDEKTSV4RRFFQ69G5FAV\"}}")))
  (ok (null (seo-codes "{}")) "an optional one may be absent")
  (ok (equal (seo-codes "{\"meta\": \"Hi\"}") '(("meta" . "type"))) "it must be an object")
  (ok (equal (seo-codes "{\"meta\": {\"title\": \"Too long\", \"image\": 3}}")
             '(("meta.title" . "max_length") ("meta.image" . "type")))
      "each field inside is checked, and named by its path")
  (ok (equal (seo-codes "{\"meta\": {\"image\": \"01ARZ3NDEKTSV4RRFFQ69G5FAV\"}}") '(("meta.title" . "required")))
      "a required field inside is required once the object is there; a boolean never is")
  (ok (equal (seo-codes "{\"meta\": {\"title\": \"Hi\", \"extra\": 1}}") '(("meta.extra" . "unknown_field"))))
  (ok (equal (seo-codes "{\"meta\": {\"title\": false}}") '(("meta.title" . "type")))
      "false is no value only for a boolean")
  (ok (equal (seo-codes "{\"meta\": {\"bogus\": null}}") '(("meta.bogus" . "unknown_field") ("meta.title" . "required")))
      "and a key the custom field does not have is never blank")
  (let ((post (schema-model (make-schema :custom-fields (list (make-custom-field "seo" (list (make-field :title :text))))
                                         :models (list (make-model "post" :list (list (make-field :meta :custom :custom-field "seo" :required t)))))
                            "post")))
    (ok (equal (seo-codes "{}" post) '(("meta" . "required"))))
    (ok (equal (seo-codes "{\"meta\": {\"title\": \" \"}}" post) '(("meta" . "required")))
        "an object whose fields are all blank is no value")))
