(defpackage #:koya-server/api/v1/<space>/<model>/<id>
  (:use #:cl)
  (:import-from #:koya-server/lib/http #:path-param #:param #:fail-api)
  (:import-from #:koya-server/lib/auth #:require-delivery-key)
  (:import-from #:koya-server/domain/query #:parse-query #:query-fields #:query-include)
  (:import-from #:koya-server/features/contents/service #:resolve-model)
  (:import-from #:koya-server/features/contents/presenter #:content->jobject)
  (:import-from #:koya-server/domain/content #:content-published #:content-draft-key)
  (:import-from #:koya-server/db/contents #:find-content)
  (:export #:@get))
(in-package #:koya-server/api/v1/<space>/<model>/<id>)

(defun @get (params)
  (let ((space-name (path-param params :space))
        (model-name (path-param params :model))
        (id (path-param params :id)))
    (require-delivery-key space-name)
    (multiple-value-bind (space model) (resolve-model space-name model-name)
      (let* ((query (parse-query params))
             (content (find-content space-name model-name id))
             (draft-key (param params "draftKey"))
             (draft (and content draft-key (content-draft-key content)
                         (string= draft-key (content-draft-key content)))))
        (unless (and content (or draft (content-published content)))
          (fail-api 404 "not_found" "Content does not exist"))
        (content->jobject content model space :draft draft
                          :fields (query-fields query) :include (query-include query))))))
