(defpackage #:koya-server/api/v1/<space>/<model>/index
  (:use #:cl)
  (:import-from #:koya/core/schema #:model-kind)
  (:import-from #:koya/core/json #:jobject)
  (:import-from #:koya-server/lib/http #:path-param #:param #:fail-api)
  (:import-from #:koya-server/lib/auth #:require-delivery-key)
  (:import-from #:koya-server/domain/query
                #:parse-query #:query-limit #:query-offset #:query-fields #:query-include)
  (:import-from #:koya-server/features/contents/service #:resolve-model)
  (:import-from #:koya-server/features/contents/presenter #:content->jobject)
  (:import-from #:koya-server/domain/content #:content-published #:content-draft-key)
  (:import-from #:koya-server/db/contents #:list-contents #:find-object-content)
  (:export #:@get))
(in-package #:koya-server/api/v1/<space>/<model>/index)

(defun @get (params)
  (let ((space-name (path-param params :space))
        (model-name (path-param params :model)))
    (require-delivery-key space-name)
    (multiple-value-bind (space model) (resolve-model space-name model-name)
      (let ((query (parse-query params)))
        (if (eq (model-kind model) :object)
            (let* ((content (find-object-content space-name model-name))
                   (draft-key (param params "draftKey"))
                   (draft (and content draft-key (content-draft-key content)
                               (string= draft-key (content-draft-key content)))))
              (unless (and content (or draft (content-published content)))
                (fail-api 404 "not_found" "Content does not exist"))
              (content->jobject content model space :draft draft
                                :fields (query-fields query) :include (query-include query)))
            (multiple-value-bind (contents total) (list-contents space-name model-name model query)
              (jobject "contents" (map 'vector (lambda (c) (content->jobject c model space
                                                                             :fields (query-fields query)
                                                                             :include (query-include query)))
                                       contents)
                       "totalCount" total
                       "offset" (query-offset query)
                       "limit" (query-limit query))))))))
