(defpackage #:koya-tests/server/pages/content-list
  (:use #:cl #:rove)
  (:import-from #:koya-tests/server/pages/support #:post-login #:edit #:moved-to #:*secret* #:*cookie* #:blog-model #:request #:location #:setup-pages #:log-in)
  (:import-from #:koya-server/db/connection #:disconnect-db #:exec)
  (:import-from #:koya-server/db/contents #:list-contents #:content-status #:content-id #:content-draft-key)
  (:import-from #:koya-server/lib/query #:parse-query)
  (:import-from #:alexandria #:alist-hash-table)
  (:import-from #:koya-server/db/contents #:save-draft)
  (:import-from #:koya-server/db/media #:insert-media #:media-id)
  (:import-from #:koya-server/db/contents #:get-content #:content-published)
  (:import-from #:koya-server/features/contents/service #:resolve-model #:create)
  (:import-from #:koya/core/json #:jobject)
  (:import-from #:koya-tests/server/pages/support #:call-action)
  (:import-from #:koya-server/pages/s/<space>/m/<model>/index #:bulk-contents #:browse-contents))
(in-package #:koya-tests/server/pages/content-list)

(defun bulk (op ids &key (q "") (status "") (page 1))
  "Do OP to IDS as the list's bulk bar does; (values status body)."
  (call-action :post (bulk-contents :space "website" :model "blog" :op op :q q :status status :sort "" :page page)
               :form (mapcar (lambda (id) (cons "id" id)) ids)))

(setup (setup-pages) (log-in))

(teardown (disconnect-db))

(deftest list-paging
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (setf *cookie* nil)
    (post-login :form `(("secret" . ,*secret*)))
    ;; one more than a page holds, so there are two
    (dotimes (i 21)
      (edit "/s/website/m/blog/new" :form `(("action" . "save") ("f-title" . ,(format nil "Page filler ~3,'0d" i))) :headers origin))
    (multiple-value-bind (status body) (request :get "/s/website/m/blog")
      (ok (= status 200))
      (ok (search "Page 1 of 2" body))
      (ok (search "?page=2" body) "a link to the next page")
      (ok (search "Page filler 020" body) "newest first")
      (ok (not (search "Page filler 000" body)) "the oldest is on the next page"))
    (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query "page=2")
      (ok (= status 200))
      (ok (search "Page 2 of 2" body))
      (ok (search "Page filler 000" body))
      (ok (search "<a href=\"/s/website/m/blog\" hx-get=" body)
          "and back, to the list's own URL: page 1 is not a query"))
    (multiple-value-bind (status body headers) (request :get "/s/website/m/blog" :query "page=9")
      (declare (ignore body))
      (ok (= status 302) "a page past the end is the last page, not an empty one")
      (ok (string= (location headers) "/s/website/m/blog?page=2") "redirected to the last"))
    (exec "DELETE FROM contents WHERE json_extract(COALESCE(draft, published), '$.title') LIKE 'Page filler %'")))

(deftest list-search-filter-and-sort
  (let* ((origin '(("origin" . "http://localhost:3000")))
         (query '(("orders" . "-createdAt"))))
    (setf *cookie* nil)
    (post-login :form `(("secret" . ,*secret*)))
    (labels ((newest ()
               (content-id (first (list-contents "website" "blog" (blog-model) (parse-query query) :status :all))))
             (save (title body)
               (edit "/s/website/m/blog/new"
                         :form `(("action" . "save") ("f-title" . ,title) ("f-body" . ,body))
                        :headers origin)
               (newest))
             (post (id action title)
               (edit (format nil "/s/website/m/blog/~a" id)
                         :form `(("action" . ,action) ("f-title" . ,title) ("f-body" . "<p>x</p>"))
                        :headers origin))
             (before-p (body a b) (< (search a body) (search b body))))
      (let ((alpha (save "Alpha" "<p>a needle in the body</p>"))
            (beta (save "Beta" "<p>b</p>"))
            (gamma (save "Gamma" "<p>c</p>")))
        (post beta "publish" "Beta")
        (post gamma "publish" "Gamma")
        (post gamma "save" "Gamma")
        (testing "the list carries the search box and the status filter"
          (multiple-value-bind (status body) (request :get "/s/website/m/blog")
            (ok (= status 200))
            (ok (search "name=\"q\"" body))
            (ok (search "<option value=\"published+draft\"" body) "the choices are the badges")
            (ok (search "3 contents" body))
            (ng (search "Clear" body) "nothing to clear when nothing is filtered")
            (ok (and (search "Alpha" body) (search "Beta" body) (search "Gamma" body)))))
        (testing "search matches the text fields, the body and the id"
          (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query "q=Alpha")
            (ok (= status 200))
            (ok (search "Alpha" body))
            (ng (search ">Beta<" body))
            (ok (search "1 of 3" body) "the count says what was narrowed from")
            (ok (search "Clear" body)))
          (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query "q=needle")
            (ok (= status 200))
            (ok (search "Alpha" body) "a richtext body is searched as well")
            (ng (search ">Beta<" body)))
          (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query (format nil "q=~a" beta))
            (ok (= status 200))
            (ok (search "Beta" body) "pasting an id finds its content")
            (ng (search ">Alpha<" body)))
          (multiple-value-bind (status body)
              (request :get "/s/website/m/blog" :query (format nil "q=~a" (subseq beta 0 6)))
            (ok (= status 200))
            (ok (search "Nothing matches this search." body)
                "a fragment of an id matches nothing: every id of the same period shares its prefix"))
          (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query "q=nothingmatchesthis")
            (ok (= status 200))
            (ok (search "Nothing matches this search." body))))
        (testing "the status filter is the badge"
          (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query "status=draft")
            (ok (= status 200))
            (ok (search "Alpha" body))
            (ng (search ">Beta<" body)))
          (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query "status=published")
            (ok (= status 200))
            (ok (search "Beta" body))
            (ng (search ">Alpha<" body))
            (ng (search ">Gamma<" body) "a published content with a draft is its own badge"))
          (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query "status=published%2Bdraft")
            (ok (= status 200))
            (ok (search "Gamma" body))
            (ng (search ">Alpha<" body)))
          (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query "status=nonsense")
            (ok (= status 200))
            (ok (search "3 contents" body) "a status nothing can have is no filter at all")))
        (testing "a column header sorts by its field, and sorts back"
          (multiple-value-bind (status body) (request :get "/s/website/m/blog")
            (ok (= status 200))
            (ok (search "?sort=title" body) "every column offers its own order")
            (ok (before-p body "Gamma" "Alpha") "newest created first until asked otherwise"))
          (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query "sort=title")
            (ok (= status 200))
            (ok (before-p body "Alpha" "Gamma"))
            (ok (search "?sort=-title" body) "and the same header turns it around"))
          (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query "sort=-title")
            (ok (= status 200))
            (ok (before-p body "Gamma" "Alpha")))
          (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query "sort=nosuchfield")
            (ok (= status 200))
            (ok (before-p body "Gamma" "Alpha") "a stale link falls back to the default order")))
        (testing "the three are one state, and the links carry it"
          (multiple-value-bind (status body)
              (request :get "/s/website/m/blog" :query "q=a&status=draft&sort=title")
            (ok (= status 200))
            (ok (search "Alpha" body))
            (ok (search "q=a" body) "the header links keep the search")
            (ok (search "status=draft" body) "and the filter")
            (ok (search "value=\"title\"" body) "and the sort survives a new filter")))
        (dolist (id (list alpha beta gamma))
          (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "delete")) :headers origin))
        (testing "an empty list says which of the three left it empty"
          (multiple-value-bind (status body) (request :get "/s/website/m/blog" :query "status=draft")
            (ok (= status 200))
            (ok (search "No contents with this status." body) "a filter is not a search"))
          (multiple-value-bind (status body headers) (request :get "/s/website/m/blog" :query "q=x&page=9")
            (declare (ignore body))
            (ok (= status 302))
            (ok (search "q=x" (location headers))
                "paging past the end of a search comes back to the search, not to an empty page")))))))

(deftest list-columns-are-bounded
  (multiple-value-bind (status body headers)
      (edit "/s/website/m/blog/new" :form '(("action" . "save") ("f-title" . "Columns") ("f-body" . "<p>x</p>"))
               :headers '(("origin" . "http://localhost:3000")))
    (declare (ignore body))
    (ok (= status 200))
    (let ((path (subseq (moved-to headers) 0 (position #\? (moved-to headers)))))
      (multiple-value-bind (status body) (request :get "/s/website/m/blog")
        (ok (= status 200))
        (ok (search ">related<" body) "every field keeps its column")
        (ok (search "min-w-16 max-w-20" body) "a boolean column stays narrow")
        (ok (search "min-w-36 max-w-64" body) "a richtext column is allowed to be wide")
        (ok (search "line-clamp-2" body) "a preview is clamped to two lines")
        (ok (search "h-14" body) "every row is the same height")
        (ok (< (search ">status<" body) (search ">title<" body)) "status leads the row"))
      (edit path :form '(("action" . "delete")) :headers '(("origin" . "http://localhost:3000"))))))

(deftest list-shows-media-as-images
  (let ((origin '(("origin" . "http://localhost:3000")))
        (media (insert-media "website" :filename "cover.png" :mime "image/png" :size 10
                                       :width 1 :height 1 :alt "A red door"))
        (paths '()))
    (flet ((save (title cover)
             (multiple-value-bind (status body headers)
                 (edit "/s/website/m/blog/new"
                           :form `(("action" . "save") ("f-title" . ,title) ("f-cover" . ,cover))
                          :headers origin)
               (declare (ignore status body))
               (push (subseq (moved-to headers) 0 (position #\? (moved-to headers))) paths))))
      (save "With cover" (media-id media))
      (save "Lost cover" "01MISSINGMEDIA0000000000000")
      (save "No cover" "")
      (multiple-value-bind (status body) (request :get "/s/website/m/blog")
        (ok (= status 200))
        (ok (search (format nil "src=\"/media/website/~a.png\"" (media-id media)) body)
            "a media field is its image, the original file")
        (ok (search "alt=\"A red door\"" body) "with the media's alt")
        (ok (search "loading=\"lazy\"" body))
        (ok (search "01MISSINGMEDIA0000000000000 (missing)" body)
            "an id no longer in the library says so, not a broken image")
        (ng (search "src=\"/media/website/01MISSINGMEDIA" body))
        (ok (search "min-w-24 max-w-36" body) "the media column keeps its bounds"))
      (dolist (path paths)
        (edit path :form '(("action" . "delete")) :headers origin)))))

(deftest list-shows-references-by-label
  (exec "DELETE FROM contents")
  (multiple-value-bind (space model) (resolve-model "website" "blog")
    (flet ((make (title &rest data)
             (content-id (create space model (apply #'jobject "title" title data) :publish t))))
      (let ((alpha (make "Alpha target"))
            (beta (make "Beta target")))
        (make "Refers" "related" (vector alpha beta))
        (multiple-value-bind (status body) (request :get "/s/website/m/blog")
          (ok (= status 200))
          (ok (search "Alpha target, Beta target" body)
              "a reference reads as the label of what it points at, looked up for the page's rows")))))
  (exec "DELETE FROM contents"))

(deftest bulk-actions-on-the-content-list
  (let ((origin '(("origin" . "http://localhost:3000")))
        (query '(("orders" . "-createdAt"))))
    (setf *cookie* nil)
    (post-login :form `(("secret" . ,*secret*)))
    (labels ((save (title)
               (edit "/s/website/m/blog/new"
                         :form `(("action" . "save") ("f-title" . ,title) ("f-body" . "<p>x</p>"))
                        :headers origin)
               (content-id (first (list-contents "website" "blog" (blog-model) (parse-query query) :status :all))))
             (status-of (id) (content-status (find id (list-contents "website" "blog" (blog-model)
                                                                     (parse-query query) :status :all)
                                                   :key #'content-id :test #'string=))))
      (let ((one (save "Bulk one"))
            (two (save "Bulk two"))
            (three (save "Bulk three")))
        (testing "the list offers a box per row and one for the page"
          (multiple-value-bind (status body) (request :get "/s/website/m/blog")
            (ok (= status 200))
            (ok (search "data-bulk-all" body))
            (ok (search (format nil "name=\"id\" data-bulk-item value=\"~a\"" one) body)
                "each row carries its id")
            (ok (search "data-bulk-bar hidden" body) "the bar waits for a selection")
            (ok (search "op=publish" body))
            (ok (search "op=unpublish" body))
            (ok (search "hx-confirm=\"Delete the selected contents?" body))))
        (testing "publishing a selection publishes each of them"
          (multiple-value-bind (status body) (bulk "publish" (list one two))
            (ok (= status 200))
            (ok (search "id=\"contents\"" body) "the list is drawn again")
            (ok (search "Published 2 contents." body)))
          (ok (string= (status-of one) "published"))
          (ok (string= (status-of two) "published"))
          (ok (string= (status-of three) "draft") "and leaves the rest alone"))
        (testing "unpublishing takes them back off"
          (bulk "unpublish" (list one))
          (ok (string= (status-of one) "draft"))
          (ok (string= (status-of two) "published")))
        (testing "an action with nothing to do to a content leaves it alone and says so"
          ;; TWO is published with no draft: publishing it again would give it a
          ;; new revisedAt and fire a webhook for a change that did not happen
          (ok (search "Published 0 contents. 1 was already published." (nth-value 1 (bulk "publish" (list two)))))
          ;; ONE is a draft: unpublishing it would reissue its draft key and break
          ;; a preview link someone is holding
          (let ((key (content-draft-key (find one (list-contents "website" "blog" (blog-model)
                                                                 (parse-query query) :status :all)
                                              :key #'content-id :test #'string=))))
            (ok (search "Unpublished 0 contents. 1 was not published." (nth-value 1 (bulk "unpublish" (list one)))))
            (ok (string= key (content-draft-key (find one (list-contents "website" "blog" (blog-model)
                                                                        (parse-query query) :status :all)
                                                      :key #'content-id :test #'string=)))
                "and the preview link it was holding still works")))
        (testing "the list comes back under the filters it was read with"
          (multiple-value-bind (status body headers) (bulk "unpublish" (list two) :q "Bulk" :status "published")
            (declare (ignore status))
            (ok (string= (getf headers :hx-replace-url) "/s/website/m/blog?q=Bulk&status=published")
                "the URL keeps the search and the filter")
            (ok (search "Nothing matches this search." body) "which now matches nothing")))
        (testing "one that cannot be done leaves the others done, and says so"
          ;; a title is required, so a draft saved without one cannot be published
          (koya-server/db/contents:save-draft three (alist-hash-table '(("body" . "<p>no title</p>")) :test 'equal))
          (let ((body (nth-value 1 (bulk "publish" (list one three)))))
            (ok (search "Published 1 content. 1 could not be: title is required." body)
                "the field that stopped it, not the condition's own report"))
          (ok (string= (status-of one) "published") "the one that could be"))
        (testing "nothing selected is not an action"
          (ok (search "Nothing was selected." (nth-value 1 (bulk "publish" nil)))))
        (testing "deleting a selection deletes each of them"
          (bulk "delete" (list one two three))
          (ok (null (list-contents "website" "blog" (blog-model) (parse-query query) :status :all))))
        (testing "an action the list does not offer is refused"
          (ok (= 404 (bulk "burn" (list one)))))
        (testing "the page takes no posts"
          (ok (= 404 (request :post "/s/website/m/blog" :form '(("op" . "publish")) :headers origin))))))))


(deftest bulk-actions-leave-a-referenced-content
  (exec "DELETE FROM contents")
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (multiple-value-bind (space model) (resolve-model "website" "blog")
      (flet ((make (title &rest data)
               (content-id (create space model (apply #'jobject "title" title data) :publish t))))
        (let* ((target (make "Target"))
               (other (make "Other"))
               (referrer (make "Refers" "related" (vector target))))
          (testing "unpublishing a selection skips the one another refers to"
            (ok (search "Unpublished 1 content. 1 could not be: This content is referenced by 1 other content"
                        (nth-value 1 (bulk "unpublish" (list target other)))))
            (ok (content-published (get-content target)) "it is still published")
            (ng (content-published (get-content other)) "the rest of the selection went"))
          (testing "deleting a selection does the same"
            (bulk "delete" (list target referrer))
            (ok (get-content target) "refused while the referrer was still there")
            (ng (get-content referrer))
            (bulk "delete" (list target))
            (ng (get-content target) "and it goes once nothing refers to it")))))))

(deftest the-list-is-read-in-place
  (exec "DELETE FROM contents")
  (multiple-value-bind (space model) (resolve-model "website" "blog")
    (dolist (title '("Apple" "Banana" "Cherry"))
      (create space model (jobject "title" title) :publish (string= title "Banana"))))
  (flet ((browse (&rest args)
           (call-action :get (apply #'browse-contents :space "website" :model "blog" args))))
    (testing "the page's controls call the action"
      (let ((body (nth-value 1 (request :get "/s/website/m/blog"))))
        (ok (search "id=\"filters\"" body))
        (ok (search "input changed delay:300ms" body) "the search goes as the typing stops")
        (ok (search "change from:'find select'" body) "and the status as it is picked")
        (ng (search ">Filter<" body) "so there is no button to press")
        (ok (search (subseq (browse-contents) 0 (position #\? (browse-contents))) body)
            "the headers and the pager too")))
    (testing "a search draws #contents, the count and the sort, and puts the state in the URL"
      (multiple-value-bind (status body headers) (browse :q "an" :status "" :sort "title" :page 1)
        (ok (= status 200))
        (ok (search "id=\"contents\"" body))
        (ok (search "Banana" body))
        (ng (search ">Cherry<" body))
        (ok (search "id=\"content-count\" class=\"ml-3 text-base font-normal text-muted\" hx-swap-oob=\"true\"" body))
        (ok (search "1 of 3" body))
        (ok (search "id=\"filter-sort\" name=\"sort\" value=\"title\" hx-swap-oob=\"true\"" body)
            "the sort the filters send, out of band")
        (ng (search "id=\"filters\"" body) "but not the box being typed in")
        (ok (string= (getf headers :hx-replace-url) "/s/website/m/blog?q=an&sort=title"))))
    (testing "clearing puts the filters back empty"
      (multiple-value-bind (status body headers) (browse :q "" :status "" :sort "" :page 1 :clear "1")
        (ok (= status 200))
        (ok (search "id=\"filters\"" body))
        (ok (search "value=\"\" placeholder=\"Search text and ids\"" body))
        (ok (string= (getf headers :hx-replace-url) "/s/website/m/blog"))))
    (testing "a page past the end is the last one"
      (ok (string= (getf (nth-value 2 (browse :q "" :status "" :sort "" :page 9)) :hx-replace-url) "/s/website/m/blog")))
    (testing "an object model has no list"
      (ok (= 404 (call-action :get (browse-contents :space "website" :model "about")))))))
