(defpackage #:koya-tests/server/pages/login
  (:use #:cl #:rove)
  (:import-from #:koya-tests/server/pages/support #:*secret* #:*cookie* #:*set-cookie* #:request #:location #:setup-pages #:log-in)
  (:import-from #:koya-server/db/connection #:disconnect-db #:fetch-one #:col)
  (:import-from #:koya-server/db/delivery-keys #:list-delivery-keys)
  (:import-from #:koya-server/db/delivery-keys #:list-delivery-keys)
  (:import-from #:koya-server/lib/totp #:totp #:*totp-last-counter*)
  (:import-from #:koya-server/lib/auth #:clear-login-failures))
(in-package #:koya-tests/server/pages/login)

(setup (setup-pages) (log-in))

(teardown (disconnect-db))

(deftest health
  (let ((*cookie* nil))
    (multiple-value-bind (status body) (request :get "/health")
      (ok (= status 200))
      (ok (search "ok" body)))))

(deftest login-flow
  (setf *cookie* nil)
  (multiple-value-bind (status body headers) (request :get "/")
    (declare (ignore body))
    (ok (= status 302))
    (ok (string= (location headers) "/login")))
  (multiple-value-bind (status body) (request :get "/login")
    (ok (= status 200))
    (ok (search "Owner secret" body)))
  (multiple-value-bind (status body) (request :post "/login" :form '(("secret" . "nope")))
    (ok (= status 401))
    (ok (search "Wrong secret" body)))
  (multiple-value-bind (status body headers) (request :post "/login" :form `(("secret" . ,*secret*)))
    (declare (ignore body))
    (ok (= status 303))
    (ok (string= (location headers) "/"))
    (ok *cookie* "session cookie set")
    (ok (search "HttpOnly" *set-cookie*) "cookie is HttpOnly")
    (ok (search "SameSite=Lax" *set-cookie*) "cookie is SameSite=Lax")
    (ok (col (fetch-one "SELECT count(*) AS n FROM sessions") "n")
        "the session is in the database, not only in the process"))
  (multiple-value-bind (status body) (request :get "/")
    (ok (= status 200))
    (ok (search "website" body) "space listed"))
  (testing "two-factor login when KOYA_TOTP_SECRET is set"
    (let ((secret "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ"))
      (setf (uiop:getenv "KOYA_TOTP_SECRET") secret
            *totp-last-counter* -1)
      (unwind-protect
           (let ((*cookie* nil))
             (multiple-value-bind (status body) (request :get "/login")
               (ok (= status 200))
               (ok (search "One-time code" body) "the form asks for a code"))
             (multiple-value-bind (status body) (request :post "/login" :form `(("secret" . ,*secret*)))
               (ok (= status 401))
               (ok (search "one-time code" body) "secret alone is not enough"))
             (multiple-value-bind (status body) (request :post "/login" :form `(("secret" . "nope") ("code" . ,(totp secret))))
               (ok (= status 401))
               (ok (search "Wrong secret" body) "a wrong secret is reported as such, and does not consume the code"))
             (let ((code (totp secret)))
               (multiple-value-bind (status body headers) (request :post "/login" :form `(("secret" . ,*secret*) ("code" . ,code)))
                 (declare (ignore body))
                 (ok (= status 303))
                 (ok (string= (location headers) "/")))
               (let ((*cookie* nil))
                 (multiple-value-bind (status body) (request :post "/login" :form `(("secret" . ,*secret*) ("code" . ,code)))
                   (ok (= status 401))
                   (ok (search "one-time code" body) "the same code cannot log in twice")))))
        (setf (uiop:getenv "KOYA_TOTP_SECRET") ""))))
  (testing "cross-origin posts are rejected"
    (multiple-value-bind (status) (request :post "/logout" :headers '(("origin" . "https://evil.example")))
      (ok (= status 403)))
    (multiple-value-bind (status) (request :post "/s/website/keys" :form '(("action" . "create")) :headers '(("origin" . "https://evil.example")))
      (ok (= status 403)))
    (multiple-value-bind (status) (request :post "/logout" :headers '(("origin" . "null")))
      (ok (= status 403) "an opaque origin is not 'no origin'")))
  (testing "same-origin post is fine"
    (multiple-value-bind (status body) (request :post "/s/website/keys" :form '(("action" . "create") ("label" . "ui"))
                                                :headers '(("origin" . "http://localhost:3000")))
      (ok (= status 200))
      (ok (search "koya_" body) "new key shown once")
      (ok (search "Webhook secret" body))))
  (testing "delete and rotate redirect instead of re-rendering"
    (let ((id (getf (first (list-delivery-keys "website")) :id)))
      (multiple-value-bind (status body headers)
          (request :post "/s/website/keys" :form `(("action" . "delete") ("id" . ,id)) :headers '(("origin" . "http://localhost:3000")))
        (declare (ignore body))
        (ok (= status 303))
        (ok (string= (location headers) "/s/website/keys")))
      (multiple-value-bind (status body) (request :get "/s/website/keys")
        (ok (= status 200))
        (ok (search "Key deleted." body) "flash shown after the redirect")))
    (multiple-value-bind (status body headers)
        (request :post "/s/website/keys" :form '(("action" . "rotate-webhook-secret")) :headers '(("origin" . "http://localhost:3000")))
      (declare (ignore body))
      (ok (= status 303))
      (ok (string= (location headers) "/s/website/keys")))))

(deftest login-returns-to-the-page
  (let ((*cookie* nil))
    (multiple-value-bind (status body headers) (request :get "/s/website/media" :query "page=2")
      (declare (ignore body))
      (ok (= status 302))
      (ok (string= (location headers) "/login?next=%2Fs%2Fwebsite%2Fmedia%3Fpage%3D2")))
    (multiple-value-bind (status body) (request :get "/login" :query "next=%2Fs%2Fwebsite%2Fmedia%3Fpage%3D2")
      (ok (= status 200))
      (ok (search "name=\"next\" value=\"/s/website/media?page=2\"" body) "the form carries it"))
    (multiple-value-bind (status body headers)
        (request :post "/login" :form `(("secret" . ,*secret*) ("next" . "/s/website/media?page=2")))
      (declare (ignore body))
      (ok (= status 303))
      (ok (string= (location headers) "/s/website/media?page=2"))))
  (testing "a form post returns to the page the form was on"
    (let ((*cookie* nil))
      (multiple-value-bind (status body headers)
          (request :post "/s/website/keys" :form '(("action" . "create"))
                   :headers '(("referer" . "http://localhost:3000/s/website/keys")))
        (declare (ignore body))
        (ok (= status 302))
        (ok (string= (location headers) "/login?next=%2Fs%2Fwebsite%2Fkeys")))))
  (testing "next never leaves the server"
    (dolist (next '("//evil.test/" "/\\evil.test/" "https://evil.test/" "evil"))
      (let ((*cookie* nil))
        (multiple-value-bind (status body headers)
            (request :post "/login" :form `(("secret" . ,*secret*) ("next" . ,next)))
          (declare (ignore body))
          (ok (= status 303))
          (ok (string= (location headers) "/") next))))))

(deftest login-lockout
  (let ((*cookie* nil))
    (clear-login-failures "127.0.0.1")
    (dotimes (i 5)
      (multiple-value-bind (status) (request :post "/login" :form '(("secret" . "nope")))
        (ok (= status 401))))
    (multiple-value-bind (status body) (request :post "/login" :form `(("secret" . ,*secret*)))
      (ok (= status 403) "even the right secret is refused while locked")
      (ok (search "Too many attempts" body)))
    (clear-login-failures "127.0.0.1")
    (multiple-value-bind (status) (request :post "/login" :form `(("secret" . ,*secret*)))
      (ok (= status 303) "logs in again once the lock is cleared"))))

