(defpackage #:koya-tests/server/pages/media
  (:use #:cl #:rove)
  (:import-from #:koya-tests/server/pages/support #:*secret* #:*cookie* #:blog-model #:request #:location #:request-url #:setup-pages #:log-in)
  (:import-from #:koya-server/db/connection #:disconnect-db)
  (:import-from #:koya-server/db/contents #:list-contents #:content-id)
  (:import-from #:koya-server/db/media #:list-media #:media-id #:media-filename)
  (:import-from #:koya-server/actions/media-picker #:media-picker #:media-picker-upload)
  (:import-from #:koya-tests/server/media #:png-bytes)
  (:import-from #:koya-server/lib/query #:parse-query)
  (:import-from #:babel #:string-to-octets))
(in-package #:koya-tests/server/pages/media)

(setup (setup-pages) (log-in))

(teardown (disconnect-db))

(deftest media-library
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (multiple-value-bind (status body) (request :get "/s/website/media")
      (ok (= status 200))
      (ok (search "No media yet" body)))
    (testing "upload from the library page"
      (multiple-value-bind (status body headers)
          (request :post "/s/website/media" :headers origin
                   :multipart (list (list "action" "upload") (list "alt" "Cover")
                                    (list "file" "cover.png" "image/png" (png-bytes 4 4))
                                    (list "file" "second.png" "image/png" (png-bytes 8 8))))
        (declare (ignore body))
        (ok (= status 303))
        (ok (string= (location headers) "/s/website/media")))
      (multiple-value-bind (status body) (request :get "/s/website/media")
        (ok (= status 200))
        (ok (search "Uploaded 2 files." body))
        (ok (search "cover.png" body))
        (ok (search "4×4" body))
        (ok (search "<dialog id=\"media-preview\"" body) "preview modal is on the page")
        (ok (search "data-preview-src=\"/media/website/" body) "cards open it")
        (ok (search "/media/website/" body)))
      (multiple-value-bind (status body) (request :get "/s/website/media" :query "q=second")
        (ok (= status 200))
        (ok (search "second.png" body))
        (ok (not (search "cover.png" body)) "search narrows the grid"))
      (multiple-value-bind (status body)
          (request :post "/s/website/media" :headers origin
                   :multipart (list (list "action" "upload") (list "file" "notes.txt" "text/plain" (babel:string-to-octets "hi"))))
        (declare (ignore body))
        (ok (= status 303)))
      (multiple-value-bind (status body) (request :get "/s/website/media")
        (ok (= status 200))
        (ok (search "Only PNG, JPEG, GIF and WebP" body) "rejection shows as a flash")))
    (testing "editor offers the picker for a :media field"
      (multiple-value-bind (status body) (request :get "/s/website/m/blog/new")
        (ok (= status 200))
        (ok (search "data-media-pick-for=\"f-cover\"" body))
        (ok (search "<dialog id=\"media-picker\"" body))
        (ok (search (media-picker :space "website") body) "dialog knows the picker URL")))
    (testing "picker fragment"
      (multiple-value-bind (status body) (request-url :get (media-picker :space "website"))
        (ok (= status 200))
        (ok (search "data-pick-id=" body))
        (ok (search "data-pick-url=\"/media/website/" body))
        (ok (not (search "<html" body)) "a fragment, not a page")
        ;; htmx 4 reads an unquoted from:find input as from:find plus a modifier
        (ok (search "from:'find input'" body) "trigger selectors are quoted")
        (ok (search "from:'find input[type=file]'" body)))
      (let ((*cookie* nil))
        (multiple-value-bind (status) (request-url :get (media-picker :space "website"))
          (ok (= status 403) "the picker needs the owner session"))))
    (testing "picker upload"
      (flet ((upload (name &rest args)
               (apply #'request-url :post (media-picker-upload :space "website")
                      :multipart (list (list "file" name "image/png" (png-bytes 2 2)))
                      args)))
        (multiple-value-bind (status body) (upload "picked.png" :headers origin)
          (ok (= status 200))
          (ok (search "picked.png" body) "the new file is in the returned grid"))
        (let ((*cookie* nil))
          (ok (= (upload "anon.png" :headers origin) 403) "uploading needs the owner session"))
        (ok (= (upload "cross.png" :headers '(("origin" . "https://evil.test"))) 403)
            "a cross-origin upload is rejected")
        (ok (null (list-media "website" :search "anon")))
        (ok (null (list-media "website" :search "cross")))))
    (testing "every action is behind the owner session"
      (let ((*cookie* nil))
        (ok (= (request :get "/actions/not-an-action-000000") 403)
            "the gate is at the mount, not in each action")))
    (testing "alt and delete"
      (let ((id (media-id (first (list-media "website" :search "cover")))))
        (multiple-value-bind (status body headers)
            (request :post "/s/website/media" :form `(("action" . "alt") ("id" . ,id) ("alt" . "New alt")) :headers origin)
          (declare (ignore body))
          (ok (= status 303))
          (ok (string= (location headers) "/s/website/media")))
        (multiple-value-bind (status body) (request :get "/s/website/media")
          (ok (= status 200))
          (ok (search "data-preview-alt=\"New alt\"" body) "the dialog opens with the file's alt text"))
        (multiple-value-bind (status body headers)
            (request :post "/s/website/media" :form `(("action" . "delete") ("id" . ,id)) :headers origin)
          (declare (ignore body))
          (ok (= status 303))
          (ok (string= (location headers) "/s/website/media")))
        (ok (null (list-media "website" :search "cover")))))))

(deftest bulk-delete-in-the-media-library
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (setf *cookie* nil)
    (request :post "/login" :form `(("secret" . ,*secret*)))
    (flet ((upload (name)
             (request :post "/s/website/media" :headers origin
                      :multipart (list (list "action" "upload")
                                       (list "file" name "image/png" (png-bytes))))
             ;; found by name: two uploads in the same millisecond carry ULIDs
             ;; that do not say which came first, so "the newest" is not one of them
             (media-id (find name (list-media "website") :key #'media-filename :test #'string=))))
      (let ((a (upload "bulk-a.png"))
            (b (upload "bulk-b.png")))
        (testing "every card carries a box, tied to the selection form"
          (multiple-value-bind (status body) (request :get "/s/website/media")
            (ok (= status 200))
            (ok (search "Select all on this page" body))
            (ok (search "id=\"media-bulk\"" body))
            (ok (search (format nil "name=\"id\" value=\"~a\" form=\"media-bulk\"" a) body)
                "the box posts to the form outside the card, because forms do not nest")
            (ok (search "value=\"delete-selected\"" body))))
        (testing "deleting a selection deletes each file"
          (multiple-value-bind (status body headers)
              (request :post "/s/website/media"
                       :form `(("action" . "delete-selected") ("id" . ,a) ("id" . ,b) ("q" . "bulk"))
                       :headers origin)
            (declare (ignore body))
            (ok (= status 303))
            (ok (string= (location headers) "/s/website/media?page=1&q=bulk")
                "and comes back to the search it was made from"))
          (ok (null (list-media "website" :search "bulk")) "both gone"))
        (testing "a file a content still uses stays, and the rest still go"
          (let* ((kept (upload "bulk-kept.png"))
                 (other (upload "bulk-other.png")))
            (request :post "/s/website/m/blog/new"
                     :form `(("action" . "save") ("f-title" . "Uses an image") ("f-cover" . ,kept))
                     :headers origin)
            (request :post "/s/website/media"
                     :form `(("action" . "delete-selected") ("id" . ,kept) ("id" . ,other))
                     :headers origin)
            (multiple-value-bind (status body) (request :get "/s/website/media")
              (declare (ignore status))
              (ok (search "Deleted 1 of 2; 1 could not be" body))
              (ok (search "is used by 1 content" body) "and says which and why"))
            (ok (find kept (list-media "website") :key #'media-id :test #'string=) "the one in use is still there")
            (ng (find other (list-media "website") :key #'media-id :test #'string=))
            ;; clear up
            (let ((content (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
              (request :post (format nil "/s/website/m/blog/~a" (content-id content))
                       :form '(("action" . "delete")) :headers origin))
            (request :post "/s/website/media" :form `(("action" . "delete") ("id" . ,kept)) :headers origin)))
        (testing "nothing selected is not an action"
          (request :post "/s/website/media" :form '(("action" . "delete-selected")) :headers origin)
          (multiple-value-bind (status body) (request :get "/s/website/media")
            (declare (ignore status))
            (ok (search "Nothing was selected." body))))))))

