(defpackage #:koya-tests/server/pages/media
  (:use #:cl #:rove)
  (:import-from #:koya-tests/server/pages/support
                #:post-login #:edit #:moved-to #:*secret* #:*cookie* #:blog-model #:request
                #:location #:request-url #:call-action #:setup-pages #:log-in)
  (:import-from #:koya-server/db/connection #:disconnect-db)
  (:import-from #:koya-server/db/contents #:list-contents #:content-id)
  (:import-from #:koya-server/db/media #:list-media #:media-id #:media-filename)
  (:import-from #:koya-server/ui/media/picker #:media-picker #:media-picker-upload)
  (:import-from #:koya-server/pages/s/<space>/media
                #:browse-media #:upload-media #:delete-media-action #:delete-selected-media #:preview-media #:save-alt)
  (:import-from #:koya-tests/server/features/media/store #:png-bytes)
  (:import-from #:koya-server/lib/query #:parse-query)
  (:import-from #:babel #:string-to-octets))
(in-package #:koya-tests/server/pages/media)

(setup (setup-pages) (log-in))

(teardown (disconnect-db))

(deftest media-library
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (multiple-value-bind (status body) (request :get "/s/website/media")
      (ok (= status 200))
      (ok (search "No media yet" body)))
    (testing "upload from the library page"
      (multiple-value-bind (status body)
          (call-action :post (upload-media :space "website" :q "" :page 1)
                       :multipart (list (list "file" "cover.png" "image/png" (png-bytes 4 4))
                                        (list "file" "second.png" "image/png" (png-bytes 8 8))))
        (ok (= status 200))
        (ok (search "id=\"library\"" body) "the library is drawn again")
        (ok (search "Uploaded 2 files." body))
        (ok (search "cover.png" body)))
      (multiple-value-bind (status body) (request :get "/s/website/media")
        (ok (= status 200))
        (ok (search "<dialog id=\"media-preview\"" body) "preview modal is on the page")
        (ok (search (subseq (preview-media) 0 (position #\? (preview-media))) body) "cards ask for it")
        (ok (search "/media/website/" body)))
      (multiple-value-bind (status body) (request :get "/s/website/media" :query "q=second")
        (ok (= status 200))
        (ok (search "second.png" body))
        (ok (not (search "cover.png" body)) "search narrows the grid"))
      (multiple-value-bind (status body headers) (call-action :get (browse-media :space "website" :q "second" :page 1))
        (ok (= status 200))
        (ok (search "id=\"library\"" body) "a search is answered in place")
        (ok (search "second.png" body))
        (ng (search "cover.png" body))
        (ok (search "id=\"media-count\" class=\"ml-3 text-base font-normal text-muted\" hx-swap-oob=\"true\">1 file<" body)
            "with the count out of band")
        (ng (search "Search file names" body) "and not the box being typed in")
        (ok (string= (getf headers :hx-replace-url) "/s/website/media?q=second")))
      (ok (search "input changed delay:300ms" (nth-value 1 (request :get "/s/website/media")))
          "the box searches as the typing stops")
      (multiple-value-bind (status body)
          (call-action :post (upload-media :space "website" :q "" :page 1)
                       :multipart (list (list "file" "notes.txt" "text/plain" (babel:string-to-octets "hi"))))
        (ok (= status 200))
        (ok (search "Only PNG, JPEG, GIF and WebP" body) "rejection shows as a toast")))
    (testing "editor offers the picker for a :media field"
      (multiple-value-bind (status body) (request :get "/s/website/m/blog/new")
        (ok (= status 200))
        (ok (search "data-media-pick-for=\"f-cover\"" body))
        (ok (search "<dialog id=\"media-picker\"" body))
        (ok (search (media-picker :space "website") body) "dialog knows the picker URL")))
    (testing "picker fragment"
      (multiple-value-bind (status body) (call-action :get (media-picker :space "website"))
        (ok (= status 200))
        (ok (search "data-pick-id=" body))
        (ok (search "data-pick-url=\"/media/website/" body))
        (ok (not (search "<html" body)) "a fragment, not a page")
        ;; htmx 4 reads an unquoted from:find input as from:find plus a modifier
        (ok (search "from:'find input'" body) "trigger selectors are quoted")
        (ok (search "from:'find input[type=file]'" body)))
      (let ((*cookie* nil))
        (multiple-value-bind (status) (call-action :get (media-picker :space "website"))
          (ok (= status 401) "the picker needs the owner session")))
      (ok (= (request-url :get (media-picker :space "website")) 400)
          "an action answers htmx only: a plain request is refused"))
    (testing "picker upload"
      (flet ((upload (name &rest args)
               (apply #'call-action :post (media-picker-upload :space "website")
                      :multipart (list (list "file" name "image/png" (png-bytes 2 2)))
                      args)))
        (multiple-value-bind (status body) (upload "picked.png" :headers origin)
          (ok (= status 200))
          (ok (search "picked.png" body) "the new file is in the returned grid"))
        (let ((*cookie* nil))
          (ok (= (upload "anon.png" :headers origin) 401) "uploading needs the owner session"))
        (ok (= (upload "cross.png" :headers '(("origin" . "https://evil.test"))) 403)
            "a cross-origin upload is rejected")
        (ok (null (list-media "website" :search "anon")))
        (ok (null (list-media "website" :search "cross")))))
    (testing "every action is behind the owner session"
      (let ((*cookie* nil))
        (ok (= (call-action :get "/actions/not-an-action-000000") 401)
            "the gate is at the mount, not in each action")))
    (testing "the preview, alt and delete"
      (let ((id (media-id (first (list-media "website" :search "cover")))))
        (multiple-value-bind (status body) (call-action :get (preview-media :space "website" :id id))
          (ok (= status 200))
          (ok (search "<dialog id=\"media-preview\" closedby=\"any\" data-show-modal" body)
              "the dialog is drawn for the file, and opens itself")
          (ok (search "4×4" body))
          (ok (search "value=\"\"" body) "with its alt text"))
        (multiple-value-bind (status body) (call-action :post (save-alt :space "website" :id id) :form '(("alt" . "New alt")))
          (ok (= status 200))
          (ok (search "Saved." body)))
        (ok (search "value=\"New alt\"" (nth-value 1 (call-action :get (preview-media :space "website" :id id)))))
        (multiple-value-bind (status body) (call-action :post (delete-media-action :space "website" :q "" :page 1)
                                                        :form `(("id" . ,id)))
          (ok (= status 200))
          (ok (search "Media deleted." body))
          (ok (search "<dialog id=\"media-preview\" closedby=\"any\" hx-swap-oob=\"true\"" body)
              "an empty dialog takes the open one's place"))
        (ok (null (list-media "website" :search "cover")))
        (ok (= 404 (call-action :get (preview-media :space "website" :id id))) "a file that is gone has no preview")))))

(deftest bulk-delete-in-the-media-library
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (setf *cookie* nil)
    (post-login :form `(("secret" . ,*secret*)))
    (flet ((upload (name)
             (call-action :post (upload-media :space "website" :q "" :page 1)
                          :multipart (list (list "file" name "image/png" (png-bytes))))
             ;; found by name: two uploads in the same millisecond carry ULIDs
             ;; that do not say which came first, so "the newest" is not one of them
             (media-id (find name (list-media "website") :key #'media-filename :test #'string=)))
           (delete-selected (&rest ids)
             (nth-value 1 (call-action :post (delete-selected-media :space "website" :q "bulk" :page 1)
                                       :form (mapcar (lambda (id) (cons "id" id)) ids)))))
      (let ((a (upload "bulk-a.png"))
            (b (upload "bulk-b.png")))
        (testing "every card carries a box, tied to the selection form"
          (multiple-value-bind (status body) (request :get "/s/website/media")
            (ok (= status 200))
            (ok (search "Select all on this page" body))
            (ok (search "id=\"media-bulk\"" body))
            (ok (search (format nil "name=\"id\" value=\"~a\" form=\"media-bulk\"" a) body)
                "the box posts to the form outside the card, because forms do not nest")))
        (testing "deleting a selection deletes each file, and answers the search it was made from"
          (multiple-value-bind (status body headers)
              (call-action :post (delete-selected-media :space "website" :q "bulk" :page 1)
                           :form `(("id" . ,a) ("id" . ,b)))
            (declare (ignore status))
            (ok (search "Deleted 2 files." body))
            (ok (string= (getf headers :hx-replace-url) "/s/website/media?q=bulk") "the URL keeps the search"))
          (ok (null (list-media "website" :search "bulk")) "both gone"))
        (testing "a file a content still uses stays, and the rest still go"
          (let* ((kept (upload "bulk-kept.png"))
                 (other (upload "bulk-other.png")))
            (edit "/s/website/m/blog/new"
                      :form `(("action" . "save") ("f-title" . "Uses an image") ("f-cover" . ,kept))
                     :headers origin)
            (let ((body (delete-selected kept other)))
              (ok (search "Deleted 1 of 2; 1 could not be" body))
              (ok (search "is used by 1 content" body) "and says which and why"))
            (ok (find kept (list-media "website") :key #'media-id :test #'string=) "the one in use is still there")
            (ng (find other (list-media "website") :key #'media-id :test #'string=))
            ;; clear up
            (let ((content (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
              (edit (format nil "/s/website/m/blog/~a" (content-id content))
                        :form '(("action" . "delete")) :headers origin))
            (call-action :post (delete-media-action :space "website") :form `(("id" . ,kept)))))
        (testing "nothing selected is not an action"
          (ok (search "Nothing was selected." (delete-selected))))))))
