(defpackage #:koya-tests/server/pages/settings
  (:use #:cl #:rove)
  (:import-from #:koya-tests/server/pages/support #:*secret* #:*cookie* #:blog-model #:request #:location #:setup-pages #:log-in)
  (:import-from #:koya-server/db/connection #:disconnect-db)
  (:import-from #:koya-server/db/contents #:list-contents #:content-draft #:content-id)
  (:import-from #:koya-server/lib/totp #:totp #:*totp-last-counter* #:totp-enabled-p)
  (:import-from #:koya-server/lib/timezone #:display-timezone-name #:find-timezone)
  (:import-from #:cl-ppcre #:scan-to-strings)
  (:import-from #:koya-server/lib/query #:parse-query)
  (:import-from #:koya/core/json #:jget))
(in-package #:koya-tests/server/pages/settings)

(setup (setup-pages) (log-in))

(teardown (disconnect-db))

(deftest two-factor-settings
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (setf *cookie* nil)
    (request :post "/login" :form `(("secret" . ,*secret*)))
    (ok (not (totp-enabled-p)) "starts disabled")
    (multiple-value-bind (status body) (request :get "/settings")
      (ok (= status 200))
      (ok (search "Disabled" body))
      (ok (search "Set up two-factor login" body)))
    (multiple-value-bind (status body headers) (request :post "/settings" :form '(("action" . "begin")) :headers origin)
      (declare (ignore body))
      (ok (= status 303))
      (ok (string= (location headers) "/settings")))
    (let ((secret nil))
      (multiple-value-bind (status body) (request :get "/settings")
        (ok (= status 200))
        (ok (search "data-qr=\"otpauth://totp/koya:owner?secret=" body) "QR code carries the otpauth URI")
        (multiple-value-bind (match groups) (scan-to-strings "secret=([A-Z2-7]+)&amp;" body)
          (ok match)
          (setf secret (and match (aref groups 0)))))
      (ok (not (totp-enabled-p)) "not enabled until a code confirms the app has the secret")
      (multiple-value-bind (status body) (request :post "/settings" :form '(("action" . "enable") ("code" . "000000")) :headers origin)
        (ok (= status 422))
        (ok (search "did not match" body)))
      (setf *totp-last-counter* -1)
      (multiple-value-bind (status body headers)
          (request :post "/settings" :form `(("action" . "enable") ("code" . ,(totp secret))) :headers origin)
        (declare (ignore body))
        (ok (= status 303))
        (ok (string= (location headers) "/settings")))
      (ok (totp-enabled-p))
      (multiple-value-bind (status body) (request :get "/settings")
        (ok (= status 200))
        (ok (search "Two-factor login is on" body) "flash")
        (ok (search "Disable two-factor login" body)))
      (testing "logging in now needs the code"
        (let ((*cookie* nil))
          (multiple-value-bind (status) (request :post "/login" :form `(("secret" . ,*secret*)))
            (ok (= status 401)))
          (setf *totp-last-counter* -1) ; pretend a new 30 s step has begun
          (multiple-value-bind (status) (request :post "/login" :form `(("secret" . ,*secret*) ("code" . ,(totp secret))))
            (ok (= status 303)))))
      (testing "disabling needs a code too"
        (multiple-value-bind (status body) (request :post "/settings" :form '(("action" . "disable") ("code" . "000000")) :headers origin)
          (ok (= status 422))
          (ok (search "still on" body)))
        (ok (totp-enabled-p))
        (setf *totp-last-counter* -1)
        (multiple-value-bind (status) (request :post "/settings" :form `(("action" . "disable") ("code" . ,(totp secret))) :headers origin)
          (ok (= status 303)))
        (ok (not (totp-enabled-p)))
        (let ((*cookie* nil))
          (multiple-value-bind (status) (request :post "/login" :form `(("secret" . ,*secret*)))
            (ok (= status 303) "secret alone logs in again")))))))

(deftest time-zone-setting
  (let ((origin '(("origin" . "http://localhost:3000"))))
    (setf *cookie* nil)
    (request :post "/login" :form `(("secret" . ,*secret*)))
    (multiple-value-bind (status body) (request :get "/settings")
      (ok (= status 200))
      (ok (search "Time zone" body))
      (ok (search "value=\"UTC\"" body) "UTC until the owner picks a zone")
      (ok (search "<option value=\"UTC\">" body) "the datalist offers the zones"))
    (multiple-value-bind (status body) (request :post "/settings" :form '(("action" . "timezone") ("timezone" . "Mars/Olympus_Mons")) :headers origin)
      (ok (= status 422))
      (ok (search "not a time zone" body))
      (ok (string= (display-timezone-name) "UTC") "nothing stored"))
    (if (null (find-timezone "Asia/Tokyo"))
        (skip "no zone database on this machine")
        (progn
          (multiple-value-bind (status body headers) (request :post "/settings" :form '(("action" . "timezone") ("timezone" . "Asia/Tokyo")) :headers origin)
            (declare (ignore body))
            (ok (= status 303))
            (ok (string= (location headers) "/settings")))
          (ok (string= (display-timezone-name) "Asia/Tokyo"))
          (multiple-value-bind (status body) (request :get "/settings")
            (ok (= status 200))
            (ok (search "Times are now shown in Asia&#x2F;Tokyo" body) "flash (text is escaped, attributes are not)")
            (ok (search "value=\"Asia/Tokyo\"" body)))
          (testing "the editor takes and shows datetimes in that zone"
            (let ((id nil))
              (multiple-value-bind (status body headers)
                  (request :post "/s/website/m/blog/new"
                           :form '(("action" . "save") ("f-title" . "Tokyo time") ("f-when" . "2026-09-21T08:30")) :headers origin)
                (declare (ignore body))
                (ok (= status 303))
                (let* ((loc (location headers)) (path (subseq loc 0 (position #\? loc))))
                  (setf id (subseq path (1+ (position #\/ path :from-end t))))))
              (let ((content (find-if (lambda (c) (string= (content-id c) id))
                                      (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
                (ok (string= (jget (content-draft content) "when") "2026-09-20T23:30:00.000Z") "stored as UTC"))
              (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
                (ok (= status 200))
                (ok (search "value=\"2026-09-21T08:30\"" body) "shown back in the zone")
                (ok (search ">Asia&#x2F;Tokyo<" body) "the hint names the zone")
                (ok (search " JST</span>" body) "created at is in the zone"))
              (multiple-value-bind (status body) (request :get "/s/website/m/blog")
                (ok (= status 200))
                (ok (search "2026-09-21 08:30 JST" body) "list preview in the zone"))
              (request :post (format nil "/s/website/m/blog/~a" id) :form '(("action" . "delete")) :headers origin)))
          (multiple-value-bind (status) (request :post "/settings" :form '(("action" . "timezone") ("timezone" . "UTC")) :headers origin)
            (ok (= status 303)))
          (ok (string= (display-timezone-name) "UTC") "back to UTC for the other tests")))))

