(defpackage #:koya-tests/server/web/admin-api/contents
  (:use #:cl #:rove)
  (:import-from #:koya-tests/server/web/api-support #:*webhooks* #:admin #:delivery #:webhook-events #:setup-api #:reset-api #:test-schema)
  (:import-from #:koya-server/usecases/ports/spaces #:save-schema)
  (:import-from #:koya/core/schema #:make-field #:make-model #:make-schema)
  (:import-from #:koya-server/infra/db/connection #:disconnect-db)
  (:import-from #:koya/core/json #:jobject #:jget #:json-null))
(in-package #:koya-tests/server/web/admin-api/contents)

(setup (setup-api))

(teardown (disconnect-db))

(defhook :before (reset-api))

(deftest content-flow
  (let ((tag-id nil) (post-id nil))
    (testing "create a published tag"
      (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/tag" :body (jobject "data" (jobject "name" "lisp") "publish" t))
        (ok (= status 201))
        (ok (string= (jget json "status") "published"))
        (setf tag-id (jget json "id"))))
    (testing "validation errors are 422 with details"
      (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/blog" :body (jobject "data" (jobject "body" "x")))
        (ok (= status 422))
        (ok (string= (jget json "error" "code") "validation_failed"))
        (ok (string= (jget (aref (jget json "error" "details") 0) "field") "title"))))
    (testing "create a draft post, then publish it"
      (multiple-value-bind (status json)
          (admin :post "/admin/api/contents/website/blog"
                 :body (jobject "data" (jobject "title" "Hello" "body" "# Hi" "tags" (vector tag-id))))
        (ok (= status 201))
        (ok (string= (jget json "status") "draft"))
        (ok (eq (jget json "published") json-null))
        (setf post-id (jget json "id")))
      (multiple-value-bind (status json) (delivery "/api/v1/website/blog")
        (ok (= status 200))
        (ok (= (jget json "totalCount") 0) "drafts are not delivered"))
      (multiple-value-bind (status json) (admin :post (format nil "/admin/api/contents/website/blog/~a/publish" post-id))
        (ok (= status 200))
        (ok (string= (jget json "status") "published"))
        (ok (string= (jget json "published" "body") "# Hi")))
      (ok (equal (webhook-events) '("publish" "draft" "publish")) "tag publish, the post's draft save, the post's publish: every event reaches the hook")
      (ok (string= (jget (second (first *webhooks*)) "model") "blog"))
      (ok (string= (jget (second (first *webhooks*)) "contents" "new" "title") "Hello"))
      (ok (string= (first (first *webhooks*)) "https://example.com/hook"))
      (ok (= (length (cdr (assoc "X-KOYA-WEBHOOK-KEY" (third (first *webhooks*)) :test #'string=))) 48)
          "webhook carries the space secret"))
    (testing "uniqueness"
      (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/blog" :body (jobject "data" (jobject "title" "Hello")))
        (ok (= status 422))
        (ok (string= (jget (aref (jget json "error" "details") 0) "code") "unique"))))
    (testing "delivery list and item, with reference expansion and fields"
      (multiple-value-bind (status json) (delivery "/api/v1/website/blog")
        (ok (= status 200))
        (ok (= (jget json "totalCount") 1))
        (ok (= (jget json "limit") 10))
        (let ((item (aref (jget json "contents") 0)))
          (ok (string= (jget item "id") post-id))
          (ok (string= (jget item "title") "Hello"))
          (ok (string= (aref (jget item "tags") 0) tag-id) "references are ids by default")
          (ok (stringp (jget item "publishedAt")))))
      (multiple-value-bind (status json) (delivery "/api/v1/website/blog" :query "include=tags")
        (ok (= status 200))
        (ok (string= (jget (aref (jget (aref (jget json "contents") 0) "tags") 0) "name") "lisp") "include embeds references"))
      (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/blog/~a" post-id) :query "fields=id,title")
        (ok (= status 200))
        (ok (equal (sort (koya/core/json:jkeys json) #'string<) '("id" "title"))))
      (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/blog/~a" post-id) :query "include=tags")
        (ok (= status 200))
        (ok (string= (jget (aref (jget json "tags") 0) "id") tag-id) "embedded object carries its id"))
      (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/blog/~a" post-id) :query "include=title")
        (ok (= status 400))
        (ok (string= (jget json "error" "code") "bad_query") "include of a non-reference field is rejected"))
      (multiple-value-bind (status) (delivery "/api/v1/website/blog" :query "filters=title[equals]Hello")
        (ok (= status 200)))
      (multiple-value-bind (status json) (delivery "/api/v1/website/blog" :query "filters=nope[equals]1")
        (ok (= status 400))
        (ok (string= (jget json "error" "code") "bad_query"))))
    (testing "draft edits and preview with draftKey"
      (multiple-value-bind (status json) (admin :patch (format nil "/admin/api/contents/website/blog/~a" post-id) :body (jobject "data" (jobject "title" "Hello v2")))
        (ok (= status 200))
        (ok (string= (jget json "status") "published+draft"))
        (ok (string= (jget json "draft" "title") "Hello v2"))
        (ok (string= (jget json "draft" "body") "# Hi") "patch merges onto existing data"))
      (multiple-value-bind (status json) (admin :post (format nil "/admin/api/contents/website/blog/~a/draft-key" post-id))
        (ok (= status 200))
        (let ((key (jget json "draftKey")))
          (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/blog/~a" post-id))
            (ok (= status 200))
            (ok (string= (jget json "title") "Hello") "without key: published"))
          (multiple-value-bind (status json) (delivery (format nil "/api/v1/website/blog/~a" post-id) :query (format nil "draftKey=~a" key))
            (ok (= status 200))
            (ok (string= (jget json "title") "Hello v2") "with key: draft"))
          (multiple-value-bind (status) (delivery (format nil "/api/v1/website/blog/~a" post-id) :query "draftKey=wrong")
            (ok (= status 200) "wrong key falls back to published")))))
    (testing "discard a draft on a published content"
      (multiple-value-bind (status json) (admin :patch (format nil "/admin/api/contents/website/blog/~a" post-id) :body (jobject "data" (jobject "title" "Draft edit")))
        (ok (= status 200))
        (ok (string= (jget json "status") "published+draft")))
      (multiple-value-bind (status json) (admin :post (format nil "/admin/api/contents/website/blog/~a/discard-draft" post-id))
        (ok (= status 200))
        (ok (string= (jget json "status") "published"))
        (ok (eq (jget json "draft") koya/core/json:json-null))
        (ok (string= (jget json "published" "title") "Hello") "published data untouched"))
      (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/blog" :body (jobject "data" (jobject "title" "Never published")))
        (ok (= status 201))
        (multiple-value-bind (status json) (admin :post (format nil "/admin/api/contents/website/blog/~a/discard-draft" (jget json "id")))
          (ok (= status 409) "a draft-only content has nothing to fall back to")
          (ok (string= (jget json "error" "code") "not_published")))
        (admin :delete (format nil "/admin/api/contents/website/blog/~a" (jget json "id")))))
    (testing "unpublish and delete"
      (multiple-value-bind (status json) (admin :post (format nil "/admin/api/contents/website/blog/~a/unpublish" post-id))
        (ok (= status 200))
        (ok (string= (jget json "status") "draft")))
      (multiple-value-bind (status) (delivery (format nil "/api/v1/website/blog/~a" post-id))
        (ok (= status 404)))
      (multiple-value-bind (status json) (admin :delete (format nil "/admin/api/contents/website/blog/~a" post-id))
        (ok (= status 200))
        (ok (eq (jget json "deleted") t)))
      (multiple-value-bind (status) (admin :get (format nil "/admin/api/contents/website/blog/~a" post-id))
        (ok (= status 404)))
      (ok (equal (webhook-events) '("publish" "draft" "publish" "draft" "draft" "draft" "unpublish"))
          "every draft save and the unpublish fire; deleting an unpublished draft fires nothing"))))

(deftest import-style-create
  (testing "explicit id and publishedAt"
    (multiple-value-bind (status json)
        (admin :post "/admin/api/contents/website/tag"
               :body (jobject "data" (jobject "name" "old") "publish" t "id" "hg2papkhis4" "publishedAt" "2025-04-30T15:00:00.000Z"))
      (ok (= status 201))
      (ok (string= (jget json "id") "hg2papkhis4"))
      (ok (string= (jget json "publishedAt") "2025-04-30T15:00:00.000Z")))
    (multiple-value-bind (status json) (delivery "/api/v1/website/tag/hg2papkhis4")
      (ok (= status 200))
      (ok (string= (jget json "publishedAt") "2025-04-30T15:00:00.000Z")))
    (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/tag" :body (jobject "data" (jobject "name" "dup") "id" "hg2papkhis4"))
      (ok (= status 409))
      (ok (string= (jget json "error" "code") "conflict")))
    (multiple-value-bind (status) (admin :post "/admin/api/contents/website/tag" :body (jobject "data" (jobject "name" "x") "id" "bad id!"))
      (ok (= status 400)))
    (multiple-value-bind (status) (admin :post "/admin/api/contents/website/tag" :body (jobject "data" (jobject "name" "x") "publish" t "publishedAt" "yesterday"))
      (ok (= status 400))))
  (testing "publish with publishedAt override"
    (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/tag" :body (jobject "data" (jobject "name" "later")))
      (ok (= status 201))
      (multiple-value-bind (status json) (admin :post (format nil "/admin/api/contents/website/tag/~a/publish" (jget json "id"))
                                                :body (jobject "publishedAt" "2024-01-01T00:00:00.000Z"))
        (ok (= status 200))
        (ok (string= (jget json "publishedAt") "2024-01-01T00:00:00.000Z"))))))

(deftest object-model
  (multiple-value-bind (status) (delivery "/api/v1/website/about")
    (ok (= status 404) "nothing yet"))
  (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/about" :body (jobject "data" (jobject "body" "about me") "publish" t))
    (ok (= status 201))
    (ok (string= (jget json "status") "published")))
  (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/about" :body (jobject "data" (jobject "body" "about me v2") "publish" t))
    (ok (= status 201))
    (ok (string= (jget json "published" "body") "about me v2") "object models upsert"))
  (multiple-value-bind (status json) (delivery "/api/v1/website/about")
    (ok (= status 200))
    (ok (string= (jget json "body") "about me v2")))
  (multiple-value-bind (status json) (admin :get "/admin/api/contents/website/about")
    (ok (= status 200))
    (ok (= (jget json "totalCount") 1))))


(deftest a-referenced-content-stays
  (flet ((make (model data)
           (jget (nth-value 1 (admin :post (format nil "/admin/api/contents/website/~a" model)
                                     :body (jobject "data" data "publish" t)))
                 "id")))
    (let* ((tag (make "tag" (jobject "name" "lisp")))
           (post (make "blog" (jobject "title" "Uses it" "tags" (vector tag)))))
      (testing "deleting or unpublishing it is refused while a content refers to it"
        (multiple-value-bind (status json) (admin :delete (format nil "/admin/api/contents/website/tag/~a" tag))
          (ok (= status 409))
          (ok (string= (jget json "error" "code") "in_use"))
          (ok (search "referenced by 1 other content" (jget json "error" "message"))))
        (multiple-value-bind (status json) (admin :post (format nil "/admin/api/contents/website/tag/~a/unpublish" tag))
          (ok (= status 409))
          (ok (string= (jget json "error" "code") "in_use")))
        (ok (string= (jget (nth-value 1 (delivery (format nil "/api/v1/website/tag/~a" tag))) "name") "lisp")
            "and it is still delivered"))
      (testing "a draft that still refers to it counts too"
        (admin :patch (format nil "/admin/api/contents/website/blog/~a" post) :body (jobject "data" (jobject "tags" #())))
        (ok (= 409 (admin :delete (format nil "/admin/api/contents/website/tag/~a" tag))) "the published data still does")
        (admin :post (format nil "/admin/api/contents/website/blog/~a/publish" post)))
      (testing "a draft is unpublished whatever refers to it: nothing is taken away"
        (let ((draft (jget (nth-value 1 (admin :post "/admin/api/contents/website/tag" :body (jobject "data" (jobject "name" "draft"))))
                           "id")))
          (admin :patch (format nil "/admin/api/contents/website/blog/~a" post) :body (jobject "data" (jobject "tags" (vector tag draft))))
          (ok (= 200 (admin :post (format nil "/admin/api/contents/website/tag/~a/unpublish" draft))))
          (ok (= 409 (admin :delete (format nil "/admin/api/contents/website/tag/~a" draft))) "but not deleted")
          (admin :patch (format nil "/admin/api/contents/website/blog/~a" post) :body (jobject "data" (jobject "tags" #())))))
      (testing "once the reference is taken out, it goes"
        (ok (= 200 (admin :post (format nil "/admin/api/contents/website/tag/~a/unpublish" tag))))
        (ok (= 200 (admin :delete (format nil "/admin/api/contents/website/tag/~a" tag)))))))
  (testing "a reference field removed by a deploy no longer holds anything"
    (let* ((tag (jget (nth-value 1 (admin :post "/admin/api/contents/website/tag"
                                          :body (jobject "data" (jobject "name" "cl") "publish" t)))
                      "id")))
      (admin :post "/admin/api/contents/website/blog" :body (jobject "data" (jobject "title" "Keeps an id" "tags" (vector tag))))
      (ok (= 409 (admin :delete (format nil "/admin/api/contents/website/tag/~a" tag))))
      (save-schema "website" (make-schema :models (list (make-model "blog" :list (list (make-field :title :text :required t)))
                                                        (make-model "tag" :list (list (make-field :name :text :required t)))
                                                        (make-model "about" :object (list (make-field :body :richtext))))))
      (unwind-protect
           (ok (= 200 (admin :delete (format nil "/admin/api/contents/website/tag/~a" tag))))
        (save-schema "website" (test-schema))))))

(deftest a-patch-that-changes-nothing-writes-nothing
  (let ((id (jget (nth-value 1 (admin :post "/admin/api/contents/website/tag"
                                      :body (jobject "data" (jobject "name" "same") "publish" t)))
                  "id")))
    (setf *webhooks* '())
    (multiple-value-bind (status json) (admin :patch (format nil "/admin/api/contents/website/tag/~a" id)
                                              :body (jobject "data" (jobject "name" "same")))
      (ok (= status 200))
      (ok (string= (jget json "status") "published") "no draft is made"))
    (ok (null *webhooks*) "and nothing is sent")))
