(defpackage #:koya-server/web/api/v1/<space>/<model>/index
  (:use #:cl)
  (:import-from #:koya/core/schema #:model-kind)
  (:import-from #:koya/core/json #:jobject)
  (:import-from #:koya-server/domain/query #:parse-query #:query-limit #:query-offset #:query-fields)
  (:import-from #:koya-server/web/http #:path-param #:param)
  (:import-from #:koya-server/web/auth #:require-delivery-key)
  (:import-from #:koya-server/usecases/contents/lookup #:resolve-model)
  (:import-from #:koya-server/usecases/contents/delivery #:delivered-list #:delivered-object)
  (:import-from #:koya-server/web/presenters #:delivered->jobject)
  (:export #:@get))
(in-package #:koya-server/web/api/v1/<space>/<model>/index)

(defun @get (params)
  (require-delivery-key (path-param params :space))
  (multiple-value-bind (space model) (resolve-model (path-param params :space) (path-param params :model))
    (let ((query (parse-query params)))
      (if (eq (model-kind model) :object)
          (delivered->jobject (delivered-object space model query :draft-key (param params "draftKey"))
                              :fields (query-fields query))
          (multiple-value-bind (contents total) (delivered-list space model query)
            (jobject "contents" (map 'vector (lambda (c) (delivered->jobject c :fields (query-fields query)))
                                     contents)
                     "totalCount" total
                     "offset" (query-offset query)
                     "limit" (query-limit query)))))))
