(defpackage #:koya-tests/server/usecases/webhooks/notify
  (:use #:cl #:rove)
  (:import-from #:koya-tests/server/web/api-support #:*webhooks* #:test-schema #:admin #:webhook-events #:setup-api #:reset-api)
  (:import-from #:koya-server/infra/db/connection #:disconnect-db #:exec)
  (:import-from #:koya-server/usecases/ports/spaces #:save-schema)
  (:import-from #:koya-server/infra/db/webhook-deliveries #:+max-response-chars+)
  (:import-from #:koya-server/usecases/ports/webhooks #:+deliveries-kept+)
  (:import-from #:koya-server/usecases/ports/webhooks #:list-deliveries #:count-deliveries)
  (:import-from #:koya-tests/server/fake-webhooks #:*webhook-sender*)
  (:import-from #:koya-server/domain/webhook-delivery
                #:delivery-ok #:delivery-status #:delivery-response #:delivery-error
                #:delivery-event #:delivery-model #:delivery-label #:delivery-url
                #:delivery-content-id #:delivery-duration-ms)
  (:import-from #:koya/core/schema #:make-field #:make-model #:make-schema #:make-webhook)
  (:import-from #:koya/core/json #:jobject #:jget #:json-null))
(in-package #:koya-tests/server/usecases/webhooks/notify)

(setup (setup-api))

(teardown (disconnect-db))

(defhook :before (reset-api))

(deftest every-webhook-gets-every-event
  (let ((with-hooks
          (make-schema :webhooks (list (make-webhook "hook" "https://example.com/hook")
                                       (make-webhook "preview" "https://example.com/preview" :only '(blog)))
                       :models (list (make-model "blog" :list (list (make-field :title :text :required t :unique t)
                                                                    (make-field :body :richtext)
                                                                    (make-field :tags :reference :model "tag" :many t)
                                                                    (make-field :cover :media)))
                                     (make-model "tag" :list (list (make-field :name :text :required t)))
                                     (make-model "about" :object (list (make-field :body :richtext)))))))
    (save-schema "website" with-hooks)
    (unwind-protect
         (flet ((sent () (mapcar (lambda (w) (list (first w) (jget (second w) "event"))) (reverse *webhooks*))))
           (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/blog" :body (jobject "data" (jobject "title" "Draft")))
             (ok (= status 201))
             (ok (equal (sent) '(("https://example.com/hook" "draft") ("https://example.com/preview" "draft")))
                 "a draft save reaches the space's hook and the one narrowed to blog, as draft")
             (ok (string= (jget (second (first *webhooks*)) "contents" "new" "title") "Draft") "with the draft data")
             (ok (null (jget (second (first *webhooks*)) "type")) "the old type key is gone")
             (let ((id (jget json "id")))
               (setf *webhooks* '())
               (admin :patch (format nil "/admin/api/contents/website/blog/~a" id) :body (jobject "data" (jobject "title" "Draft 2")))
               (ok (equal (sent) '(("https://example.com/hook" "draft") ("https://example.com/preview" "draft"))) "so does a draft update")
               (setf *webhooks* '())
               (admin :post (format nil "/admin/api/contents/website/blog/~a/publish" id))
               (ok (equal (sent) '(("https://example.com/hook" "publish") ("https://example.com/preview" "publish"))))
               (setf *webhooks* '())
               (admin :post (format nil "/admin/api/contents/website/blog/~a/unpublish" id))
               (ok (equal (sent) '(("https://example.com/hook" "unpublish") ("https://example.com/preview" "unpublish"))))
               (setf *webhooks* '())
               (admin :post (format nil "/admin/api/contents/website/blog/~a/publish" id))
               (setf *webhooks* '())
               (admin :post (format nil "/admin/api/contents/website/blog/~a/discard-draft" id))
               (ok (null (sent)) "discarding sends nothing")
               (admin :delete (format nil "/admin/api/contents/website/blog/~a" id))
               (ok (equal (sent) '(("https://example.com/hook" "delete") ("https://example.com/preview" "delete"))))))
           (testing "a model the :only leaves out gets only the space's own hook"
             (setf *webhooks* '())
             (let ((id (jget (nth-value 1 (admin :post "/admin/api/contents/website/tag"
                                                 :body (jobject "data" (jobject "name" "lisp")))) "id")))
               (ok (equal (sent) '(("https://example.com/hook" "draft"))))
               (admin :delete (format nil "/admin/api/contents/website/tag/~a" id)))))
      (save-schema "website" (test-schema)))))

(deftest delete-published-webhook
  (let ((post-id nil))
    (multiple-value-bind (status json) (admin :post "/admin/api/contents/website/blog" :body (jobject "data" (jobject "title" "Bye") "publish" t))
      (ok (= status 201))
      (setf post-id (jget json "id")))
    (multiple-value-bind (status json) (admin :delete (format nil "/admin/api/contents/website/blog/~a" post-id))
      (ok (= status 200))
      (ok (eq (jget json "deleted") t)))
    (ok (equal (webhook-events) '("publish" "delete")))
    (let ((hook (first *webhooks*)))
      (ok (string= (jget (second hook) "id") post-id))
      (ok (string= (jget (second hook) "contents" "old" "title") "Bye"))
      (ok (eq (jget (second hook) "contents" "new") json-null))
      (ok (= (length (cdr (assoc "X-KOYA-WEBHOOK-KEY" (third hook) :test #'string=))) 48)
          "delete webhook carries the space secret"))))

(deftest webhook-delivery-log
  (testing "what the receiver answered is kept"
    (multiple-value-bind (status json)
        (admin :post "/admin/api/contents/website/blog" :body (jobject "data" (jobject "title" "Logged") "publish" t))
      (ok (= status 201))
      (let ((deliveries (list-deliveries "website")))
        (ok (= (length deliveries) 1) "one hook, one call")
        (let ((d (first deliveries)))
          (ok (eq (delivery-ok d) t) "200 counts as accepted")
          (ok (= (delivery-status d) 200))
          (ok (string= (delivery-response d) "{\"revalidated\":true}") "the body is there to read")
          (ok (string= (delivery-error d) ""))
          (ok (string= (delivery-event d) "publish"))
          (ok (string= (delivery-model d) "blog"))
          (ok (string= (delivery-label d) "hook"))
          (ok (string= (delivery-url d) "https://example.com/hook"))
          (ok (string= (delivery-content-id d) (jget json "id")))
          (ok (integerp (delivery-duration-ms d)))))))
  (testing "a refusal is recorded as one, with its body"
    (exec "DELETE FROM webhook_deliveries")
    (let ((*webhook-sender* (lambda (url payload headers)
                              (declare (ignore url payload headers))
                              (values 500 "revalidation failed" nil))))
      (admin :post "/admin/api/contents/website/blog" :body (jobject "data" (jobject "title" "Refused") "publish" t)))
    (let ((d (first (list-deliveries "website"))))
      (ok (null (delivery-ok d)) "5xx is not an acceptance")
      (ok (= (delivery-status d) 500))
      (ok (string= (delivery-response d) "revalidation failed"))))
  (testing "a call that never arrived has no status"
    (exec "DELETE FROM webhook_deliveries")
    (let ((*webhook-sender* (lambda (url payload headers)
                              (declare (ignore url payload headers))
                              (error "connection refused"))))
      (admin :post "/admin/api/contents/website/blog" :body (jobject "data" (jobject "title" "Unreachable") "publish" t)))
    (let ((d (first (list-deliveries "website"))))
      (ok (null (delivery-ok d)))
      (ok (null (delivery-status d)))
      (ok (search "connection refused" (delivery-error d)) "the condition is kept as the error")))
  (testing "an oversized body is clipped, and the log does not grow without end"
    (exec "DELETE FROM webhook_deliveries")
    (let ((*webhook-sender* (lambda (url payload headers)
                              (declare (ignore url payload headers))
                              (values 200 (make-string (* 4 +max-response-chars+) :initial-element #\x) nil))))
      (admin :post "/admin/api/contents/website/blog" :body (jobject "data" (jobject "title" "Chatty") "publish" t)))
    (let ((d (first (list-deliveries "website"))))
      (ok (< (length (delivery-response d)) (* 2 +max-response-chars+)) "stored clipped, not whole")
      (ok (search "characters in all" (delivery-response d)) "and says it was clipped"))
    (dotimes (i 5)
      (admin :post "/admin/api/contents/website/tag" :body (jobject "data" (jobject "name" (format nil "t~a" i)) "publish" t)))
    (ok (<= (count-deliveries "website") +deliveries-kept+) "the cap holds")))

