(defpackage #:koya-tests/server/web/pages/editor
  (:use #:cl #:rove)
  (:import-from #:koya-server/web/pages/s/<space>/m/<model>/<id>/history #:browse-history)
  (:import-from #:koya-tests/server/web/pages/support #:call-action #:edit #:moved-to #:blog-model #:request #:location #:setup-pages #:log-in)
  (:import-from #:koya-server/infra/db/connection #:disconnect-db #:exec)
  (:import-from #:koya-server/usecases/ports/spaces #:save-schema)
  (:import-from #:koya-server/usecases/ports/contents
                #:list-contents #:list-revisions #:count-revisions #:get-content)
  (:import-from #:koya-server/domain/content
                #:content-status #:content-published #:content-draft #:content-id #:slugify)
  (:import-from #:koya-server/domain/media #:media-id)
  (:import-from #:koya-server/domain/query #:parse-query)
  (:import-from #:koya-server/domain/revision #:revision-id #:revision-event #:revision-by)
  (:import-from #:koya/core/schema #:make-field #:make-model #:make-schema)
  (:import-from #:koya/core/json #:jget)
  (:import-from #:koya-server/usecases/ports/media #:insert-media #:delete-media)
  (:import-from #:koya-server/usecases/contents/write #:create)
  (:import-from #:koya-server/usecases/contents/lookup #:resolve-model))
(in-package #:koya-tests/server/web/pages/editor)

(setup (setup-pages) (log-in))

(teardown (disconnect-db))

(deftest editor-flow
  (exec "DELETE FROM contents")
  (testing "validation errors re-render the form"
    (multiple-value-bind (status body) (edit "/s/website/m/blog/new" :form '(("action" . "save") ("f-body" . "x")))
      (ok (= status 422))
      (ok (search "is required" body))
      (ng (search "NIL" body))))
  (testing "an empty Quill document counts as blank"
    (multiple-value-bind (status body headers)
        (edit "/s/website/m/blog/new" :form '(("action" . "save") ("f-title" . "Blank body") ("f-body" . "<p><br></p>")))
      (declare (ignore body))
      (ok (= status 200))
      (let* ((loc (moved-to headers)) (id (subseq loc (1+ (position #\/ loc :from-end t)))))
        (ok (null (jget (content-draft (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))) "body")))
        (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "delete"))))))
  (let ((id nil))
    (testing "save a draft"
      (multiple-value-bind (status body headers)
          (edit "/s/website/m/blog/new"
                    :form '(("action" . "save") ("f-title" . "Hello World") ("f-body" . "# Hi")
                           ("f-featured" . "on") ("f-category" . "tech") ("f-labels" . "a") ("f-labels" . "b")
                           ("f-count" . "2.5") ("f-when" . "2026-09-20T10:00")
                           ("f-related" . "x1") ("f-related" . "x2")))
        (declare (ignore body))
        (ok (= status 200))
        (let* ((loc (moved-to headers))
               (path (subseq loc 0 (position #\? loc))))
          (setf id (subseq path (1+ (position #\/ path :from-end t))))
          (ok (= (length id) 26))))
      (let ((content (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
        (ok (string= (content-status content) "draft"))
        (let ((draft (content-draft content)))
          (ok (string= (jget draft "slug") "hello-world") "slug generated from title")
          (ok (eq (jget draft "featured") t))
          (ok (equalp (jget draft "labels") #("a" "b")))
          (ok (= (jget draft "count") 2.5))
          (ok (string= (jget draft "when") "2026-09-20T10:00:00.000Z") "datetime-local value stored as UTC in the canonical form")
          (ok (equalp (jget draft "related") #("x1" "x2")) "a multiple select repeats the name"))))
    (testing "editor shows the draft and the toast exactly once"
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ok (search "value=\"Hello World\"" body))
        (ok (search "value=\"hello-world\"" body))
        (ok (search "checked" body))
        (ok (search "value=\"2026-09-20T10:00\"" body))
        (ok (search "value=\"2.5\"" body) "floats render without an exponent marker")
        (ok (search "<select id=\"f-related\" name=\"f-related\" multiple" body)
            "reference is a multiple select")
        (ok (search "value=\"x1\" selected" body) "selected ids not in the target model are kept")
        (ok (search (format nil "value=\"~a\"" id) body) "existing contents are offered")
        (ok (search "Draft saved" body))
        (ng (search "NIL" body) "no stray NILs in the page"))
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ng (search "Draft saved" body) "toast is gone on the next request")))
    (testing "text with a literal entity survives the editor"
      (multiple-value-bind (status body headers)
          (edit "/s/website/m/blog/new"
                    :form '(("action" . "save") ("f-title" . "AT&amp;T <b>") ("f-body" . "<p>x</p>")))
        (declare (ignore body))
        (ok (= status 200))
        (let ((path (subseq (moved-to headers) 0 (position #\? (moved-to headers)))))
          (multiple-value-bind (status body) (request :get path)
            (ok (= status 200))
            (ok (search "value=\"AT&amp;amp;T <b>\"" body) "the attribute encodes & so the browser shows AT&amp;T"))
          (edit path :form '(("action" . "delete"))))))
    (testing "list shows field previews and status, newest first"
      (edit "/s/website/m/blog/new"
                :form `(("action" . "save") ("f-title" . "Second post") ("f-body" . "<p>Rich <b>text</b> &amp; more</p>")
                       ("f-related" . ,id) ("f-related" . "x2")))
      (multiple-value-bind (status body) (request :get "/s/website/m/blog")
        (ok (= status 200))
        (ok (search "Hello World" body))
        (ok (< (search "Second post" body) (search "Hello World" body)) "newest created first")
        (ok (search "Rich text &amp; more" body) "rich text is previewed as plain text")
        (ok (not (search "<b>text</b>" body)))
        (ok (search "2026-09-20 10:00 UTC" body) "datetime preview")
        (ok (search ">Yes<" body) "boolean preview")
        (ok (search ">a, b<" body) "multi select preview")
        (ok (search ">2.5<" body) "number preview")
        (ok (search ">draft<" body))
        (ok (search "class=\"after:absolute after:inset-0\" aria-label=\"Open " body) "a row's link covers the row")
        (ok (search "Hello World, x2" body) "a reference previews as the target's label, unknown ids stay ids")
        (ok (not (search ">Hello World</a>" body)) "the title is not a link of its own")
        (ok (not (search "Created at" body)))
        (ok (not (search "Updated at" body))))
      (let ((second (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
        (edit (format nil "/s/website/m/blog/~a" (content-id second)) :form '(("action" . "delete")))))
    (testing "discard a draft"
      (let ((origin '(("origin" . "http://localhost:3000"))))
        (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "publish") ("f-title" . "Hello World") ("f-body" . "<p>x</p>")) :headers origin)
        (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
          (ok (= status 200))
          (ok (not (search "Discard draft" body)) "no draft, no button"))
        (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "save") ("f-title" . "Edited") ("f-body" . "<p>x</p>")) :headers origin)
        (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
          (ok (= status 200))
          (ok (search "Discard draft" body))
          (ok (search "value=\"Edited\"" body)))
        (multiple-value-bind (status body headers) (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "discard")) :headers origin)
          (ok (= status 200))
          (ok (string= (moved-to headers) (format nil "/s/website/m/blog/~a" id)))
          (ok (search "id=\"editor\"" body) "the editor is drawn again")
          (ok (search "Draft discarded." body) "with the toast out of band")
          (ok (search "value=\"Hello World\"" body) "and the published data back in it"))
        (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
          (ok (= status 200))
          (ok (search "value=\"Hello World\"" body) "editor shows the published data again")
          (ok (not (search "Discard draft" body))))
        (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "unpublish")) :headers origin)))
    (testing "publish, unpublish, delete"
      (multiple-value-bind (status body headers)
          (edit (format nil "/s/website/m/blog/~a" id)
                    :form '(("action" . "publish") ("f-title" . "Hello World") ("f-slug" . "hello-world") ("f-body" . "# Hi")))
        (ok (= status 200))
        (ok (search "Published." body) "toast after publish")
        (ok (string= (moved-to headers) (format nil "/s/website/m/blog/~a" id)) "the URL loses any query noise"))
      (let ((content (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))))
        (ok (string= (content-status content) "published"))
        (ok (null (jget (content-published content) "featured")) "unchecked box stored as false"))
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ok (search "Published page" body) "published + public template gives a page link")
        (ng (search "Preview draft" body) "no draft, no preview link"))
      (multiple-value-bind (status) (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "unpublish")))
        (ok (= status 200)))
      (ok (string= (content-status (first (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all))) "draft"))
      (multiple-value-bind (status body) (request :get (format nil "/s/website/m/blog/~a" id))
        (ok (= status 200))
        (ok (search "Preview draft" body) "draft + preview template gives a preview link")
        (ok (search "https://site.test/blog/" body))
        (ng (search "Published page" body)))
      (multiple-value-bind (status body headers) (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "delete")))
        (declare (ignore body))
        (ok (= status 200))
        (ok (string= (moved-to headers) "/s/website/m/blog")))
      (ok (null (list-contents "website" "blog" (blog-model) (parse-query nil) :status :all)))))
  (testing "object model editor upserts"
    (multiple-value-bind (status body headers) (edit "/s/website/m/about/new" :form '(("action" . "publish") ("f-body" . "about")))
      (declare (ignore body))
      (ok (= status 200))
      (ok (search "/s/website/m/about/" (moved-to headers))))
    (multiple-value-bind (status body headers) (request :get "/s/website/m/about")
      (declare (ignore body))
      (ok (= status 302))
      (ng (search "/new" (location headers)) "now redirects to the existing content"))))

(deftest richtext-is-stored-as-sent
  (exec "DELETE FROM contents")
  ;; HTML the API stored, not in the shape the editor writes
  (let* ((html (format nil "<h2 id=\"intro\">Intro</h2><p>a</p>~%<p>b</p>"))
         (id (multiple-value-bind (space model) (resolve-model "website" "blog")
               (content-id (create space model (let ((data (make-hash-table :test 'equal)))
                                                 (setf (gethash "title" data) "Imported"
                                                       (gethash "body" data) html)
                                                 data)
                                   :publish t))))
         (path (format nil "/s/website/m/blog/~a" id)))
    (testing "the editor carries the HTML whole, its line breaks included"
      (let ((body (nth-value 1 (request :get path))))
        (ok (search (format nil "id=\"f-body\" name=\"f-body\" value=\"<h2 id=&quot;intro&quot;>Intro</h2><p>a</p>~%<p>b</p>\"")
                    body)
            "an untouched field is sent back as it is here: hsx keeps an attribute value's line breaks")))
    (testing "an untouched field comes back as it was, less the CRLF of the form"
      (edit path :form `(("action" . "save") ("f-title" . "Renamed")
                                  ("f-body" . ,(format nil "<h2 id=\"intro\">Intro</h2><p>a</p>~c~%<p>b</p>" #\Return))))
      (ok (string= (jget (content-draft (get-content id)) "body") html)))
    (testing "the whitespace around it is kept too"
      (let ((spaced (format nil "~%<p>a</p>~%")))
        (edit path :form `(("action" . "save") ("f-title" . "Renamed") ("f-body" . ,spaced)))
        (ok (string= (jget (content-draft (get-content id)) "body") spaced))))
    (testing "an edited one is stored as the editor wrote it"
      (edit path :form '(("action" . "save") ("f-title" . "Renamed") ("f-body" . "<p>c</p><p>d</p>")))
      (ok (string= (jget (content-draft (get-content id)) "body") "<p>c</p><p>d</p>")))))

(deftest slugify-test
  (ok (string= (slugify "Hello, World!") "hello-world"))
  (ok (string= (slugify "  Common  Lisp 2026 ") "common-lisp-2026"))
  (ok (string= (slugify "日本語") "") "non-ascii yields empty; validation then reports it"))

(defun new-blog (form)
  "Post FORM to the new-content editor; the new content's id."
  (multiple-value-bind (status body headers) (edit "/s/website/m/blog/new" :form form)
    (declare (ignore body))
    (ok (= status 200))
    (let ((path (subseq (moved-to headers) 0 (position #\? (moved-to headers)))))
      (subseq path (1+ (position #\/ path :from-end t))))))

(deftest history-and-restore
  (exec "DELETE FROM contents")
  (let* ((kept (new-blog '(("action" . "publish") ("f-title" . "Kept"))))
         (unpublished (new-blog '(("action" . "publish") ("f-title" . "Unpublished later"))))
         (deleted (new-blog '(("action" . "publish") ("f-title" . "Deleted later"))))
         (media (media-id (insert-media "website" :filename "cover.png" :mime "image/png" :size 1)))
         (first `(("f-title" . "First") ("f-slug" . "first") ("f-category" . "news") ("f-count" . "3")
                  ("f-body" . "<p>Rich <b>old</b></p><img src=x onerror=\"alert(1)\">")
                  ("f-cover" . ,media)
                  ("f-related" . ,kept) ("f-related" . ,unpublished) ("f-related" . ,deleted)))
         (id (new-blog (cons '("action" . "save") first)))
         (url (format nil "/s/website/m/blog/~a" id)))
    (edit url  :form (cons '("action" . "publish") first))
    (edit url  :form '(("action" . "save") ("f-title" . "Second") ("f-category" . "tech")))
    (ok (equal (mapcar #'revision-event (list-revisions id)) '("draft" "publish" "draft")))
    (ok (string= (revision-by (first (list-revisions id))) "owner") "the editor writes as the owner")
    (testing "the editor links to the history"
      (multiple-value-bind (status body) (request :get url)
        (ok (= status 200))
        (ok (search (format nil "href=\"~a/history\"" url) body))))
    (testing "every change, each against the one before"
      (multiple-value-bind (status body) (request :get (format nil "~a/history" url))
        (ok (= status 200))
        (ok (search "All changes (3)" body))
        (ok (search "Published (1)" body))
        (ok (search "Draft saved" body))
        (let ((ids (mapcar #'revision-id (list-revisions id))))
          (ok (< (search (format nil "revision=~a\"" (first ids)) body)
                 (search (format nil "revision=~a\"" (car (last ids))) body))
              "newest first"))
        (ok (search "The oldest version in this view." body))
        (ok (search "cover.png" body) "a media id is shown with its file name")
        (ok (search "Kept (" body) "a reference is shown with its label")
        (ok (search "<iframe sandbox=\"allow-same-origin\"" body) "rich text is drawn in a sandbox without scripts")
        (ok (search "<b>old</b>" body) "as the frame's own document")
        (let ((outside (cl-ppcre:regex-replace-all "srcdoc=\"[^\"]*\"" body "")))
          (ng (search "<b>old</b>" outside) "and never as markup of this page")
          (ng (search "onerror" outside)))
        (ng (search "NIL" body))))
    (testing "the published versions alone"
      (multiple-value-bind (status body) (request :get (format nil "~a/history" url) :query "view=published")
        (ok (= status 200))
        (ng (search "Draft saved" body))
        (ok (search "Published" body))))
    ;; the world moves on: a referenced content is unpublished, another deleted,
    ;; the media is gone, an option and a field are taken out of the schema. The
    ;; two contents go past the guard that keeps a referenced content: this one
    ;; still refers to them, and a revision is what outlives that
    (koya-server/usecases/ports/contents:unpublish-content unpublished)
    (koya-server/usecases/ports/contents:delete-content deleted)
    (delete-media "website" media)
    (save-schema "website"
                 (make-schema :models (list (make-model "blog" :list
                                                        (remove-if (lambda (f) (member (koya/core/schema:field-name f) '("count") :test #'string=))
                                                                   (mapcar (lambda (f)
                                                                             (if (string= (koya/core/schema:field-name f) "category")
                                                                                 (make-field :category :select :options '("tech" "other"))
                                                                                 f))
                                                                           (koya/core/schema:model-fields (blog-model))))
                                                        :label :title
                                                        :preview-url "https://site.test/blog/{CONTENT_ID}?draft-key={DRAFT_KEY}"
                                                        :public-url "https://site.test/blog/{CONTENT_ID}")
                                            (make-model "about" :object (list (make-field :body :richtext))))))
    (let* ((published (find "publish" (list-revisions id) :key #'revision-event :test #'string=))
           (before (count-revisions id)))
      (testing "a restore fills the editor with what can come back, and says what cannot"
        (multiple-value-bind (status body)
            (request :get url :query (format nil "revision=~a" (revision-id published)))
          (ok (= status 200))
          (ok (search "Restoring the version of" body))
          (ok (search "value=\"First\"" body) "the old title is in the form")
          (ok (search "value=\"first\"" body) "and its slug, which nobody else has taken")
          (ok (search "<strong>count</strong> is no longer a field" body))
          (ok (search "<strong>category</strong> keeps the current value" body))
          (ok (search "value=\"tech\" selected" body) "the option that is gone leaves the current one")
          (ok (search "<strong>related</strong> lost 2 references" body))
          (ok (search (format nil "value=\"~a\" selected" kept) body) "a published reference comes back")
          (ng (search (format nil "value=\"~a\" selected" unpublished) body) "an unpublished one does not")
          (ng (search deleted body) "nor a deleted one")
          (ok (search "<strong>cover</strong> lost 1 media" body))
          (ng (search media body) "the media that is gone is not in the form")
          (ng (search "NIL" body))))
      (testing "and writes nothing until it is saved"
        (ok (= (count-revisions id) before))
        (ok (string= (jget (content-draft (get-content id)) "title") "Second")))
      (testing "saving it is an ordinary draft save"
        (edit url  :form `(("action" . "save") ("f-title" . "First") ("f-slug" . "first")
                                   ("f-category" . "tech") ("f-related" . ,kept)))
        (ok (= (count-revisions id) (1+ before)))
        (ok (string= (jget (content-draft (get-content id)) "title") "First"))
        (ok (string= (content-status (get-content id)) "published+draft") "what is live is untouched")))
    (testing "a revision this content does not have"
      (multiple-value-bind (status body) (request :get url :query "revision=999999")
        (ok (= status 200))
        (ok (search "does not exist for this content" body))
        (ng (search "Restoring the version of" body))))
    (testing "a deleted content has no history left"
      (edit url  :form '(("action" . "delete")))
      (ok (= (count-revisions id) 0))
      (ok (= (request :get (format nil "~a/history" url)) 404))))
  (save-schema "website"
               (make-schema :models (list (blog-model)
                                          (make-model "about" :object (list (make-field :body :richtext)))))))

(deftest a-content-is-named-by-its-model-label
  (exec "DELETE FROM contents")
  (let* ((target (new-blog '(("action" . "publish") ("f-title" . "Named target"))))
         (pointer (new-blog `(("action" . "save") ("f-title" . "Pointer") ("f-related" . ,target)))))
    (flet ((list-body () (nth-value 1 (request :get "/s/website/m/blog"))))
      (ok (search "Named target" (list-body)) "the declared field names the reference")
      (ok (search "title=\"Pointer\">Pointer</span>"
                  (nth-value 1 (request :get (format nil "/s/website/m/blog/~a" pointer))))
          "and the editor's crumb")
      (ok (search ">Pointer</a>"
                  (nth-value 1 (request :get (format nil "/s/website/m/blog/~a/history" pointer))))
          "and the history's")
      (save-schema "website"
                   (make-schema :models (list (make-model "blog" :list (koya/core/schema:model-fields (blog-model)))
                                              (make-model "about" :object (list (make-field :body :richtext))))))
      (unwind-protect
           (let ((body (list-body)))
             (ok (search (format nil ">~a<" target) body)
                 "without a :label the reference is its id")
             (multiple-value-bind (status editor) (request :get (format nil "/s/website/m/blog/~a" pointer))
               (ok (= status 200))
               (ok (search (format nil "value=\"~a\" selected>~a<" target target) editor)
                   "and so is the option that picks it")
               (ok (search (format nil "title=\"~a\">~a</span>" pointer pointer) editor)
                   "and the crumb")))
        (save-schema "website"
                     (make-schema :models (list (blog-model)
                                                (make-model "about" :object (list (make-field :body :richtext))))))))))


(deftest a-referenced-content-is-not-deleted-from-the-editor
  (exec "DELETE FROM contents")
  (multiple-value-bind (space model) (resolve-model "website" "blog")
    (let* ((target (content-id (create space model (koya/core/json:jobject "title" "Target") :publish t)))
           (path (format nil "/s/website/m/blog/~a" target)))
      (create space model (koya/core/json:jobject "title" "Refers" "related" (vector target)) :publish t)
      (multiple-value-bind (status body headers) (edit path :form '(("action" . "delete")))
        (ok (= status 409))
        (ok (equal (getf headers :hx-reswap) "none") "the editor stays as it is")
        (ok (null (moved-to headers)) "and on this content, not the list")
        (ok (search "referenced by 1 other content" body) "the toast says why")
        (ok (get-content target) "it is still there")))))

(deftest history-is-read-in-place
  (exec "DELETE FROM contents")
  (let* ((id (new-blog '(("action" . "publish") ("f-title" . "Once"))))
         (path (format nil "/s/website/m/blog/~a/history" id)))
    (edit (format nil "/s/website/m/blog/~a" id) :form '(("action" . "save") ("f-title" . "Twice")))
    (testing "the tabs call the action"
      (ok (search (subseq (browse-history) 0 (position #\? (browse-history))) (nth-value 1 (request :get path)))))
    (testing "a tab draws #revisions and puts the view in the URL"
      (multiple-value-bind (status body headers)
          (call-action :get (browse-history :space "website" :model "blog" :id id :view "published" :page 1))
        (ok (= status 200))
        (ok (search "id=\"revisions\"" body))
        (ng (search "Draft saved" body) "the published versions alone")
        (ok (string= (getf headers :hx-replace-url) (format nil "~a?view=published" path)))))
    (ok (= 404 (call-action :get (browse-history :space "website" :model "blog" :id "nope"))))))

(deftest a-draft-that-changes-nothing-is-none
  (exec "DELETE FROM contents")
  (let* ((id (new-blog '(("action" . "publish") ("f-title" . "Live") ("f-slug" . "live"))))
         (path (format nil "/s/website/m/blog/~a" id))
         (form '(("f-title" . "Live") ("f-slug" . "live"))))
    (testing "the form and its Save draft are marked for the script that turns it on"
      (let ((body (nth-value 1 (request :get path))))
        (ok (search "data-save-draft" body))
        (ok (search "data-editor-form" body))
        (ng (search "data-unsaved" body) "what is shown is what is stored")))
    (testing "saving what is published already writes nothing"
      (let ((before (count-revisions id)))
        (multiple-value-bind (status body) (edit path :form (cons '("action" . "save") form))
          (ok (= status 200))
          (ok (search "Nothing to save." body)))
        (ok (= (count-revisions id) before) "no revision")
        (ok (string= (koya-server/domain/content:content-status (get-content id)) "published") "and no draft")))
    (testing "a draft taken back to the published data is dropped, and the history says so"
      (edit path :form '(("action" . "save") ("f-title" . "Changed") ("f-slug" . "live")))
      (ok (string= (koya-server/domain/content:content-status (get-content id)) "published+draft"))
      (multiple-value-bind (status body) (edit path :form (cons '("action" . "save") form))
        (ok (= status 200))
        (ok (search "Back to the published version" body)))
      (ok (string= (koya-server/domain/content:content-status (get-content id)) "published") "the draft is gone")
      (ok (string= (revision-event (first (list-revisions id))) "discard")
          "and it went as a discard, which has something to show"))
    (testing "a restore is marked unsaved"
      (let ((revision (revision-id (car (last (list-revisions id))))))
        (ok (search "data-unsaved" (nth-value 1 (request :get path :query (format nil "revision=~a" revision)))))))))
