(defpackage #:koya-tests/server/web/pages/space-import
  (:use #:cl #:rove)
  (:import-from #:koya-tests/server/web/pages/support #:post-login #:*secret* #:*cookie* #:request #:location #:setup-pages #:log-in)
  (:import-from #:koya-server/infra/db/connection #:disconnect-db)
  (:import-from #:koya-server/usecases/ports/spaces
                #:save-schema #:find-space #:delete-space #:list-deploys #:load-schema
                #:space-webhooks #:space-webhook-secret)
  (:import-from #:koya-server/usecases/spaces/lifecycle #:create-space)
  (:import-from #:koya-server/usecases/ports/keys
                #:create-delivery-key #:list-delivery-keys #:create-management-key)
  (:import-from #:koya-server/domain/content
                #:content-status #:content-published #:content-draft #:content-id
                #:content-draft-key #:content-created-at #:content-published-at)
  (:import-from #:koya-server/usecases/ports/media
                #:list-media #:media-file-path #:write-media-file #:delete-media-file)
  (:import-from #:koya-server/domain/media #:media-id #:media-filename #:media-space #:media-mime)
  (:import-from #:koya-tests/server/usecases/media/library #:png-bytes)
  (:import-from #:koya-tests/server/fake-webhooks #:*webhook-sender*)
  (:import-from #:koya/core/schema #:make-webhook)
  (:import-from #:koya/core/schema #:make-field #:make-model #:make-schema)
  (:import-from #:koya-server/domain/deploy #:deploy-by)
  (:import-from #:koya-server/usecases/ports/contents
                #:list-revisions #:count-revisions #:get-content #:create-content #:save-draft)
  (:import-from #:koya-server/domain/revision #:revision-event)
  (:import-from #:koya/core/json #:jget)
  (:import-from #:alexandria #:alist-hash-table)
  (:import-from #:babel #:string-to-octets)
  (:import-from #:koya-server/usecases/media/library
                #:store-upload #:remove-space-media)
  (:import-from #:koya/core/schema #:schema-models #:model-name #:webhook-url)
  (:import-from #:koya-server/web/pages/index
                #:begin-import-action #:continue-import-action #:finish-import-action)
  (:import-from #:koya-server/infra/env #:archive-dir))
(in-package #:koya-tests/server/web/pages/space-import)

(setup (setup-pages) (log-in))

(teardown (disconnect-db))

(defun archive-schema ()
  (make-schema :webhooks (list (make-webhook "site" "https://site.test/hook"))
               :models (list (make-model "tag" :list (list (make-field :name :text)))
                             (make-model "post" :list (list (make-field :title :text)
                                                            (make-field :cover :media)
                                                            (make-field :body :richtext)
                                                            (make-field :tags :reference :model "tag" :many t))
                                         :label :title))))

(defparameter +as-htmx+ '(("origin" . "http://localhost:3000") ("hx-request" . "true"))
  "What the import dialog's fetch sends: an action answers htmx requests only.")

(defun post-piece (url &optional (octets (make-array 0 :element-type '(unsigned-byte 8))) (headers +as-htmx+))
  "POST OCTETS to the action at URL as the import dialog does. (values status body headers)."
  (let ((q (position #\? url)))
    (request :post (subseq url 0 q) :query (and q (subseq url (1+ q))) :headers headers
                                    :body octets :content-type "application/octet-stream")))

(defun begin ()
  (string-trim '(#\Space #\Newline) (nth-value 1 (post-piece (begin-import-action)))))

(defun piece-url (id offset)
  (format nil "~a?id=~a&offset=~a" (continue-import-action) id offset))

(defun import-archive (octets &key (pieces 3))
  "Send OCTETS to the import actions in PIECES pieces, as the import dialog does;
(values status next-location) of the last answer."
  (let ((id (begin))
        (size (max 1 (ceiling (length octets) pieces))))
    (loop :for offset :from 0 :below (length octets) :by size
          :do (post-piece (piece-url id offset) (subseq octets offset (min (length octets) (+ offset size)))))
    (multiple-value-bind (status body headers) (post-piece (format nil "~a?id=~a" (finish-import-action) id))
      (declare (ignore body))
      (values status (getf headers :hx-redirect)))))

(defun archive-files (pattern)
  "The files in the archive directory whose names contain PATTERN."
  (let ((directory (archive-dir)))
    (and (uiop:directory-exists-p directory)
         (remove-if-not (lambda (file) (search pattern (file-namestring file)))
                        (uiop:directory-files directory)))))

(deftest a-space-is-exported-and-imported-again
  (setf *cookie* nil)
  (post-login :form `(("secret" . ,*secret*)))
  (create-space "archive")
  (save-schema "archive" (archive-schema))
  (let* ((media (store-upload "archive" (png-bytes 4 5) :filename "cover.png" :alt "A cover"))
         (tag (content-id (create-content "archive" "tag" (alist-hash-table '(("name" . "lisp")) :test 'equal)
                                          :publish t :id "tag-1" :created-at "2020-01-01T00:00:00.000Z"
                                          :published-at "2020-01-02T00:00:00.000Z")))
         (post (content-id (create-content "archive" "post"
                                           (alist-hash-table `(("title" . "Old") ("cover" . ,(media-id media))
                                                               ("tags" . ,(vector tag)))
                                                             :test 'equal)
                                           :publish t)))
         (old-secret (space-webhook-secret "archive"))
         (delivery-key (create-delivery-key "archive" :label "site"))
         (management-key (create-management-key "archive" :label "repl"))
         (sent 0)
         octets)
    (save-draft post (alist-hash-table `(("title" . "New")
                                         ("body" . ,(format nil "<p><img src=\"/media/archive/~a.png\"></p>" (media-id media))))
                                       :test 'equal))
    (testing "the space page offers the export"
      (let ((body (nth-value 1 (request :get "/s/archive"))))
        (ok (search "href=\"/s/archive/export\"" body))
        (ng (search "download" body) "a failed export must show its toast, not be saved as a file")))
    (testing "export is a zip download"
      (multiple-value-bind (status body headers) (request :get "/s/archive/export")
        (ok (= status 200))
        (ok (string= (getf headers :content-type) "application/zip"))
        (ok (search "attachment; filename=\"archive-" (getf headers :content-disposition)))
        (ok (typep body '(vector (unsigned-byte 8))))
        (ok (equalp (subseq body 0 2) #(80 75)) "PK")
        (setf octets body)))
    (delete-space "archive")
    (remove-space-media "archive")
    (let ((*webhook-sender* (lambda (url payload headers)
                              (declare (ignore url payload headers))
                              (incf sent))))
      (testing "import makes the space again"
        (multiple-value-bind (status location) (import-archive octets)
          (ok (= status 200))
          (ok (string= location "/s/archive")))
        (ok (search "Space archive imported." (nth-value 1 (request :get "/s/archive"))))
        (ok (equal (mapcar #'model-name (schema-models (load-schema "archive"))) '("tag" "post")))
        (ok (equal (mapcar #'webhook-url (space-webhooks "archive")) '("https://site.test/hook"))
            "with its webhooks")
        (ok (string= (space-webhook-secret "archive") old-secret)
            "and its webhook secret, which the site checks")
        (ok (= sent 0) "and nothing is sent to them"))
      (testing "the site's keys still work"
        (ok (string= (koya-server/usecases/ports/keys:space-for-delivery-key delivery-key) "archive"))
        (ok (string= (koya-server/usecases/ports/keys:space-for-management-key management-key) "archive"))
        (ok (equal (mapcar (lambda (k) (getf k :label)) (list-delivery-keys "archive")) '("site"))))
      (testing "contents keep their ids, state, draft, timestamps and history"
        (let ((tag-content (get-content tag))
              (post-content (get-content post)))
          (ok (string= (content-created-at tag-content) "2020-01-01T00:00:00.000Z"))
          (ok (string= (content-published-at tag-content) "2020-01-02T00:00:00.000Z"))
          (ok (string= (content-status post-content) "published+draft"))
          (ok (string= (jget (content-published post-content) "title") "Old"))
          (ok (string= (jget (content-draft post-content) "title") "New"))
          (ok (equalp (jget (content-published post-content) "tags") (vector tag)))
          (ok (content-draft-key post-content) "the preview link still works")
          (ok (= (count-revisions post) 2))
          (ok (equal (mapcar #'revision-event (list-revisions post)) '("draft" "publish")))))
      (testing "media keep their ids, metadata and files"
        (let ((copy (find (media-id media) (list-media "archive") :key #'media-id :test #'string=)))
          (ok copy)
          (ok (string= (media-filename copy) "cover.png"))
          (ok (string= (koya-server/domain/media:media-alt copy) "A cover"))
          (ok (equalp (alexandria:read-file-into-byte-vector (media-file-path (media-space copy) (media-id copy) (media-mime copy))) (png-bytes 4 5)))))
      (testing "the import is in the deploy log, named for whoever made it"
        (ok (equal (mapcar #'deploy-by (list-deploys "archive")) '("owner"))))
      (testing "a space that has models is not imported into"
        (multiple-value-bind (status location) (import-archive octets)
          (ok (= status 200))
          (ok (string= location "/")))
        (ok (search "is not empty" (nth-value 1 (request :get "/"))))
        (ok (= (length (list-deploys "archive")) 1) "and nothing changed"))
      (testing "a space whose models went but whose media stayed is not empty"
        (save-schema "archive" (make-schema))
        (let ((path (let ((m (find (media-id media) (list-media "archive") :key #'media-id :test #'string=)))
                      (media-file-path (media-space m) (media-id m) (media-mime m)))))
          (multiple-value-bind (status location) (import-archive octets)
            (ok (= status 200))
            (ok (string= location "/")))
          (ok (search "is not empty" (nth-value 1 (request :get "/"))))
          (ok (probe-file path) "its file is still there")
          (ok (find (media-id media) (list-media "archive") :key #'media-id :test #'string=))))
      (testing "nor is one that has only a key"
        (delete-space "archive")
        (remove-space-media "archive")
        (create-space "archive")
        (create-delivery-key "archive")
        (ok (string= (nth-value 1 (import-archive octets)) "/"))
        (ok (search "is not empty" (nth-value 1 (request :get "/"))))
        (ng (get-content post)))
      (testing "one that has only webhooks is imported into, and they are replaced"
        (delete-space "archive")
        (remove-space-media "archive")
        (create-space "archive")
        (save-schema "archive" (make-schema :webhooks (list (make-webhook "old" "https://old.test/hook"))))
        (ok (string= (nth-value 1 (import-archive octets)) "/s/archive"))
        (ok (get-content post))
        (ok (equal (mapcar #'webhook-url (space-webhooks "archive")) '("https://site.test/hook")))
        (ok (string= (space-webhook-secret "archive") old-secret))))
    (testing "a file that is not an archive changes nothing"
      (delete-space "archive")
      (remove-space-media "archive")
      (multiple-value-bind (status location) (import-archive (string-to-octets "not a zip"))
        (ok (= status 200))
        (ok (string= location "/")))
      (ok (search "not a zip archive" (nth-value 1 (request :get "/"))))
      (ng (find-space "archive")))
    (testing "a file already in the library is never replaced, and the import changes nothing"
      (write-media-file "archive" (media-id media) "image/png" (png-bytes 1 1))
      (ok (string= (nth-value 1 (import-archive octets)) "/"))
      (ok (search "already in the media library" (nth-value 1 (request :get "/"))))
      (ng (find-space "archive"))
      (ok (equalp (alexandria:read-file-into-byte-vector (media-file-path "archive" (media-id media) "image/png"))
                  (png-bytes 1 1))
          "the file that was there is as it was")
      (remove-space-media "archive"))
    (testing "a space whose file has gone is not exported, and says why"
      (ok (string= (nth-value 1 (import-archive octets)) "/s/archive"))
      (delete-media-file "archive" (media-id media) "image/png")
      (multiple-value-bind (status body headers) (request :get "/s/archive/export")
        (declare (ignore body))
        (ok (= status 303))
        (ok (string= (getf headers :location) "/s/archive")))
      (ok (search "missing from the media library" (nth-value 1 (request :get "/s/archive"))))
      (delete-space "archive")
      (remove-space-media "archive"))
    (testing "pieces go where they say, in order"
      (let ((id (begin)))
        (ok (= 409 (post-piece (piece-url id 5) (subseq octets 0 5))) "one that skips ahead is refused")
        (ok (search "has 0 bytes" (nth-value 1 (post-piece (piece-url id 5) (subseq octets 0 5))))
            "and says where the import stands")
        (ok (= 200 (post-piece (piece-url id 0) (subseq octets 0 5))))
        (ok (= 409 (post-piece (piece-url id 0) (subseq octets 0 5))) "one sent twice is refused")
        (ok (string= (string-trim '(#\Space) (nth-value 1 (post-piece (piece-url id 5) (subseq octets 5 9))))
                     "9")
            "the next one is taken, and the answer is how much has arrived")))
    (testing "an import that was never begun is not found"
      (ok (= 404 (post-piece (piece-url "01ARZ3NDEKTSV4RRFFQ69G5FAV" 0) (subseq octets 0 5))))
      (ok (= 404 (post-piece (piece-url "../../etc/passwd" 0) (subseq octets 0 5))) "nor is a path"))
    (testing "an import is gone once it is finished, and one given up is cleared a day later"
      (let ((stale (begin))
            (count (length (archive-files ".upload"))))
        (sb-posix:utime (merge-pathnames (format nil "~a.upload" stale) (archive-dir))
                        (- (get-universal-time) #.(encode-universal-time 0 0 0 1 1 1970 0) (* 2 24 3600))
                        (- (get-universal-time) #.(encode-universal-time 0 0 0 1 1 1970 0) (* 2 24 3600)))
        (ok (string= (nth-value 1 (import-archive (string-to-octets "not a zip"))) "/"))
        (ok (null (archive-files stale)) "the one given up a day ago is gone")
        (ok (= (length (archive-files ".upload")) (1- count)) "and so is the one just finished")))
    (testing "a file larger than an upload may be is refused before it is read"
      (let ((koya-server/domain/media:+max-upload-bytes+ 10))
        (ok (string= (nth-value 1 (import-archive octets)) "/")))
      (ok (search "larger than an upload may be" (nth-value 1 (request :get "/"))))
      (ng (find-space "archive")))
    (testing "an export leaves nothing behind"
      (ok (string= (nth-value 1 (import-archive octets)) "/s/archive"))
      (ok (= 200 (request :get "/s/archive/export")))
      (ok (null (archive-files "export-")) "the archive is deleted once it is sent")
      (delete-space "archive")
      (remove-space-media "archive"))
    (testing "an import from another site is refused"
      (ok (= 403 (post-piece (begin-import-action) nil '(("origin" . "https://evil.test") ("hx-request" . "true")))))
      (ok (= 400 (post-piece (begin-import-action) nil '(("origin" . "http://localhost:3000"))))
          "nor is a plain post: an action answers htmx only")
      (ng (find-space "archive")))
    (testing "the import dialog is on the spaces page"
      (let ((page (nth-value 1 (request :get "/"))))
        (ok (search (format nil "data-import-begin=\"~a\"" (begin-import-action)) page))
        (ok (search "data-import-piece-bytes=" page))))))
