(defpackage #:koya-server/web/admin-api/me
  (:use #:cl)
  (:import-from #:koya-core/json #:jobject #:json-null)
  (:import-from #:jingle #:*request* #:request-env)
  (:import-from #:koya-server/web/lib/auth #:session-owner-p #:calling-space)
  (:export #:@get))
(in-package #:koya-server/web/admin-api/me)

(defun @get (params)
  (declare (ignore params))
  (let ((owner (session-owner-p (getf (request-env *request*) :lack.session))))
    (jobject "owner" (and owner t)
             "management" (not owner)
             "space" (if owner json-null (calling-space))
             "version" (load-time-value (asdf:component-version (asdf:find-system :koya-server))))))
