(defpackage #:koya-server/domain/image
  (:use #:cl)
  (:import-from #:ironclad #:digest-sequence)
  (:export #:sniff-image
           #:strip-metadata
           #:image-extension
           #:+image-types+))
(in-package #:koya-server/domain/image)

(defparameter +image-types+
  '(("image/png" . "png") ("image/jpeg" . "jpg") ("image/gif" . "gif") ("image/webp" . "webp")))

(defun image-extension (mime)
  (cdr (assoc mime +image-types+ :test #'string=)))

(defun u16be (v i) (logior (ash (aref v i) 8) (aref v (1+ i))))
(defun u16le (v i) (logior (aref v i) (ash (aref v (1+ i)) 8)))
(defun u32be (v i) (logior (ash (u16be v i) 16) (u16be v (+ i 2))))
(defun u24le (v i) (logior (u16le v i) (ash (aref v (+ i 2)) 16)))
(defun u32le (v i) (logior (u16le v i) (ash (u16le v (+ i 2)) 16)))

(defun prefix-p (bytes i &rest expected)
  (and (<= (+ i (length expected)) (length bytes))
       (loop :for e :in expected :for k :from i
             :always (or (null e) (= (aref bytes k) e)))))

(defun png-size (bytes)
  (when (and (>= (length bytes) 24) (prefix-p bytes 12 #x49 #x48 #x44 #x52))
    (values (u32be bytes 16) (u32be bytes 20))))

(defun gif-size (bytes)
  (when (>= (length bytes) 10)
    (values (u16le bytes 6) (u16le bytes 8))))

(defun jpeg-size (bytes)
  (let ((i 2) (n (length bytes)))
    (loop
      (when (> (+ i 9) n) (return nil))
      (unless (= (aref bytes i) #xFF) (return nil))
      (let ((marker (aref bytes (1+ i))))
        (cond ((= marker #xFF) (incf i))
              ((or (<= #xC0 marker #xC3) (<= #xC5 marker #xC7) (<= #xC9 marker #xCB) (<= #xCD marker #xCF))
               (return (values (u16be bytes (+ i 7)) (u16be bytes (+ i 5)))))
              ((or (= marker #xD8) (<= #xD0 marker #xD7) (= marker #x01)) (incf i 2))
              (t (incf i (+ 2 (u16be bytes (+ i 2))))))))))

(defun webp-size (bytes)
  (when (and (>= (length bytes) 30) (prefix-p bytes 8 #x57 #x45 #x42 #x50))
    (cond ((prefix-p bytes 12 #x56 #x50 #x38 #x20)
           (values (logand (u16le bytes 26) #x3FFF) (logand (u16le bytes 28) #x3FFF)))
          ((prefix-p bytes 12 #x56 #x50 #x38 #x4C)
           (let ((b (u32be (reverse (subseq bytes 21 25)) 0)))
             (values (1+ (logand b #x3FFF)) (1+ (logand (ash b -14) #x3FFF)))))
          ((prefix-p bytes 12 #x56 #x50 #x38 #x58)
           (values (1+ (u24le bytes 24)) (1+ (u24le bytes 27)))))))

(defun sniff-image (bytes)
  (let ((bytes (coerce bytes '(simple-array (unsigned-byte 8) (*)))))
    (cond ((prefix-p bytes 0 #x89 #x50 #x4E #x47 #x0D #x0A #x1A #x0A)
           (multiple-value-bind (w h) (png-size bytes) (values "image/png" w h)))
          ((prefix-p bytes 0 #xFF #xD8 #xFF)
           (multiple-value-bind (w h) (jpeg-size bytes) (values "image/jpeg" w h)))
          ((or (prefix-p bytes 0 #x47 #x49 #x46 #x38 #x39 #x61) (prefix-p bytes 0 #x47 #x49 #x46 #x38 #x37 #x61))
           (multiple-value-bind (w h) (gif-size bytes) (values "image/gif" w h)))
          ((and (prefix-p bytes 0 #x52 #x49 #x46 #x46) (prefix-p bytes 8 #x57 #x45 #x42 #x50))
           (multiple-value-bind (w h) (webp-size bytes) (values "image/webp" w h)))
          (t nil))))

(defun octets (&rest parts)
  (let ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (labels ((put (part)
               (etypecase part
                 (integer (vector-push-extend part out))
                 (string (loop :for c :across part :do (vector-push-extend (char-code c) out)))
                 (sequence (map nil #'put part)))))
      (map nil #'put parts))
    (coerce out '(simple-array (unsigned-byte 8) (*)))))

(defun at-p (bytes i &rest parts)
  (apply #'prefix-p bytes i (coerce (apply #'octets parts) 'list)))

(defun be16 (n) (list (ldb (byte 8 8) n) (ldb (byte 8 0) n)))
(defun be32 (n) (list (ldb (byte 8 24) n) (ldb (byte 8 16) n) (ldb (byte 8 8) n) (ldb (byte 8 0) n)))
(defun le32 (n) (reverse (be32 n)))

(defun tiff-orientation (bytes start end)
  (let* ((big (at-p bytes start "MM"))
         (u16 (if big #'u16be #'u16le))
         (u32 (if big #'u32be #'u32le)))
    (when (and (<= (+ start 8) end) (or big (at-p bytes start "II")))
      (let ((ifd (+ start (funcall u32 bytes (+ start 4)))))
        (when (<= (+ ifd 2) end)
          (loop :for k :below (funcall u16 bytes ifd)
                :for entry := (+ ifd 2 (* 12 k))
                :while (<= (+ entry 12) end)
                :when (and (= (funcall u16 bytes entry) #x0112) (= (funcall u16 bytes (+ entry 2)) 3))
                  :return (let ((value (funcall u16 bytes (+ entry 8))))
                            (and (<= 2 value 8) value))))))))

(defun orientation-tiff (orientation)
  (octets "MM" 0 42 (be32 8) (be16 1) (be16 #x0112) (be16 3) (be32 1) (be16 orientation) 0 0 (be32 0)))

(defun strip-jpeg (bytes)
  (let ((n (length bytes)) (i 2) (parts '()) (orientation nil))
    (flet ((keep (from to) (push (subseq bytes from to) parts)))
      (loop
        (when (>= i n) (return))
        (when (or (> (+ i 2) n) (/= (aref bytes i) #xFF)) (keep i n) (return))
        (let ((marker (aref bytes (1+ i))))
          (cond ((= marker #xFF) (incf i))
                ((= marker #xD9) (keep i (+ i 2)) (return))
                ((or (<= #xD0 marker #xD7) (= marker #x01)) (keep i (+ i 2)) (incf i 2))
                ((> (+ i 4) n) (keep i n) (return))
                (t
                 (let ((end (+ i 2 (u16be bytes (+ i 2)))))
                   (when (> end n) (keep i n) (return))
                   (cond ((= marker #xDA)
                          (keep i end)
                          (let ((j (loop :for j :from end :below (1- n)
                                         :when (and (= (aref bytes j) #xFF)
                                                    (not (member (aref bytes (1+ j)) '(#x00 #xD0 #xD1 #xD2 #xD3 #xD4 #xD5 #xD6 #xD7))))
                                           :return j
                                         :finally (return n))))
                            (keep end j)
                            (setf end j)))
                         ((= marker #xE1)
                          (when (at-p bytes (+ i 4) "Exif" 0 0)
                            (setf orientation (or orientation (tiff-orientation bytes (+ i 10) end)))))
                         ((or (and (= marker #xE0) (at-p bytes (+ i 4) "JFIF" 0))
                              (and (= marker #xE2) (at-p bytes (+ i 4) "ICC_PROFILE" 0))
                              (and (= marker #xEE) (at-p bytes (+ i 4) "Adobe")))
                          (keep i end))
                         ((or (<= #xE0 marker #xEF) (= marker #xFE)))
                         (t (keep i end)))
                   (setf i end)))))))
    (setf parts (nreverse parts))
    (when orientation
      (let ((exif (octets #xFF #xE1 (be16 34) "Exif" 0 0 (orientation-tiff orientation))))
        (if (and parts (at-p (first parts) 0 #xFF #xE0))
            (push exif (cdr parts))
            (push exif parts))))
    (octets #xFF #xD8 parts)))

(defun png-chunk (type data)
  (let ((body (octets type data)))
    (octets (be32 (length data)) body (digest-sequence :crc32 body))))

(defun strip-png (bytes)
  (let ((n (length bytes)) (i 8) (parts '()))
    (flet ((keep (from to) (push (subseq bytes from to) parts)))
      (loop
        (when (>= i n) (return))
        (when (> (+ i 12) n) (keep i n) (return))
        (let* ((length (u32be bytes i))
               (end (+ i 12 length))
               (type (map 'string #'code-char (subseq bytes (+ i 4) (+ i 8)))))
          (when (> end n) (keep i n) (return))
          (cond ((member type '("tEXt" "zTXt" "iTXt" "tIME") :test #'string=))
                ((string= type "eXIf")
                 (let ((orientation (tiff-orientation bytes (+ i 8) (+ i 8 length))))
                   (when orientation (push (png-chunk "eXIf" (orientation-tiff orientation)) parts))))
                (t (keep i end)))
          (when (string= type "IEND") (return))
          (setf i end))))
    (octets (subseq bytes 0 8) (nreverse parts))))

(defun riff-chunk (type data)
  (octets type (le32 (length data)) data (when (oddp (length data)) 0)))

(defun strip-webp (bytes)
  (let ((n (min (length bytes) (+ 8 (u32le bytes 4)))))
    (if (at-p bytes 12 "VP8X")
        (strip-vp8x bytes n)
        (subseq bytes 0 n))))

(defun strip-vp8x (bytes n)
  (let ((i 12) (parts '()) (orientation nil))
    (flet ((keep (from to) (push (subseq bytes from (min to n)) parts)))
      (loop
        (when (>= i n) (return))
        (when (> (+ i 8) n) (keep i n) (return))
        (let* ((size (u32le bytes (+ i 4)))
               (start (+ i 8))
               (end (+ start size (logand size 1))))
          (when (> (+ start size) n) (keep i n) (return))
          (cond ((at-p bytes i "EXIF")
                 (let ((tiff (if (at-p bytes start "Exif" 0 0) (+ start 6) start)))
                   (setf orientation (or orientation (tiff-orientation bytes tiff (+ start size))))))
                ((at-p bytes i "XMP "))
                (t (keep i end)))
          (setf i end))))
    (setf parts (nreverse parts))
    (let ((vp8x (copy-seq (first parts))))
      (when (> (length vp8x) 8)
        (setf (aref vp8x 8) (logior (logand (aref vp8x 8) (lognot #x0C)) (if orientation #x08 0)))
        (setf (first parts) vp8x)))
    (let ((body (octets "WEBP" parts (when orientation (riff-chunk "EXIF" (orientation-tiff orientation))))))
      (octets "RIFF" (le32 (length body)) body))))

(defun strip-metadata (bytes mime)
  (let ((bytes (coerce bytes '(simple-array (unsigned-byte 8) (*)))))
    (cond ((string= mime "image/jpeg") (strip-jpeg bytes))
          ((string= mime "image/png") (strip-png bytes))
          ((string= mime "image/webp") (strip-webp bytes))
          (t bytes))))
