(defpackage #:koya-spec/server/layers
  (:use #:cl #:rove)
  (:import-from #:okite #:define-layers #:layer-violations))
(in-package #:koya-spec/server/layers)

(define-layers koya-server
  (:layers (:domain          "domain/")
           (:presenter-ports "usecases/ports/presenters")
           (:ports           "usecases/ports/")
           (:usecases        "usecases/")
           (:infra           "infra/")
           (:web             "web/")
           (:ui              "web/ui/")
           (:pages           "web/pages/")
           (:api             "web/api/")
           (:admin-api       "web/admin-api/")
           (:main            "main"))
  (:allow (:ports           :domain :presenter-ports)
          (:presenter-ports :domain)
          (:usecases        :domain :ports :presenter-ports)
          (:infra           :domain :ports)
          (:web             :domain :usecases :presenter-ports)
          (:ui              :domain :usecases :web)
          (:pages           :domain :usecases :web :ui)
          (:api             :domain :usecases :web)
          (:admin-api       :domain :usecases :web)
          (:main            :domain :ports :presenter-ports :usecases :infra :web))
  (:isolated :pages :api :admin-api)
  (:libraries ("cl-dbi" :infra) ("zippy" :infra) ("dexador" :infra) ("usocket" :infra) ("cl-dotenv" :infra)
              ("clack" :main) ("lack" :web :infra) ("lack-mw" :web)
              ("jingle" :web :ui :pages :admin-api)
              ("ningle-actions" :web :ui :pages) ("ningle-fbr" :web) ("smart-buffer" :web)
              ("hsx" :web :ui :pages) ("okite" :main))
  (:anywhere "koya-core" "alexandria" "cl-ppcre" "babel" "ironclad" "local-time"
             "bordeaux-threads" "quri")
  (:forbid "koya-sdk" "ningle"))

(deftest layers
  (let ((violations (layer-violations 'koya-server)))
    (ok (null violations) (format nil "~{~a~^~%~}" violations))))
