(defpackage #:koya-server/web/admin-api/contents/<space>/<model>/index
  (:use #:cl)
  (:import-from #:koya-core/json #:jobject #:json-null)
  (:import-from #:koya-server/web/lib/http
                #:path-param #:read-json-body #:body-field #:fail-api #:ok-status)
  (:import-from #:koya-server/domain/query #:parse-query #:query-limit #:query-offset)
  (:import-from #:koya-core/schema #:model-kind)
  (:import-from #:koya-server/usecases/contents #:create #:object-content #:save-object)
  (:import-from #:koya-server/usecases/listing #:all-contents)
  (:import-from #:koya-server/web/lib/presenters #:admin-content->jobject)
  (:import-from #:koya-server/usecases/schema #:resolve-model #:resolve-object-model)
  (:export #:@get #:@post #:@patch))
(in-package #:koya-server/web/admin-api/contents/<space>/<model>/index)

(defun @get (params)
  (multiple-value-bind (space model) (resolve-model (path-param params :space) (path-param params :model))
    (if (eq (model-kind model) :object)
        (admin-content->jobject (object-content space model))
        (let ((query (parse-query params)))
          (multiple-value-bind (contents total) (all-contents space model query)
            (jobject "contents" (map 'vector #'admin-content->jobject contents)
                     "totalCount" total "offset" (query-offset query) "limit" (query-limit query)))))))

(defun @post (params)
  (multiple-value-bind (space model) (resolve-model (path-param params :space) (path-param params :model))
    (let* ((body (read-json-body))
           (data (body-field body "data")))
      (unless (hash-table-p data) (fail-api 400 "bad_request" "\"data\" must be an object"))
      (unless (member (body-field body "publish") (list t nil json-null))
        (fail-api 400 "bad_request" "\"publish\" must be true or false"))
      (let ((content (create space model data :publish (eq (body-field body "publish") t)
                             :id (body-field body "id")
                             :created-at (body-field body "createdAt")
                             :updated-at (body-field body "updatedAt")
                             :published-at (body-field body "publishedAt")
                             :revised-at (body-field body "revisedAt"))))
        (ok-status 201)
        (admin-content->jobject content)))))

(defun @patch (params)
  (multiple-value-bind (space model) (resolve-object-model (path-param params :space) (path-param params :model))
    (let ((data (body-field (read-json-body) "data")))
      (unless (hash-table-p data) (fail-api 400 "bad_request" "\"data\" must be an object"))
      (admin-content->jobject (save-object space model data)))))
