(defpackage #:koya-server/web/admin-api/contents/<space>/<model>/<id>/publish
  (:use #:cl)
  (:import-from #:koya-server/web/lib/http #:path-param #:read-json-body #:body-field)
  (:import-from #:koya-server/usecases/contents #:publish)
  (:import-from #:koya-server/web/lib/presenters #:admin-content->jobject)
  (:import-from #:koya-server/usecases/schema #:resolve-model)
  (:export #:@post))
(in-package #:koya-server/web/admin-api/contents/<space>/<model>/<id>/publish)

(defun @post (params)
  (multiple-value-bind (space model) (resolve-model (path-param params :space) (path-param params :model))
    (let* ((body (read-json-body))
           (data (body-field body "data")))
      (admin-content->jobject (publish space model (path-param params :id) (and (hash-table-p data) data)
                                       :published-at (body-field body "publishedAt"))))))
